export type AdditionalAnswerLine = {
  kind: "通用" | "特殊";
  text: string;
};

export type AdditionalTopic = {
  id: string;
  code: string;
  name: string;
  question: string;
  answer: AdditionalAnswerLine[];
};

export type AdditionalMaterial = {
  id: string;
  tab: string;
  title: string;
  tagline: string;
  description: string;
  storyline: string;
  modules: Array<{
    label: string;
    title: string;
    detail: string;
    sentence: string;
  }>;
  baseAnswer: string;
  topics: AdditionalTopic[];
  rules: string[];
};

const common = (text: string): AdditionalAnswerLine => ({ kind: "通用", text });
const special = (text: string): AdditionalAnswerLine => ({ kind: "特殊", text });

export const additionalMaterials: AdditionalMaterial[] = [
  {
    id: "shanghai",
    tab: "素材 03｜上海城市旅行",
    title: "通用素材 03：一次上海城市旅行",
    tagline: "城市 + 高楼 + 特色建筑 + 购物中心",
    description: "用一次三天的上海旅行串联城市环境、两座代表性建筑和一个购物中心。",
    storyline: "去年秋天去上海 → 城市新旧结合 → 上海中心 → 东方明珠 → 商场吃饭购物 → 喜欢这座城市",
    modules: [
      {
        label: "01 · 旅行背景",
        title: "三天的上海旅行",
        detail: "去年秋天与女朋友坐高铁去上海，在那里住了三天。",
        sentence: "Last autumn, I took a three-day trip to Shanghai with my girlfriend.",
      },
      {
        label: "02 · 城市印象",
        title: "现代与传统并存",
        detail: "既有现代高楼，也有老街、小店和具有历史感的建筑。",
        sentence: "What impressed me most was the mix of modern buildings and traditional streets.",
      },
      {
        label: "03 · 高楼",
        title: "上海中心",
        detail: "玻璃外观、很高、用于办公和观光，可以看到城市景色。",
        sentence: "Shanghai Tower is a huge glass building with offices and a viewing area near the top.",
      },
      {
        label: "04 · 特色建筑",
        title: "东方明珠",
        detail: "由几个球形结构组成，外观独特，很容易辨认。",
        sentence: "The Oriental Pearl Tower has several large round sections, so it looks very unusual and easy to recognise.",
      },
      {
        label: "05 · 商场",
        title: "陆家嘴的购物中心",
        detail: "环境干净明亮，有商店、餐厅和电影院，旅行中去那里吃饭休息。",
        sentence: "We also visited a large shopping mall in Lujiazui, where we had dinner and looked around the shops.",
      },
      {
        label: "06 · 总体感受",
        title: "适合参观和推荐",
        detail: "交通方便、活动丰富，旅行结束后仍然印象深刻。",
        sentence: "The trip was enjoyable because the city was convenient, lively and full of interesting places.",
      },
    ],
    baseAnswer:
      "I'd like to talk about a three-day trip I took to Shanghai with my girlfriend last autumn. We travelled there by high-speed train and stayed near the city centre. What impressed me most was the mix of modern buildings and traditional streets. We visited Shanghai Tower, which is a huge glass building with offices and a viewing area near the top. We also saw the Oriental Pearl Tower. Its large round sections made it look unusual and easy to recognise. During the trip, we visited a shopping mall in Lujiazui, where we had dinner and looked around the shops. Although the city was sometimes crowded, the transport was convenient and there was always something interesting to do. I really enjoyed the trip, and I would like to visit Shanghai again in the future.",
    topics: [
      {
        id: "shanghai-city",
        code: "S1",
        name: "去过并喜欢的城市",
        question: "Describe a city you have visited and liked.",
        answer: [
          special("I'd like to talk about Shanghai, a city I visited and really liked."),
          common("Last autumn, I took a three-day trip to Shanghai with my girlfriend."),
          special("We travelled by high-speed train and stayed near the city centre."),
          common("What impressed me most was the mix of modern buildings and traditional streets."),
          special("During the day, we visited famous places such as Shanghai Tower and the Oriental Pearl Tower. In the evening, we walked beside the river and enjoyed the city lights."),
          common("We also visited a large shopping mall in Lujiazui, where we had dinner and looked around the shops."),
          special("I liked Shanghai because the public transport was convenient and there were many different things to see and do. Although it was sometimes crowded, the city felt lively and exciting."),
          common("The trip was enjoyable because the city was convenient, lively and full of interesting places."),
          special("I hope I can visit it again and explore some quieter neighbourhoods next time."),
        ],
      },
      {
        id: "shanghai-tall-building",
        code: "S2",
        name: "喜欢的高楼",
        question: "Describe a tall building you like or dislike.",
        answer: [
          special("I'd like to talk about Shanghai Tower, a tall building that I really like."),
          common("Last autumn, I took a three-day trip to Shanghai with my girlfriend."),
          common("Shanghai Tower is a huge glass building with offices and a viewing area near the top."),
          special("It has a smooth, modern shape that seems to turn slightly as it rises. From the ground, it looks impressive without being too complicated."),
          special("The building is mainly used for offices, shops and tourism. We went to the viewing area and saw roads, smaller buildings and the river far below us."),
          common("What impressed me most was the mix of modern buildings and traditional streets."),
          special("I like this building because it represents the modern side of the city. I also enjoyed the wide view from the top, although the lift made my ears feel a little uncomfortable."),
          special("Overall, visiting it was one of the most memorable parts of my trip."),
        ],
      },
      {
        id: "shanghai-interesting-building",
        code: "S3",
        name: "见过的有趣建筑",
        question: "Describe an interesting building you have seen.",
        answer: [
          special("I'd like to talk about the Oriental Pearl Tower, which is one of the most interesting buildings I have seen."),
          common("Last autumn, I took a three-day trip to Shanghai with my girlfriend."),
          special("It stands in Lujiazui, close to the river and several other modern buildings."),
          common("The Oriental Pearl Tower has several large round sections, so it looks very unusual and easy to recognise."),
          special("The tower is used for sightseeing, broadcasting and entertainment. Visitors can go inside, enjoy the city view and learn a little about the history of Shanghai."),
          common("What impressed me most was the mix of modern buildings and traditional streets."),
          special("I found it interesting because its shape is completely different from an ordinary office building. It also looks especially colourful when the lights are turned on at night."),
          special("Seeing it in person made the trip feel much more special than simply looking at photos online."),
        ],
      },
      {
        id: "shanghai-mall",
        code: "S4",
        name: "喜欢的购物中心",
        question: "Describe a shopping mall you like.",
        answer: [
          special("I'd like to talk about a large shopping mall in Lujiazui that I visited during a trip to Shanghai."),
          common("Last autumn, I took a three-day trip to Shanghai with my girlfriend."),
          special("The mall was close to several famous buildings and was easy to reach by underground. It looked modern, bright and very clean."),
          special("There were many clothing shops, restaurants, cafés and a cinema. We mainly went there to have dinner after walking around the city for most of the day."),
          common("We also visited a large shopping mall in Lujiazui, where we had dinner and looked around the shops."),
          special("I liked the mall because it gave us a comfortable place to rest, and there were many types of food to choose from. The signs were also clear, so it was easy to find everything."),
          common("The trip was enjoyable because the city was convenient, lively and full of interesting places."),
          special("If I visit Shanghai again, I would happily return there for a meal."),
        ],
      },
    ],
    rules: [
      "城市题讲整段旅程；建筑题把旅行背景压缩成一两句，再详细描述建筑。",
      "购物中心题重点讲位置、外观、在那里做什么和喜欢的原因，不要大讲城市景点。",
      "整段经历使用过去时；建筑现在仍然存在的外观和用途可以使用现在时。",
    ],
  },
  {
    id: "gardening-grandma",
    tab: "素材 04｜种菜的奶奶",
    title: "通用素材 04：爱种菜的奶奶",
    tagline: "人物 + 种植物 + 家庭关爱",
    description: "用奶奶在自家菜园种菜、教我照料植物并把蔬菜送给家人的故事，塑造一位健康、勤劳又关爱家人的老人。",
    storyline: "介绍奶奶 → 她种的蔬菜 → 跟她学种菜 → 她把蔬菜送给家人 → 理解她种菜的原因",
    modules: [
      {
        label: "01 · 人物介绍",
        title: "健康而有活力的奶奶",
        detail: "我想讲讲我的奶奶，她大概就是你能想象到的最典型的中国奶奶。她现在年纪挺大了，但不知道为什么还是特别有活力。她走路比我快，吃得比我健康，说实话，有时候我觉得我才是家里真正的老人。",
        sentence: "I’d like to talk about my grandma, who is probably the most typical Chinese grandma you can imagine. She is quite old now, but somehow she is still full of energy. She walks faster than me, eats healthier than me, and honestly, sometimes I feel like I’m the real old person in the family.",
      },
      {
        label: "02 · 种植内容",
        title: "家后面的小菜园",
        detail: "她特别喜欢自己种蔬菜。她家后面有一个小菜园，里面种了西红柿、黄瓜、胡萝卜和大蒜。她总说超市里的食物不够新鲜，而她自己种的东西又有机又免费。你懂的，中国奶奶一听到这两个魔法词会有多激动。",
        sentence: "One thing she really enjoys is growing her own vegetables. Behind her house, she has a small garden where she grows tomatoes, cucumbers, carrots, and garlic. She always says food from the supermarket is not fresh enough, while the things she grows herself are organic and free. And you know how excited Chinese grandmas get when they hear those two magic words.",
      },
      {
        label: "03 · 一起种菜",
        title: "学习照料植物",
        detail: "有时候我去看她，她一大早就把我从床上拽起来，直接带到她的小菜园里帮她种菜。她会教我怎么松土、拔草、浇水。她还告诉我阳光特别重要，因为万物都需要阳光才能生长，人也一样。她说得好像很简单，但我干了十分钟就已经累得不行。结果她还是精力充沛，在菜园里走来走去，像那是她的私人健身房。",
        sentence: "Sometimes when I visit her, she drags me out of bed early in the morning and takes me straight into her little garden to help her grow vegetables. She teaches me how to loosen the soil, pull out weeds, and water the plants. She also tells me that sunlight is really important because everything needs sunlight to grow, and people are no different. She makes it sound easy, but after ten minutes, I’m already completely worn out. Meanwhile, she is still full of energy, moving around like the garden is her personal gym.",
      },
      {
        label: "04 · 对家人的爱",
        title: "把收获送给家人",
        detail: "每次我去看她，她都会给我一大袋蔬菜。她记得我喜欢吃什么，从来不会忘记我的生日，有一次甚至用自己菜园里的胡萝卜给我做了一个胡萝卜蛋糕。",
        sentence: "Every time I visit her, she gives me a huge bag of vegetables. She remembers what I like to eat, never forgets my birthday, and once even made me a carrot cake with carrots from her own garden.",
      },
      {
        label: "05 · 故事含义",
        title: "种菜是照顾家人的方式",
        detail: "我想这也是她如此喜欢种菜的原因。对她来说，种菜不只是为了有菜吃，更是她一种默默守护所爱之人的方式，即便不在我们身边，也盼着我们身体健康。",
        sentence: "I guess that’s also why she loves growing vegetables so much. For her, it’s not just about food. It’s her quiet way of taking care of the people she loves and making sure we are healthy, even when she is not right beside us.",
      },
    ],
    baseAnswer:
      "I’d like to talk about my grandma, who is probably the most typical Chinese grandma you can imagine. She is quite old now, but somehow she is still full of energy. She walks faster than me, eats healthier than me, and honestly, sometimes I feel like I’m the real old person in the family. One thing she really enjoys is growing her own vegetables. Behind her house, she has a small garden where she grows tomatoes, cucumbers, carrots, and garlic. She always says food from the supermarket is not fresh enough, while the things she grows herself are organic and free. And you know how excited Chinese grandmas get when they hear those two magic words. Sometimes when I visit her, she drags me out of bed early in the morning and takes me straight into her little garden to help her grow vegetables. She teaches me how to loosen the soil, pull out weeds, and water the plants. She also tells me that sunlight is really important because everything needs sunlight to grow, and people are no different. She makes it sound easy, but after ten minutes, I’m already completely worn out. Meanwhile, she is still full of energy, moving around like the garden is her personal gym. Every time I visit her, she gives me a huge bag of vegetables. She remembers what I like to eat, never forgets my birthday, and once even made me a carrot cake with carrots from her own garden. I guess that’s also why she loves growing vegetables so much. For her, it’s not just about food. It’s her quiet way of taking care of the people she loves and making sure we are healthy, even when she is not right beside us.",
    topics: [
      {
        id: "grandma-grow-plants",
        code: "G1",
        name: "喜欢种植物的人",
        question: "Describe a person who loves to grow plants at home or in a garden.",
        answer: [
          special("I'd like to talk about my grandma, who really loves growing vegetables."),
          common("Although she is quite old, she is still healthy and full of energy."),
          common("Behind her house, she has a small garden where she grows tomatoes, cucumbers, carrots and garlic."),
          special("She looks after the garden almost every morning. She waters the plants, pulls out weeds and checks whether they are growing well."),
          common("When I visit her, she teaches me how to loosen the soil, pull out weeds and water the plants."),
          common("After only ten minutes, I usually feel tired, but she is still moving around the garden with lots of energy."),
          special("She says gardening keeps her active and makes her feel calm. She also enjoys seeing a small seed slowly turn into food for the family."),
          common("Every time I visit her, she gives me a large bag of vegetables and reminds me to eat healthily."),
          common("For her, growing vegetables is not only a hobby. It is also a quiet way of caring for the people she loves."),
          special("That is why I admire her and enjoy spending time with her in the garden."),
        ],
      },
      {
        id: "grandma-energetic-person",
        code: "G2",
        name: "精力充沛的老人",
        question: "Describe an elderly person you know who has an interesting life.",
        answer: [
          special("I'd like to talk about my grandma, an elderly person whose active life really impresses me."),
          common("Although she is quite old, she is still healthy and full of energy."),
          special("She gets up early, cooks simple meals and spends a lot of time outdoors instead of sitting in front of a television."),
          common("Behind her house, she has a small garden where she grows tomatoes, cucumbers, carrots and garlic."),
          common("When I visit her, she teaches me how to loosen the soil, pull out weeds and water the plants."),
          common("After only ten minutes, I usually feel tired, but she is still moving around the garden with lots of energy."),
          special("She also enjoys talking to neighbours and sharing vegetables with them, so she knows almost everyone nearby."),
          common("Every time I visit her, she gives me a large bag of vegetables and reminds me to eat healthily."),
          special("I find her life interesting because it is simple but meaningful. She stays active, helps other people and enjoys what she does every day."),
        ],
      },
      {
        id: "grandma-learned-skill",
        code: "G3",
        name: "从长辈那里学到的技能",
        question: "Describe a useful skill you learned from an older person.",
        answer: [
          special("I'd like to talk about a useful gardening skill that I learned from my grandma."),
          common("Behind her house, she has a small garden where she grows tomatoes, cucumbers, carrots and garlic."),
          special("One weekend, I asked if I could help because I had never grown anything before."),
          common("She taught me how to loosen the soil, pull out weeds and water the plants."),
          special("She also explained that plants need enough sunlight and water, but too much water can be harmful."),
          common("After only ten minutes, I usually feel tired, but she is still moving around the garden with lots of energy."),
          special("At first, I found the work tiring and a little difficult. However, I became more interested when I saw the vegetables growing."),
          common("Every time I visit her, she gives me a large bag of vegetables and reminds me to eat healthily."),
          special("This skill is useful because it helps me understand where food comes from, and it gives me a relaxing activity away from my phone and computer."),
        ],
      },
      {
        id: "grandma-family-book",
        code: "G4",
        name: "对家庭重要的东西",
        question: "Describe something important that has been kept in your family for a long time.",
        answer: [
          special("I'd like to talk about an old storybook that has been kept in my family for many years."),
          common("It belongs to my grandma, who is still healthy, active and full of energy."),
          special("Her parents gave it to her when she was a child, so the book is more than sixty years old."),
          special("The cover is faded and some pages are yellow, but the pictures and words can still be seen clearly."),
          special("When I was young, my grandma often read stories from it to me after dinner."),
          common("She remembers what I like, never forgets my birthday and always finds a quiet way to care for me."),
          special("A few years ago, she gave the book to my parents and asked us to keep it safely."),
          special("It is important because it carries her childhood memories and also reminds me of the time we spent together."),
          common("For her, caring for the family is more important than the value of an object."),
          special("I hope we can pass this book on to the next generation."),
        ],
      },
      {
        id: "grandma-recent-story",
        code: "G5",
        name: "最近读过的故事",
        question: "Describe a story you have read recently.",
        answer: [
          special("I'd like to talk about a story I recently reread from an old book that belongs to my grandma."),
          special("It is about a small bird that is afraid to leave its nest."),
          special("One day, a storm damages the nest, so the bird has to fly for the first time and find a safer place."),
          special("I first heard this story from my grandma when I was a child, and I read it again last month when I visited her."),
          common("My grandma is quite old now, but she is still healthy and full of energy."),
          common("She always encourages me to be active and take care of myself."),
          special("I still like the story because it is simple, easy to understand and connected with my childhood."),
          special("It taught me that people often become stronger when they face a difficult situation instead of avoiding it."),
          common("The story also reminds me of my grandma's quiet way of caring for the people she loves."),
          special("That is why reading it again made me feel warm and a little emotional."),
        ],
      },
    ],
    rules: [
      "人物题先突出奶奶的性格和生活方式；植物题重点讲种什么、怎么种和为什么喜欢。",
      "技能题把奶奶压缩成引导者，详细讲自己学了哪些步骤以及学后的感受。",
      "奶奶现在仍然种菜的事实用现在时；某次跟她学习的经历用过去时。",
    ],
  },
  {
    id: "phone-detox",
    tab: "素材 05｜戒断手机瘾",
    title: "通用素材 05：减少手机使用",
    tagline: "近期改变 + 建议 + 克服困难",
    description: "用自己沉迷手机、向朋友 Sara 求助、阅读一本书并逐步改变习惯的故事，讲清问题、行动和结果。",
    storyline: "意识到手机成瘾 → 向 Sara 求助 → 阅读相关书籍 → 删除诱人应用并设置限制 → 注意力和生活状态改善",
    modules: [
      {
        label: "01 · 原来的问题",
        title: "过度依赖手机",
        detail: "有段时间我简直是在跟手机谈恋爱。每天早上睁眼先摸它，晚上闭眼前还得跟它道晚安。最糟的是，这一切根本不好玩，就像在吃数字垃圾食品，而且不仅没饱，反而更空虚。",
        sentence: "There was a time when I was basically dating my phone. It was the first thing I touched in the morning and the last thing I said goodnight to. And the worst part? It wasn’t even fun. It felt like eating digital junk food, and I wasn’t full. I just felt empty.",
      },
      {
        label: "02 · 寻求帮助",
        title: "请教朋友 Sara",
        detail: "后来我知道我需要做点事情改变了，于是我去找到我的朋友Sara——每次见到她，她几乎都不碰手机，好像生活在另一个宇宙。我问她是怎么做到的。她笑了笑说：“哦，我以前跟你一模一样。”然后她递给我一本书，叫《How to Break Up with Your Phone》（如何与手机分手），还说：“相信我，它真的改变了我的生活。”",
        sentence: "Eventually, I knew I had to do something. So I reached out to my friend Sara—every time I saw her, she barely touched her phone, like she was living in another universe. I asked her how she did it. She just laughed and said, ‘Oh, I used to be exactly like you.’ Then she handed me this book called How to Break Up with Your Phone and said, ‘Trust me, it changed my life.’",
      },
      {
        label: "03 · 一本有用的书",
        title: "理解上瘾的原因",
        detail: "这本书并不只是简单让我“把手机放下”——它让我明白了我为什么放不下手机，还教我该怎么做。它拆解了注意力上瘾背后的科学原理，还给了我一些可操作的小技巧，让手机变得不再那么诱人。",
        sentence: "The book didn’t just say ‘put your phone down’—it showed me exactly why I couldn’t, and what to do about it. It broke down the science of attention addiction and gave me doable tricks to make my phone less tempting.",
      },
      {
        label: "04 · 第一项改变",
        title: "让刷手机变得麻烦",
        detail: "读完那本书后，我立刻开始实践里面的建议。我做的第一件事就是“制造阻力”。我删掉了所有那些下意识就会打开的App——抖音、微信、Instagram。如果真的需要再用，我就再次下载安装。我也不再让手机陪我睡觉了。现在它被放在我够不到的地方，比如房间的另一头。",
        sentence: "After finishing the book, I started applying the tips right away. The first thing I did was create friction. I deleted all the apps I used to open on autopilot—TikTok, WeChat, Instagram. If I really needed them, I’d reinstall. I also stopped letting my phone sleep next to me. Now it stays somewhere out of reach—like across the room.",
      },
      {
        label: "05 · 第二项改变",
        title: "设置停止提示",
        detail: "我还学到一个技巧：给自己加一个“停止提示”。我意识到很多App的设计就是让你停不下来，比如抖音和Instagram，一个视频接着一个视频。所以我开始在手机里设置使用时间限制。时间一到，手机就会提醒我该停下来了，去做点别的事情。这个小小的中断，真的很有用，能帮我打断那种无限循环的刷屏行为。",
        sentence: "There was also another trick I learned from the book: adding stopping cues. I realized a lot of apps are designed to keep you scrolling forever—like TikTok or Instagram, where one video leads straight into the next. So I started setting screen time limits on my phone. When the time is up, it reminds me to stop and do something else. That little pause really helps me break the cycle.",
      },
      {
        label: "06 · 改变后的感受",
        title: "重新掌控生活",
        detail: "一个月下来，我真的感觉好多了。脑子安静了，注意力更集中。虽然我还是用手机，但它现在只是个工具，不再是控制我的东西。最棒的是，我终于有种“自己在生活”的感觉，而不是只隔着屏幕看别人过日子。",
        sentence: "After a month, I felt so much better. My mind was quieter, and I was more focused. I still use my phone, but now it feels more like a tool instead of something that controls me. The best part is that I finally feel like I'm living again, not just watching other people live through a screen.",
      },
    ],
    baseAnswer:
      "There was a time when I was basically dating my phone. It was the first thing I touched in the morning and the last thing I said goodnight to. And the worst part? It wasn’t even fun. It felt like eating digital junk food, and I wasn’t full. I just felt empty. Eventually, I knew I had to do something. So I reached out to my friend Sara—every time I saw her, she barely touched her phone, like she was living in another universe. I asked her how she did it. She just laughed and said, ‘Oh, I used to be exactly like you.’ Then she handed me this book called How to Break Up with Your Phone and said, ‘Trust me, it changed my life.’ The book didn’t just say ‘put your phone down’—it showed me exactly why I couldn’t, and what to do about it. It broke down the science of attention addiction and gave me doable tricks to make my phone less tempting. After finishing the book, I started applying the tips right away. The first thing I did was create friction. I deleted all the apps I used to open on autopilot—TikTok, WeChat, Instagram. If I really needed them, I’d reinstall. I also stopped letting my phone sleep next to me. Now it stays somewhere out of reach—like across the room. There was also another trick I learned from the book: adding stopping cues. I realized a lot of apps are designed to keep you scrolling forever—like TikTok or Instagram, where one video leads straight into the next. So I started setting screen time limits on my phone. When the time is up, it reminds me to stop and do something else. That little pause really helps me break the cycle. After a month, I felt so much better. My mind was quieter, and I was more focused. I still use my phone, but now it feels more like a tool instead of something that controls me. The best part is that I finally feel like I'm living again, not just watching other people live through a screen.",
    topics: [
      {
        id: "phone-recent-change",
        code: "P1",
        name: "近期做出的改变",
        question: "Describe a recent change you made in your life.",
        answer: [
          special("I'd like to talk about a recent change I made to reduce the amount of time I spend on my phone."),
          common("There was a time when my phone was the first thing I checked in the morning and the last thing I used at night."),
          special("I often watched short videos for hours, but afterwards I felt tired and empty."),
          common("I asked my friend Sara for advice because she rarely used her phone when we spent time together."),
          common("She recommended a book that explained why phones are so tempting and gave me several practical tips."),
          common("I deleted the apps I opened without thinking and kept my phone away from my bed at night."),
          common("I also set screen-time limits, so my phone reminded me to stop and do something else."),
          special("The first week was difficult because checking my phone had become a habit. However, I slowly learned to read, exercise or talk to people instead."),
          common("After a month, I felt calmer and more focused. My phone became a useful tool instead of something that controlled me."),
          special("This change was small, but it improved both my work and my daily life."),
        ],
      },
      {
        id: "phone-helped-problem",
        code: "P2",
        name: "别人帮助解决问题",
        question: "Describe a time when someone helped you solve a problem.",
        answer: [
          special("I'd like to talk about a time when my friend Sara helped me deal with my phone addiction."),
          common("There was a time when my phone was the first thing I checked in the morning and the last thing I used at night."),
          special("I knew the habit was affecting my sleep and concentration, but I did not know how to change it."),
          common("I asked my friend Sara for advice because she rarely used her phone when we spent time together."),
          special("She listened patiently and told me that she had experienced the same problem before, so I did not feel embarrassed."),
          common("She recommended a book that explained why phones are so tempting and gave me several practical tips."),
          common("I deleted the apps I opened without thinking and kept my phone away from my bed at night."),
          common("I also set screen-time limits, so my phone reminded me to stop and do something else."),
          common("After a month, I felt calmer and more focused. My phone became a useful tool instead of something that controlled me."),
          special("I was grateful to Sara because her advice was simple, practical and based on her own experience."),
        ],
      },
      {
        id: "phone-overcame-difficulty",
        code: "P3",
        name: "克服困难并取得成功",
        question: "Describe a difficult thing you did and succeeded in doing.",
        answer: [
          special("I'd like to talk about how I successfully reduced my phone use, which was more difficult than I expected."),
          common("There was a time when my phone was the first thing I checked in the morning and the last thing I used at night."),
          special("The habit affected my sleep and made it harder for me to focus at work."),
          common("I asked my friend Sara for advice because she rarely used her phone when we spent time together."),
          common("She recommended a book that explained why phones are so tempting and gave me several practical tips."),
          common("I deleted the apps I opened without thinking and kept my phone away from my bed at night."),
          common("I also set screen-time limits, so my phone reminded me to stop and do something else."),
          special("At first, I kept reaching for my phone without thinking, and I nearly gave up several times. I continued because I wanted better sleep and more control over my time."),
          common("After a month, I felt calmer and more focused. My phone became a useful tool instead of something that controlled me."),
          special("I felt proud because I had changed a habit that once seemed impossible to control."),
        ],
      },
      {
        id: "phone-advice",
        code: "P4",
        name: "给别人的建议",
        question: "Describe a time when you gave someone useful advice.",
        answer: [
          special("I'd like to talk about some useful advice I gave a colleague who was spending too much time on his phone."),
          common("There was a time when my phone was the first thing I checked in the morning and the last thing I used at night."),
          special("Because I had experienced the same problem, I understood why it was difficult for him to stop."),
          common("I told him about a book that explained why phones are so tempting and gave several practical tips."),
          common("I suggested deleting the apps he opened without thinking and keeping his phone away from his bed at night."),
          common("I also suggested setting screen-time limits, so his phone could remind him to stop and do something else."),
          special("I did not tell him to stop using his phone completely. I explained that small changes were easier to follow."),
          special("A few weeks later, he told me that he was sleeping better and wasting less time online."),
          common("My phone became a useful tool instead of something that controlled me."),
          special("I felt happy that my own experience could help another person."),
        ],
      },
      {
        id: "phone-self-study-friend",
        code: "P5",
        name: "自学的朋友",
        question: "Describe one of your friends who learned something without a teacher.",
        answer: [
          special("I'd like to talk about my friend Sara, who taught herself how to control her phone use."),
          common("She once had the same problem as me and spent too much time looking at her phone."),
          special("She decided to change because the habit was affecting her sleep and concentration."),
          common("She read a book called How to Break Up with Your Phone, which explained why phones are so tempting."),
          common("The book also gave her practical tips, such as deleting unnecessary apps and keeping the phone away from the bed."),
          special("She tried the methods by herself and slowly found out which ones worked best for her."),
          common("She also set screen-time limits, so her phone reminded her to stop and do something else."),
          special("After about a month, she became calmer and more focused."),
          special("A teacher might have given her a clearer plan, but I think self-study was suitable because she could change her habits at her own speed."),
          special("I admire her because she solved a personal problem through reading and practice."),
        ],
      },
      {
        id: "phone-encourage-other",
        code: "P6",
        name: "鼓励别人做不愿做的事",
        question: "Describe a time when you encouraged someone to do something that he or she didn't want to do.",
        answer: [
          special("I'd like to talk about a time when I encouraged a colleague to reduce his phone use."),
          special("He often watched short videos late at night and felt tired at work, but he did not want to delete the apps."),
          common("Because I had experienced the same problem, I understood why it was difficult for him to stop."),
          common("I told him about a book that explained why phones are so tempting and gave several practical tips."),
          special("I encouraged him to try the change for only one week instead of giving up his phone completely."),
          common("I suggested keeping the phone away from his bed and setting a screen-time limit."),
          special("At first, he complained that it was inconvenient, but he finally agreed to try."),
          special("A week later, he said that he was sleeping earlier and felt more energetic in the morning."),
          special("I encouraged him because his tiredness was affecting both his health and his work."),
          special("I felt pleased that a small suggestion made a real difference."),
        ],
      },
      {
        id: "phone-screen-time-app",
        code: "P7",
        name: "App／程序",
        question: "Describe a program or app on your computer or phone.",
        answer: [
          special("I'd like to talk about Screen Time, a useful function on my phone."),
          special("I found it in my phone settings after reading a book about reducing phone use."),
          common("The book explained why many apps are designed to keep people scrolling for a long time."),
          special("I use Screen Time to check how long I spend on different apps each day."),
          common("I also set daily limits, so my phone reminds me to stop when the time is up."),
          special("For example, I allow myself about thirty minutes for short-video apps."),
          special("The function is simple because I only need to choose an app and set a time limit."),
          common("That little pause helps me break the cycle and do something else."),
          common("After using it for a month, I felt calmer and more focused."),
          special("I like this function because it helps me control my habits without completely giving up my phone."),
        ],
      },
      {
        id: "phone-not-allowed",
        code: "P8",
        name: "禁用手机的场合",
        question: "Describe an occasion when you were not allowed to use your mobile phone.",
        answer: [
          special("I'd like to talk about an important company meeting when I was not allowed to use my mobile phone."),
          special("It happened about six months ago in a meeting room at my office."),
          special("Our team was discussing a new project, and some of the information was private."),
          special("Before the meeting started, the manager asked everyone to put their phones on silent and keep them inside their bags."),
          special("We were not allowed to check messages or take photos during the meeting."),
          common("At that time, I was trying to reduce my phone use, so the rule was also useful for me."),
          special("At first, I felt a little uncomfortable because I usually checked work messages quite often."),
          special("However, I soon noticed that I could follow the discussion more carefully without my phone."),
          common("My mind felt quieter, and I was more focused."),
          special("In the end, I understood the rule and thought it made the meeting more efficient."),
        ],
      },
    ],
    rules: [
      "近期改变题突出改变前后；求助题突出 Sara 做了什么；困难题突出自己坚持的过程。",
      "建议题把 Sara 的建议改成自己给别人的建议，并交代对方采用后的结果。",
      "讲过去的习惯和行动用过去时；描述现在的状态与收获用现在时。",
    ],
  },
  {
    id: "movie-night",
    tab: "素材 06｜家庭电影之夜",
    title: "通用素材 06：和女朋友在家看电影",
    tagline: "家中放松 + 近期观影 + 失望电影",
    description: "固定使用周末在客厅与女朋友看电影的背景，只根据题目替换电影内容和评价。",
    storyline: "周末在家 → 舒适的客厅 → 和女朋友看电影 → 喜欢或失望的观影经历 → 工作后得到放松",
    modules: [
      {
        label: "01 · 地点",
        title: "家里的客厅",
        detail: "客厅有一张舒服的沙发、一台电视和柔和的灯光。",
        sentence: "My favourite place to relax at home is the living room. It has a comfortable sofa, a television and soft lighting.",
      },
      {
        label: "02 · 日常活动",
        title: "周末一起看电影",
        detail: "通常周末晚上和女朋友坐在沙发上看电影。",
        sentence: "At weekends, my girlfriend and I often sit on the sofa and watch a movie together.",
      },
      {
        label: "03 · 简单准备",
        title: "零食和饮料",
        detail: "看电影前会准备一些零食和饮料，让晚上更轻松。",
        sentence: "We usually prepare some snacks and drinks before the movie starts.",
      },
      {
        label: "04 · 喜欢的类型",
        title: "喜剧和美国电影",
        detail: "两个人都喜欢美国电影，尤其是轻松有趣的喜剧。",
        sentence: "We both enjoy American movies, especially comedies that are simple and funny.",
      },
      {
        label: "05 · 放松作用",
        title: "忘记工作压力",
        detail: "看电影不需要出门，可以暂时忘记工作并一起聊天。",
        sentence: "Watching a movie at home helps me forget about work and spend some relaxing time with my girlfriend.",
      },
      {
        label: "06 · 总体感受",
        title: "简单但享受",
        detail: "这不是特别的活动，却是忙碌一周后最喜欢的放松方式。",
        sentence: "It is a simple activity, but it is one of my favourite ways to relax after a busy week.",
      },
    ],
    baseAnswer:
      "My favourite place to relax at home is the living room. It has a comfortable sofa, a television and soft lighting. At weekends, my girlfriend and I often sit on the sofa and watch a movie together. We usually prepare some snacks and drinks before the movie starts. We both enjoy American movies, especially comedies that are simple and funny. Sometimes we talk about the story or the actors after the movie. I like watching movies at home because it is more comfortable and less expensive than going to a cinema. I can also pause the movie if I need a break. Watching a movie at home helps me forget about work and spend some relaxing time with my girlfriend. It is a simple activity, but it is one of my favourite ways to relax after a busy week.",
    topics: [
      {
        id: "movie-relaxing-place",
        code: "M1",
        name: "家里放松的地方",
        question: "Describe your favorite place in your house where you can relax.",
        answer: [
          special("I'd like to talk about my living room, which is my favourite place to relax at home."),
          common("It has a comfortable sofa, a television and soft lighting."),
          special("It is not very large, but it is clean, quiet and comfortable."),
          common("At weekends, my girlfriend and I often sit on the sofa and watch a movie together."),
          common("We usually prepare some snacks and drinks before the movie starts."),
          common("We both enjoy American movies, especially comedies that are simple and funny."),
          special("When I am alone, I sometimes listen to music or play computer games there."),
          common("Watching a movie at home helps me forget about work and spend some relaxing time with my girlfriend."),
          special("I feel relaxed there because I do not need to think about work or deal with other people."),
          common("It is a simple place, but it is one of my favourite ways to relax after a busy week."),
        ],
      },
      {
        id: "movie-recent-enjoyed",
        code: "M2",
        name: "近期观影",
        question: "Describe a movie you watched and enjoyed recently.",
        answer: [
          special("I'd like to talk about a comedy called The Intern, which I watched again last weekend."),
          common("My girlfriend and I watched it at home in our living room."),
          common("We sat on the sofa and prepared some snacks and drinks before the movie started."),
          special("The film is about an older man who becomes an intern at an online company."),
          special("At first, some younger workers do not understand him, but they slowly respect his experience and kindness."),
          common("We both enjoy American movies, especially comedies that are simple and funny."),
          special("I enjoyed this movie because it was warm, easy to understand and related to working life."),
          special("It also showed that people of different ages can learn from each other."),
          common("Watching a movie at home helped me forget about work and spend relaxing time with my girlfriend."),
          special("After the film, we talked about our favourite characters, so the evening was enjoyable."),
        ],
      },
      {
        id: "movie-disappointed",
        code: "M3",
        name: "让你失望的电影",
        question: "Describe a movie you watched recently that you felt disappointed about.",
        answer: [
          special("I'd like to talk about an action movie I watched at home about a month ago."),
          common("My girlfriend and I watched it in our living room on a Saturday evening."),
          common("We prepared some snacks and drinks because we expected an enjoyable movie night."),
          special("I decided to watch it because the trailer looked exciting and several famous actors were in it."),
          special("However, the story was difficult to follow and many scenes felt almost the same."),
          special("The movie also lasted for more than two hours, so I became tired before it ended."),
          special("My girlfriend and I usually enjoy American movies, but neither of us liked this one."),
          special("I felt disappointed because the trailer made the film look much better than it really was."),
          common("Watching movies at home is normally one of my favourite ways to relax after a busy week."),
          special("This time, however, we stopped the movie early and watched a comedy instead."),
        ],
      },
    ],
    rules: [
      "地点题重点描述客厅和放松原因；电影题只用两句交代客厅背景。",
      "喜欢与失望的电影使用同一观影习惯，但必须更换影片内容和评价。",
      "描述房间和习惯用现在时；讲某次观影经历用过去时。",
    ],
  },
  {
    id: "singer-event",
    tab: "素材 07｜喜欢的歌手与音乐活动",
    title: "通用素材 07：喜欢周杰伦，但不喜欢一次现场活动",
    tagline: "想见的名人 + 不喜欢的音乐活动",
    description: "固定使用从学生时代喜欢周杰伦的背景；名人题突出欣赏，活动题突出现场体验不佳，两者并不冲突。",
    storyline: "学生时代听歌 → 欣赏周杰伦 → 参加一次播放其歌曲的活动 → 现场拥挤且音响太大 → 仍希望有机会见面",
    modules: [
      {
        label: "01 · 人物",
        title: "喜欢的歌手周杰伦",
        detail: "从中学时代开始听他的歌，他是中国非常有名的歌手和音乐创作者。",
        sentence: "The famous person I would like to meet is Jay Chou, a well-known Chinese singer and songwriter.",
      },
      {
        label: "02 · 如何了解",
        title: "学生时代开始听歌",
        detail: "朋友推荐了一首歌，后来逐渐听了更多作品。",
        sentence: "I first heard his music when I was in secondary school, after a friend recommended one of his songs to me.",
      },
      {
        label: "03 · 喜欢原因",
        title: "歌曲有特色",
        detail: "他的音乐结合流行和传统元素，很多歌曲也带来学生时代的回忆。",
        sentence: "I like his music because it has a special style and reminds me of my school days.",
      },
      {
        label: "04 · 音乐活动",
        title: "商场举办的现场活动",
        detail: "和朋友参加一场音乐活动，希望听到熟悉的歌曲。",
        sentence: "Last year, I went to a live music event at a shopping mall with a close friend.",
      },
      {
        label: "05 · 不喜欢原因",
        title: "拥挤且声音太大",
        detail: "现场人太多，音响太响，歌曲还被改得难以辨认。",
        sentence: "The place was crowded, the speakers were too loud, and some familiar songs sounded completely different.",
      },
      {
        label: "06 · 最终态度",
        title: "区分歌手和现场体验",
        detail: "不喜欢那次活动，但依然欣赏歌手并希望将来见到他。",
        sentence: "I did not enjoy that particular event, but I still like his music and would be happy to meet him one day.",
      },
    ],
    baseAnswer:
      "The famous person I would like to meet is Jay Chou, a well-known Chinese singer and songwriter. I first heard his music when I was in secondary school, after a friend recommended one of his songs to me. Since then, I have listened to many of his albums. I like his music because it has a special style and reminds me of my school days. Last year, I went to a live music event at a shopping mall with a close friend. We decided to go because the event included several of his popular songs. Unfortunately, the place was crowded, the speakers were too loud, and some familiar songs sounded completely different. We left earlier than planned because we both felt tired. I did not enjoy that particular event, but I still like Jay Chou's music. If I could meet him, I would like to ask how he creates his songs and tell him that his music is connected with many of my memories.",
    topics: [
      {
        id: "singer-famous-person",
        code: "J1",
        name: "想见的名人",
        question: "Describe a famous person you would like to meet.",
        answer: [
          special("The famous person I would like to meet is Jay Chou, a well-known Chinese singer and songwriter."),
          common("I first heard his music when I was in secondary school, after a friend recommended one of his songs to me."),
          special("I later watched his music videos and interviews online, so I gradually learned more about him."),
          common("I like his music because it has a special style and reminds me of my school days."),
          special("Some of his songs combine modern pop music with traditional Chinese sounds."),
          special("I would like to meet him after a small concert or at a music event, because that would feel more natural than meeting him in a crowded public place."),
          special("I would ask him how he gets ideas for his songs and how he has continued working for so many years."),
          special("I would also tell him that his music helped me relax when I was a student."),
          common("Although I once had a disappointing experience at a music event, I still enjoy his songs."),
          special("Meeting him would be memorable because his music is connected with an important part of my life."),
        ],
      },
      {
        id: "singer-bad-event",
        code: "J2",
        name: "不喜欢的音乐活动",
        question: "Describe an event you attended in which you didn't enjoy the music played.",
        answer: [
          special("I'd like to talk about a live music event at a shopping mall that I did not enjoy."),
          common("I went there with a close friend last year."),
          special("We decided to attend because the event was free and the performers planned to play several songs by Jay Chou."),
          common("I have liked his music since secondary school, so I expected the event to be enjoyable."),
          common("However, the place was crowded and the speakers were much too loud."),
          special("The performers changed the songs a lot, and some of them were difficult to recognise."),
          special("People around us were also talking and recording videos, so it was hard to focus on the music."),
          special("After about forty minutes, my friend and I both had headaches and decided to leave."),
          special("I felt disappointed because I liked the original songs but did not enjoy the way they were performed."),
          common("I did not enjoy that particular event, but I still like Jay Chou's music."),
        ],
      },
    ],
    rules: [
      "名人题主要讲人物、了解渠道、见面方式和想见原因，不要展开失败活动。",
      "音乐活动题主要讲时间、同行者、参加原因和不喜欢的原因，歌手背景只占两句。",
      "不喜欢一次现场表演不等于不喜欢歌手，结尾要明确区分。",
    ],
  },
];
