import type {
  AdditionalAnswerLine,
  AdditionalMaterial,
} from "./additional-materials";

const common = (text: string): AdditionalAnswerLine => ({ kind: "通用", text });
const special = (text: string): AdditionalAnswerLine => ({ kind: "特殊", text });

export const remainingMaterials: AdditionalMaterial[] = [
  {
    id: "interview-advice",
    tab: "素材 08｜面试建议",
    title: "通用素材 08：鼓励朋友参加工作面试",
    tagline: "鼓励别人 + 提供有用建议",
    description: "使用同一次求职经历：朋友因缺乏信心不想参加面试，你鼓励他并帮助他准备。",
    storyline: "朋友收到面试邀请 → 担心失败 → 鼓励尝试 → 模拟面试并给建议 → 顺利参加 → 获得工作 → 开心和自豪",
    modules: [
      {
        label: "01 · 人物背景",
        title: "正在找工作的朋友 Kevin",
        detail: "Kevin 是一位大学朋友，去年希望找到一份更好的工作。",
        sentence: "Kevin is a university friend of mine, and last year he was looking for a better job.",
      },
      {
        label: "02 · 遇到困难",
        title: "收到邀请却不敢参加",
        detail: "他觉得经验不足，也担心回答不好，所以想放弃面试。",
        sentence: "He received an interview invitation, but he wanted to turn it down because he was not confident.",
      },
      {
        label: "03 · 鼓励行动",
        title: "先尝试，不要害怕失败",
        detail: "告诉他即使没有得到工作，面试本身也能带来经验。",
        sentence: "I encouraged him to attend because even an unsuccessful interview would give him useful experience.",
      },
      {
        label: "04 · 实用建议",
        title: "准备例子并模拟练习",
        detail: "建议他准备项目案例、练习自我介绍，并提前了解公司。",
        sentence: "I advised him to prepare two clear examples of his work and practise answering common questions.",
      },
      {
        label: "05 · 最终结果",
        title: "顺利完成并得到工作",
        detail: "练习后更有信心，参加面试并在一周后收到录用通知。",
        sentence: "He attended the interview and received a job offer about a week later.",
      },
      {
        label: "06 · 个人感受",
        title: "为朋友感到高兴",
        detail: "建议真正帮助了朋友，也更相信鼓励的重要性。",
        sentence: "I felt happy and proud because a little encouragement helped him take an important step.",
      },
    ],
    baseAnswer:
      "I'd like to talk about my university friend Kevin. Last year, he was looking for a better job and received an interview invitation from a company he liked. However, he wanted to turn it down because he was not confident and thought he did not have enough experience. I encouraged him to attend because even an unsuccessful interview would give him useful experience. I also advised him to prepare two clear examples of his work, practise a short self-introduction and learn some basic information about the company. We did a practice interview online, and I helped him make his answers shorter and clearer. In the end, he attended the interview and received a job offer about a week later. I felt happy and proud because a little encouragement helped him take an important step.",
    topics: [
      {
        id: "interview-encouraged",
        code: "I1",
        name: "鼓励别人做不愿意做的事",
        question: "Describe a time when you encouraged someone to do something they didn't want to do.",
        answer: [
          special("I'd like to talk about a time when I encouraged my friend Kevin to attend a job interview."),
          common("Kevin is a university friend of mine, and last year he was looking for a better job."),
          common("He received an interview invitation, but he wanted to turn it down because he was not confident."),
          special("He was worried that the interviewers would ask difficult questions and discover that he did not have enough experience."),
          common("I encouraged him to attend because even an unsuccessful interview would give him useful experience."),
          special("I reminded him that the company had already read his CV, so they clearly thought he had something useful to offer."),
          common("I advised him to prepare two clear examples of his work and practise answering common questions."),
          special("We also did a short practice interview online, which made him feel calmer."),
          common("He attended the interview and received a job offer about a week later."),
          common("I felt happy and proud because a little encouragement helped him take an important step."),
        ],
      },
      {
        id: "interview-advice",
        code: "I2",
        name: "给别人有用的建议",
        question: "Describe a time when you gave someone useful advice.",
        answer: [
          special("I'd like to talk about some useful advice I gave my university friend Kevin."),
          common("Kevin is a university friend of mine, and last year he was looking for a better job."),
          common("He received an interview invitation, but he wanted to turn it down because he was not confident."),
          special("He asked me how he could prepare because I had attended several technical interviews before."),
          common("I advised him to prepare two clear examples of his work and practise answering common questions."),
          special("I also suggested researching the company and preparing one or two questions for the interviewers. Most importantly, I told him to answer slowly instead of trying to sound too clever."),
          common("I encouraged him to attend because even an unsuccessful interview would give him useful experience."),
          special("We practised online for about an hour, and his answers became much clearer."),
          common("He attended the interview and received a job offer about a week later."),
          common("I felt happy and proud because a little encouragement helped him take an important step."),
        ],
      },
    ],
    rules: [
      "鼓励题重点讲对方为什么不愿意以及你如何改变他的想法；建议题重点讲建议的具体内容。",
      "同一结果可以复用，但不要把两道题说成完全相同的答案。",
      "故事使用过去时；总结鼓励和建议的价值时可以使用现在时。",
    ],
  },
  {
    id: "music-event",
    tab: "素材 09｜音乐活动",
    title: "通用素材 09：一次体验不好的音乐演出",
    tagline: "不喜欢的音乐活动 + 不允许使用手机",
    description: "固定一次室内录制演出：入场时手机被放入锁袋，现场拥挤且等待很久。",
    storyline: "去年夏天和女朋友去演出 → 入场收起手机 → 等待一小时 → 场地拥挤闷热 → 音响太大 → 提前离开 → 失望",
    modules: [
      {
        label: "01 · 时间人物",
        title: "去年夏天的室内演出",
        detail: "与女朋友一起去市中心观看一场现场录制的音乐节目。",
        sentence: "Last summer, I went to an indoor music event in the city centre with my girlfriend.",
      },
      {
        label: "02 · 手机规定",
        title: "手机必须放入锁袋",
        detail: "主办方不允许录音录像，也不希望屏幕影响节目拍摄。",
        sentence: "At the entrance, everyone had to put their phone into a locked pouch until the event ended.",
      },
      {
        label: "03 · 等待问题",
        title: "节目迟到近一小时",
        detail: "没有清楚说明原因，人群只能站着等待。",
        sentence: "The show started almost an hour late, and nobody clearly explained the reason.",
      },
      {
        label: "04 · 现场环境",
        title: "拥挤、闷热且声音太大",
        detail: "座位空间小，空气不好，音乐声让人不舒服。",
        sentence: "The hall was crowded and hot, and the music was much louder than I expected.",
      },
      {
        label: "05 · 最终行动",
        title: "演出结束后立刻离开",
        detail: "没有拍照，也不能联系朋友，结束后只想回家休息。",
        sentence: "When the event finally ended, we collected our phones and went home immediately.",
      },
      {
        label: "06 · 感受",
        title: "从期待到失望",
        detail: "音乐本身不差，但整体组织方式影响了体验。",
        sentence: "I felt disappointed because the poor organisation made it difficult to enjoy the music.",
      },
    ],
    baseAnswer:
      "I'd like to talk about an indoor music event I attended with my girlfriend last summer. It was held in the city centre and was being recorded for an online programme. At the entrance, everyone had to put their phone into a locked pouch because recording was not allowed. The rule was understandable, but it became inconvenient when the show started almost an hour late and nobody explained the reason. The hall was crowded and hot, and the music was much louder than I expected. We could not check the time, contact anyone or take a photo during the event. When it finally ended, we collected our phones and went home immediately. I felt disappointed because the poor organisation made it difficult to enjoy the music, even though some of the singers were quite good.",
    topics: [
      {
        id: "music-not-enjoyed",
        code: "M1",
        name: "不喜欢的音乐活动",
        question: "Describe a music event you did not enjoy.",
        answer: [
          special("I'd like to talk about a music event that I did not enjoy very much."),
          common("Last summer, I went to an indoor music event in the city centre with my girlfriend."),
          special("We had bought the tickets several weeks earlier, so we were looking forward to spending an enjoyable evening together."),
          common("At the entrance, everyone had to put their phone into a locked pouch until the event ended."),
          common("The show started almost an hour late, and nobody clearly explained the reason."),
          common("The hall was crowded and hot, and the music was much louder than I expected."),
          special("Some singers performed well, but it was hard to concentrate because we had already become tired and uncomfortable."),
          common("When the event finally ended, we collected our phones and went home immediately."),
          common("I felt disappointed because the poor organisation made it difficult to enjoy the music."),
          special("Since then, I have checked reviews and event rules more carefully before buying tickets."),
        ],
      },
      {
        id: "music-no-phone",
        code: "M2",
        name: "不允许使用手机的经历",
        question: "Describe an occasion when you were not allowed to use your phone.",
        answer: [
          special("I'd like to talk about an occasion when I was not allowed to use my phone at a music event."),
          common("Last summer, I went to an indoor music event in the city centre with my girlfriend."),
          common("At the entrance, everyone had to put their phone into a locked pouch until the event ended."),
          special("The event was being recorded, so the organisers wanted to prevent people from filming the singers or distracting others with bright screens."),
          special("At first, I thought the rule was reasonable and expected the show to begin soon."),
          common("The show started almost an hour late, and nobody clearly explained the reason."),
          special("Without my phone, I could not check the time or tell a friend that we would be late afterwards. That made the waiting feel even longer."),
          common("When the event finally ended, we collected our phones and went home immediately."),
          special("I understood the reason for the rule, but I still felt frustrated because the event was badly organised."),
        ],
      },
    ],
    rules: [
      "音乐活动题重点讲为什么不喜欢；手机题重点讲禁用原因、不能使用时发生了什么和个人感受。",
      "手机规定可以理解，但活动组织不好；这种平衡表达比单纯抱怨更自然。",
      "具体经历统一使用过去时，不要在故事中突然切换成现在时。",
    ],
  },
  {
    id: "drawing-child",
    tab: "素材 10｜画画的小孩",
    title: "通用素材 10：喜欢画画并获奖的外甥女",
    tagline: "喜欢画画的孩子 + 为家庭成员感到骄傲 + 发挥想象力",
    description: "固定八岁的外甥女 Lily：喜欢画动物和公园；你帮助她构思环保主题，她独立完成作品并在学校比赛中获奖。",
    storyline: "八岁外甥女 Lily → 喜欢画画 → 参加环保比赛 → 一起构思未来公园 → 她独立完成作品 → 获奖 → 为她骄傲",
    modules: [
      {
        label: "01 · 人物身份",
        title: "八岁的外甥女 Lily",
        detail: "Lily 活泼、好奇，从很小的时候就喜欢画画。",
        sentence: "Lily is my eight-year-old niece, and she has enjoyed drawing since she was very young.",
      },
      {
        label: "02 · 喜欢内容",
        title: "动物、公园和家人",
        detail: "最常画猫、狗、树木和家庭活动，画面颜色明亮。",
        sentence: "She usually draws animals, parks and simple pictures of our family.",
      },
      {
        label: "03 · 画画地点",
        title: "家中书桌和学校美术课",
        detail: "周末在书桌画，也喜欢学校的美术课程。",
        sentence: "She often draws at a small desk in her bedroom and during art lessons at school.",
      },
      {
        label: "04 · 比赛经历",
        title: "参加学校环保绘画比赛",
        detail: "画了一座干净的公园，里面有人种树、捡垃圾。",
        sentence: "Last term, she entered a school art competition with a picture of a clean green park.",
      },
      {
        label: "05 · 想象构思",
        title: "一起想象未来的环保公园",
        detail: "她不知道如何开始时，你想象了干净的湖、更多树木和保护自然的孩子。",
        sentence: "When she asked me for ideas, I imagined a future park with a clean lake, more trees and children protecting nature.",
      },
      {
        label: "06 · 结果",
        title: "获得一等奖",
        detail: "认真修改了几次，作品最终获得学校比赛一等奖。",
        sentence: "Her picture won first prize, and it was displayed near the entrance of her school.",
      },
      {
        label: "07 · 感受",
        title: "为努力和耐心感到骄傲",
        detail: "骄傲的不只是结果，更是她没有放弃并完成了作品。",
        sentence: "I felt proud because she worked patiently and did not give up when the picture was difficult.",
      },
    ],
    baseAnswer:
      "I'd like to talk about my eight-year-old niece Lily, who has enjoyed drawing since she was very young. She usually draws animals, parks and simple pictures of our family. Last term, she entered a school competition but did not know how to begin. When she asked me for ideas, I imagined a future park with a clean lake, more trees and children protecting nature. We discussed the idea, but she chose the colours and completed the picture herself. She changed several parts before she was satisfied with it. In the end, it won first prize and was displayed near the entrance of her school. I felt proud because she worked patiently and did not give up. I also enjoyed using my imagination to help her turn a simple theme into a clear picture.",
    topics: [
      {
        id: "drawing-child-topic",
        code: "D1",
        name: "喜欢画画的孩子",
        question: "Describe a child who likes drawing.",
        answer: [
          special("I'd like to talk about a child in my family who really likes drawing."),
          common("Lily is my eight-year-old niece, and she has enjoyed drawing since she was very young."),
          common("She usually draws animals, parks and simple pictures of our family."),
          special("Her favourite subjects are cats and dogs because she thinks their faces can show many different feelings."),
          common("She often draws at a small desk in her bedroom and during art lessons at school."),
          special("At weekends, she sometimes spends more than an hour adding colours and small details to one picture. She often shows it to the whole family afterwards."),
          common("Last term, she entered a school art competition with a picture of a clean green park."),
          common("Her picture won first prize, and it was displayed near the entrance of her school."),
          special("I enjoy looking at her drawings because they are cheerful and imaginative."),
          common("I felt proud because she worked patiently and did not give up when the picture was difficult."),
        ],
      },
      {
        id: "drawing-proud-family",
        code: "D2",
        name: "为家庭成员感到骄傲",
        question: "Describe a time when you felt proud of a family member.",
        answer: [
          special("I'd like to talk about a time when I felt proud of my niece Lily."),
          common("Lily is my eight-year-old niece, and she has enjoyed drawing since she was very young."),
          common("Last term, she entered a school art competition with a picture of a clean green park."),
          special("The picture showed children planting trees and cleaning up rubbish. She worked on it for several days and changed the colours more than once."),
          special("At one point, she thought the picture was not good enough and wanted to stop. Her parents encouraged her to finish it and submit it."),
          common("Her picture won first prize, and it was displayed near the entrance of her school."),
          special("When she told us the news, she was smiling and could hardly stop talking about it. Our family had a small dinner to celebrate."),
          common("I felt proud because she worked patiently and did not give up when the picture was difficult."),
          special("The experience showed me that even a young child can achieve something through steady effort."),
        ],
      },
      {
        id: "drawing-imagination",
        code: "D3",
        name: "发挥想象力",
        question: "Describe a time when you used your imagination.",
        answer: [
          special("I'd like to talk about helping my niece with an art competition by using my imagination."),
          common("Lily is my eight-year-old niece, and she has enjoyed drawing since she was very young."),
          common("Last term, she entered a school art competition with a picture of a clean green park."),
          special("She knew the theme was protecting the environment, but she did not know how to begin."),
          common("When she asked me for ideas, I imagined a future park with a clean lake, more trees and children protecting nature."),
          special("I suggested a clean lake, trees and children collecting rubbish, and helped her arrange them on the page."),
          special("We needed imagination because there was no real place to copy."),
          special("Lily chose the colours and completed the artwork herself, so it was still her own work."),
          common("Her picture won first prize, and it was displayed near the entrance of her school."),
          special("I felt excited that my idea was useful and proud that she turned it into a clear picture."),
        ],
      },
    ],
    rules: [
      "孩子题重点讲她画什么、在哪里画；骄傲题重点讲比赛过程；想象力题重点讲你怎样构思画面以及为什么需要想象。",
      "不要只说获得一等奖，要说明她反复修改和没有放弃，故事才完整。",
      "想象力题必须说明你只提供构思，Lily 自己完成作品，避免与为她骄傲的故事冲突。",
      "孩子现在的兴趣使用现在时；比赛和获奖经历使用过去时。",
    ],
  },
  {
    id: "family-recipe",
    tab: "素材 11｜家庭食谱",
    title: "通用素材 11：祖母的食谱本和春节饺子",
    tagline: "家庭重要物品 + 特殊场合的食物",
    description: "使用同一件家庭物品和同一次春节聚餐：祖母的手写食谱本记录了家里的饺子做法。",
    storyline: "祖母的旧食谱本 → 保存三十多年 → 春节按食谱包饺子 → 全家一起准备 → 味道熟悉 → 家庭记忆",
    modules: [
      {
        label: "01 · 重要物品",
        title: "祖母的手写食谱本",
        detail: "一本普通的蓝色笔记本，里面写着几十道家庭菜谱。",
        sentence: "An important item in my family is an old recipe notebook written by my grandmother.",
      },
      {
        label: "02 · 保存时间",
        title: "使用了三十多年",
        detail: "母亲结婚时祖母送给她，此后一直保存在家里厨房。",
        sentence: "My family has kept it for more than thirty years, and my mother still uses it on special occasions.",
      },
      {
        label: "03 · 特殊场合",
        title: "春节家庭聚餐",
        detail: "去年春节，全家按照食谱一起准备猪肉白菜馅饺子。",
        sentence: "Last Spring Festival, we used the notebook to make pork and cabbage dumplings together.",
      },
      {
        label: "04 · 制作过程",
        title: "全家分工包饺子",
        detail: "母亲准备馅料，其他人包饺子，边做边聊天。",
        sentence: "My mother prepared the filling while the rest of us wrapped the dumplings and talked together.",
      },
      {
        label: "05 · 食物感受",
        title: "简单但熟悉的味道",
        detail: "饺子不是昂贵食物，但让人想到童年和家庭团聚。",
        sentence: "The dumplings were simple, but their familiar taste reminded me of family celebrations when I was a child.",
      },
      {
        label: "06 · 物品意义",
        title: "连接家庭成员和记忆",
        detail: "食谱本不仅记录做法，也保存祖母的笔迹和家庭传统。",
        sentence: "The notebook is important because it preserves my grandmother's handwriting and connects different generations of our family.",
      },
    ],
    baseAnswer:
      "I'd like to talk about an old recipe notebook written by my grandmother. It is a simple blue notebook containing many family recipes, and we have kept it for more than thirty years. My grandmother gave it to my mother when she got married, and my mother still uses it on special occasions. Last Spring Festival, we followed one of the recipes to make pork and cabbage dumplings. My mother prepared the filling while the rest of us wrapped the dumplings and talked together. They were not expensive or unusual, but their familiar taste reminded me of family celebrations when I was a child. The notebook is important because it preserves my grandmother's handwriting as well as our family traditions. Whenever we use it, it feels as if she is still sharing something with us.",
    topics: [
      {
        id: "recipe-food",
        code: "R1",
        name: "特殊场合吃过的食物",
        question: "Describe a food you ate on a special occasion.",
        answer: [
          special("I'd like to talk about some dumplings I ate during a special family occasion."),
          common("Last Spring Festival, we used the notebook to make pork and cabbage dumplings together."),
          special("The notebook was written by my grandmother and contains the recipe our family has followed for many years."),
          common("My mother prepared the filling while the rest of us wrapped the dumplings and talked together."),
          special("I ate them at my parents' home with my girlfriend, my parents and several relatives. We served them with a little vinegar and shared several other home-cooked dishes."),
          common("The dumplings were simple, but their familiar taste reminded me of family celebrations when I was a child."),
          special("What made the meal special was not the price of the food but the chance to sit together after a busy year."),
          common("The notebook is important because it preserves my grandmother's handwriting and connects different generations of our family."),
          special("I felt warm and relaxed, and I hope we continue this tradition in the future."),
        ],
      },
      {
        id: "recipe-family-item",
        code: "R2",
        name: "对家庭重要的物品",
        question: "Describe an item that is important to your family.",
        answer: [
          special("I'd like to talk about an item that has been important to my family for many years."),
          common("An important item in my family is an old recipe notebook written by my grandmother."),
          special("It is a small blue notebook with worn pages and simple handwritten instructions for dumplings, noodles and other home-cooked dishes."),
          common("My family has kept it for more than thirty years, and my mother still uses it on special occasions."),
          special("My grandmother gave it to my mother when she got married. Since then, it has always been kept in a drawer in our kitchen."),
          common("Last Spring Festival, we used the notebook to make pork and cabbage dumplings together."),
          common("My mother prepared the filling while the rest of us wrapped the dumplings and talked together."),
          common("The notebook is important because it preserves my grandmother's handwriting and connects different generations of our family."),
          special("It is not valuable in terms of money, but nobody in my family would want to lose it."),
        ],
      },
    ],
    rules: [
      "食物题重点讲什么时候吃、和谁吃以及感受；物品题重点讲来源、保存时间和家庭意义。",
      "不要把食谱本说成昂贵古董，它的价值来自笔迹、传统和共同记忆。",
      "食谱本现在仍被保存使用现在时或现在完成时；春节聚餐使用过去时。",
    ],
  },
  {
    id: "paddington",
    tab: "素材 12｜动物故事",
    title: "通用素材 12：《帕丁顿熊》的故事与电影",
    tagline: "动物故事或书 + 最近看的电影 + 搞笑视频",
    description: "固定同一个作品：小时候听过《帕丁顿熊》的故事，最近看了电影，也在手机上看过其中的搞笑片段。",
    storyline: "小时候听老师讲故事 → 来自秘鲁的小熊到伦敦 → 被家庭收留 → 最近和女朋友看电影 → 浴室搞笑片段 → 温暖有趣",
    modules: [
      {
        label: "01 · 故事名称",
        title: "《帕丁顿熊》",
        detail: "主角是一只来自秘鲁、后来来到伦敦生活的小熊。",
        sentence: "The story is about a polite young bear called Paddington who travels from Peru to London.",
      },
      {
        label: "02 · 初次接触",
        title: "小学时听老师讲故事",
        detail: "英语老师用简化版本讲给全班听，也展示了书中的图片。",
        sentence: "I first heard the story from my English teacher when I was at primary school.",
      },
      {
        label: "03 · 故事内容",
        title: "被一个家庭收留",
        detail: "Paddington 在车站被发现，遇到很多麻烦，但最终找到家。",
        sentence: "A family finds him at a railway station and gives him a home, although he often causes small accidents.",
      },
      {
        label: "04 · 电影经历",
        title: "最近在家观看电影",
        detail: "上个月与女朋友在家看电影，故事容易理解，节奏轻松。",
        sentence: "Last month, I watched the film version at home with my girlfriend.",
      },
      {
        label: "05 · 搞笑片段",
        title: "浴室里造成混乱",
        detail: "Paddington 第一次使用浴室，不小心让浴缸里的水流得到处都是。",
        sentence: "The funniest part shows Paddington trying to use a bathroom and accidentally flooding it.",
      },
      {
        label: "06 · 总体感受",
        title: "轻松、温暖并适合家庭观看",
        detail: "既有简单笑点，也讲述善意、家庭和接纳。",
        sentence: "I like it because it is funny and relaxing but also has a warm message about kindness and family.",
      },
    ],
    baseAnswer:
      "I'd like to talk about the story of Paddington, a polite young bear who travels from Peru to London. I first heard a simple version from my English teacher when I was at primary school. In the story, a family finds Paddington at a railway station and gives him a home. He is friendly and well meaning, but he often causes small accidents because city life is new to him. Last month, I watched the film version at home with my girlfriend. The funniest scene shows Paddington trying to use a bathroom and accidentally flooding it. I later saw the same short clip on my phone and laughed again. I like the story because it is easy to understand, funny and relaxing. It also has a warm message about kindness, family and accepting someone who is different.",
    topics: [
      {
        id: "paddington-story",
        code: "P1",
        name: "包含动物的故事或书",
        question: "Describe a story or book that has an animal in it.",
        answer: [
          special("I'd like to talk about an animal story that I have remembered since childhood."),
          common("The story is about a polite young bear called Paddington who travels from Peru to London."),
          common("I first heard the story from my English teacher when I was at primary school."),
          special("She told us a simplified version in class and showed us some colourful pictures from the book."),
          common("A family finds him at a railway station and gives him a home, although he often causes small accidents."),
          special("Paddington tries to behave well, but ordinary things such as using a bathroom or travelling around the city become difficult for him."),
          common("The funniest part shows Paddington trying to use a bathroom and accidentally flooding it."),
          common("I like it because it is funny and relaxing but also has a warm message about kindness and family."),
          special("It was one of the first English stories I could follow, so it also gave me confidence as a child."),
        ],
      },
      {
        id: "paddington-movie",
        code: "P2",
        name: "最近看过的电影",
        question: "Describe a movie you watched recently.",
        answer: [
          special("I'd like to talk about a film called Paddington that I watched recently."),
          common("Last month, I watched the film version at home with my girlfriend."),
          common("The story is about a polite young bear called Paddington who travels from Peru to London."),
          common("A family finds him at a railway station and gives him a home, although he often causes small accidents."),
          special("We chose it because we wanted something light after a busy week. The story was simple, so we could relax without concentrating too hard."),
          common("The funniest part shows Paddington trying to use a bathroom and accidentally flooding it."),
          special("My girlfriend and I both laughed because he was trying to be careful but made the situation much worse."),
          common("I like it because it is funny and relaxing but also has a warm message about kindness and family."),
          special("I felt cheerful after watching it and would happily recommend it to families or people who want an easy film."),
        ],
      },
      {
        id: "paddington-video",
        code: "P3",
        name: "看过的搞笑视频",
        question: "Describe a funny video you watched.",
        answer: [
          special("I'd like to talk about a funny video clip from the film Paddington."),
          special("I saw it on my phone a few weeks ago while I was looking through short videos after work."),
          common("The story is about a polite young bear called Paddington who travels from Peru to London."),
          common("The funniest part shows Paddington trying to use a bathroom and accidentally flooding it."),
          special("In the clip, he touches several things without understanding how they work. Water starts going everywhere, and he tries to stop it but only creates more trouble."),
          special("The scene is funny because Paddington looks serious and polite while the bathroom becomes completely chaotic."),
          common("Last month, I watched the film version at home with my girlfriend."),
          special("I sent the clip to her because we had both enjoyed that part of the movie, and she replied with a laughing emoji."),
          common("I like it because it is funny and relaxing but also has a warm message about kindness and family."),
        ],
      },
    ],
    rules: [
      "故事题必须说明何时读到或听到；电影题必须说明在哪里、和谁看；视频题必须详细解释笑点。",
      "三题共用作品，但分别围绕故事、整部电影和一个短片段展开，不能只换第一句话。",
      "童年接触使用过去时；故事情节可用现在时；最近观看经历使用过去时。",
    ],
  },
  {
    id: "high-rise-home",
    tab: "素材 13｜想参观的家",
    title: "独立素材 13：朋友在上海的高层公寓",
    tagline: "想参观但不想居住的家",
    description: "这道题不与城市建筑题硬合并，单独讲朋友 David 位于上海高层住宅中的现代公寓。",
    storyline: "朋友 David 的家 → 上海高层公寓 → 落地窗和智能设备 → 想看城市景色 → 楼层太高、空间有限、生活昂贵 → 只想参观",
    modules: [
      {
        label: "01 · 房屋主人",
        title: "朋友 David 的公寓",
        detail: "David 是以前的同事，几年前搬到上海工作。",
        sentence: "The home belongs to my former colleague David, who now works in Shanghai.",
      },
      {
        label: "02 · 位置",
        title: "市中心附近的高层住宅",
        detail: "公寓位于一栋四十多层的现代住宅中，交通方便。",
        sentence: "His apartment is on a high floor of a modern building near the city centre.",
      },
      {
        label: "03 · 房屋外观",
        title: "落地窗和城市景色",
        detail: "房屋不大但设计整洁，有大窗户、开放式厨房和智能设备。",
        sentence: "It has large windows, a small open kitchen and a wide view of the city lights.",
      },
      {
        label: "04 · 想参观原因",
        title: "体验现代城市生活",
        detail: "想看看景色、智能家居，也想与朋友一起吃饭聊天。",
        sentence: "I would like to visit because I am curious about the view and the smart devices in his home.",
      },
      {
        label: "05 · 不想居住原因",
        title: "太高、空间小且生活昂贵",
        detail: "更喜欢较安静、空间更充足的房子，不适合长期住在高层。",
        sentence: "However, I would not want to live there because it is very high, quite small and probably expensive.",
      },
    ],
    baseAnswer:
      "I'd like to talk about my former colleague David's apartment in Shanghai. He moved there for work a few years ago and now lives on a high floor of a modern building near the city centre. I have seen photos of the apartment, and it looks clean and carefully designed. It has large windows, a small open kitchen and a wide view of the city lights. There are also several smart devices that control the lights and curtains. I would like to visit because I am curious about the view and would enjoy having dinner with David while looking over the city. However, I would not want to live there because the floor is very high, the space is limited and daily life in that area is probably expensive. I prefer a quieter home with more space and easier access to the ground.",
    topics: [
      {
        id: "home-visit-not-live",
        code: "H1",
        name: "想参观但不想居住的家",
        question: "Describe a home you would like to visit but not live in.",
        answer: [
          special("I'd like to talk about a home that I would like to visit but would not want to live in."),
          common("The home belongs to my former colleague David, who now works in Shanghai."),
          common("His apartment is on a high floor of a modern building near the city centre."),
          special("I have only seen it in photos and during video calls, but it looks clean and carefully designed."),
          common("It has large windows, a small open kitchen and a wide view of the city lights."),
          special("It also has smart lights and curtains that can be controlled by phone."),
          common("I would like to visit because I am curious about the view and the smart devices in his home."),
          special("I would also enjoy having dinner with David and talking about his life in Shanghai."),
          common("However, I would not want to live there because it is very high, quite small and probably expensive."),
          special("I prefer a quieter home with more space and easier access to the ground, so one visit would be enough for me."),
        ],
      },
    ],
    rules: [
      "必须明确房屋属于谁，并同时解释想参观和不想居住的不同原因。",
      "不要只描述高楼外观，答案核心是室内空间、生活体验和个人选择。",
      "尚未参观使用 would like to；房屋现在的事实使用现在时。",
    ],
  },
  {
    id: "expensive-laptop",
    tab: "素材 14｜超预算物品",
    title: "独立素材 14：比预计更贵的工作笔记本电脑",
    tagline: "买得比预计更贵的物品",
    description: "使用真实工作背景，讲一次购买高性能笔记本电脑时因为内存、存储和保修而超出预算的经历。",
    storyline: "旧电脑变慢 → 计划八千元 → 比较型号 → 增加内存和存储 → 实际花一万一千元 → 工作效率提高 → 心疼但值得",
    modules: [
      {
        label: "01 · 购买物品",
        title: "用于工作的笔记本电脑",
        detail: "两年前旧电脑变慢，因此决定购买一台性能更好的新电脑。",
        sentence: "About two years ago, I bought a new laptop mainly for software development and daily work.",
      },
      {
        label: "02 · 原始预算",
        title: "原计划花八千元",
        detail: "认为普通型号已经足够，最初设置了明确预算。",
        sentence: "I originally planned to spend about eight thousand yuan.",
      },
      {
        label: "03 · 价格上涨",
        title: "升级配置和延长保修",
        detail: "为了多用几年，选择更大内存、存储空间和保修服务。",
        sentence: "After choosing more memory, extra storage and a longer warranty, the final price was nearly eleven thousand yuan.",
      },
      {
        label: "04 · 购买原因",
        title: "工作稳定且速度更快",
        detail: "软件工程工作需要同时运行多个程序，旧电脑已经影响效率。",
        sentence: "I decided to buy it because I needed a reliable computer that could run several work programmes smoothly.",
      },
      {
        label: "05 · 最终感受",
        title: "超预算但长期值得",
        detail: "付款时心疼，但使用频率高，节省了很多等待时间。",
        sentence: "I felt uncomfortable about the price at first, but the laptop has been reliable and useful every day.",
      },
    ],
    baseAnswer:
      "I'd like to talk about a laptop I bought about two years ago for software development and daily work. My old computer had become slow, so I planned to replace it and expected to spend about eight thousand yuan. After comparing several models, I realised that I needed more memory and storage because I often run several work programmes at the same time. I also added a longer warranty because I hoped to use the laptop for several years. These choices increased the final price to nearly eleven thousand yuan, which was much more than I had expected. I felt uncomfortable when I paid for it and wondered whether I had spent too much. However, the laptop has been fast and reliable, and I use it almost every day. In the end, I think it was expensive but worth buying.",
    topics: [
      {
        id: "item-cost-more",
        code: "E1",
        name: "买得比预计更贵的物品",
        question: "Describe an item you bought that cost more than you expected.",
        answer: [
          special("I'd like to talk about an item that cost much more than I expected."),
          common("About two years ago, I bought a new laptop mainly for software development and daily work."),
          special("My old computer had become slow and sometimes stopped responding, so replacing it was necessary rather than simply something I wanted."),
          common("I originally planned to spend about eight thousand yuan."),
          special("However, after comparing several models, I realised that a basic one might become slow again quite quickly."),
          common("After choosing more memory, extra storage and a longer warranty, the final price was nearly eleven thousand yuan."),
          common("I decided to buy it because I needed a reliable computer that could run several work programmes smoothly."),
          special("When I paid, I felt a little guilty because the price was far above my budget."),
          common("I felt uncomfortable about the price at first, but the laptop has been reliable and useful every day."),
          special("Looking back, I think the extra cost was acceptable because it has saved me time and should last for several years."),
        ],
      },
    ],
    rules: [
      "必须给出预计价格和实际价格，才能直接回答“比预计更贵”。",
      "购买原因和最终感受都要展开，不要把答案变成电脑参数介绍。",
      "购买过程使用过去时；持续到现在的使用效果可使用现在完成时。",
    ],
  },
  {
    id: "foldable-phone",
    tab: "素材 15｜想拥有的科技",
    title: "独立素材 15：想拥有的折叠屏手机",
    tagline: "想拥有的科技产品",
    description: "选择容易解释的折叠屏手机，重点讲大屏与便携性的结合、工作和旅行用途，以及暂时没有购买的原因。",
    storyline: "折叠屏手机 → 展开像小平板 → 看文档和视频 → 旅行时便携 → 当前价格高 → 等更成熟后购买 → 好奇和期待",
    modules: [
      {
        label: "01 · 产品名称",
        title: "折叠屏智能手机",
        detail: "合起来与普通手机接近，展开后屏幕像一台小平板。",
        sentence: "A piece of technology I would like to own is a foldable smartphone.",
      },
      {
        label: "02 · 主要功能",
        title: "在便携设备上使用更大屏幕",
        detail: "适合阅读文档、看视频、同时打开两个应用。",
        sentence: "It can open into a larger screen, which makes reading documents and watching videos more comfortable.",
      },
      {
        label: "03 · 工作用途",
        title: "查看工作信息和简单处理任务",
        detail: "外出时可以更方便地阅读错误信息、邮件或项目文档。",
        sentence: "The larger screen would also help me check work messages and technical documents when I am away from my computer.",
      },
      {
        label: "04 · 想拥有原因",
        title: "比平板更容易携带",
        detail: "旅行时只带一部手机，也能获得接近平板的使用体验。",
        sentence: "I want one because it combines the portability of a phone with some of the benefits of a tablet.",
      },
      {
        label: "05 · 暂未购买",
        title: "价格和耐用性仍需观察",
        detail: "目前价格较高，也担心折叠部分长期使用后的稳定性。",
        sentence: "I have not bought one yet because it is expensive and I am still unsure about its durability.",
      },
      {
        label: "06 · 感受",
        title: "期待但愿意等待",
        detail: "对新设计很好奇，但会等价格降低和产品更成熟。",
        sentence: "I feel excited about the idea, but I am willing to wait until the technology becomes more affordable and reliable.",
      },
    ],
    baseAnswer:
      "A piece of technology I would like to own is a foldable smartphone. When it is closed, it works like an ordinary phone, but it can open into a larger screen like a small tablet. This would make reading documents, watching videos and using two apps at the same time more comfortable. As a software engineer, I sometimes need to check work messages or technical information when I am away from my computer, and the larger screen would be useful. It would also be easier to carry than both a phone and a tablet when travelling. I have not bought one yet because the current models are expensive and I am still unsure about their durability. I feel excited about the design, but I am willing to wait until the technology becomes more affordable and reliable.",
    topics: [
      {
        id: "technology-want-own",
        code: "T1",
        name: "想拥有的科技产品",
        question: "Describe a piece of technology you would like to own.",
        answer: [
          special("I'd like to talk about a piece of technology that I hope to own in the future."),
          common("A piece of technology I would like to own is a foldable smartphone."),
          special("When it is closed, it looks and works like an ordinary phone, so it can still fit into a pocket."),
          common("It can open into a larger screen, which makes reading documents and watching videos more comfortable."),
          special("Some models can also show two apps side by side, which would make simple tasks easier."),
          common("The larger screen would also help me check work messages and technical documents when I am away from my computer."),
          common("I want one because it combines the portability of a phone with some of the benefits of a tablet."),
          common("I have not bought one yet because it is expensive and I am still unsure about its durability."),
          common("I feel excited about the idea, but I am willing to wait until the technology becomes more affordable and reliable."),
        ],
      },
    ],
    rules: [
      "必须明确它能做什么、为什么想拥有，以及目前还没有购买的原因。",
      "用日常用途解释科技产品，不堆叠屏幕尺寸或硬件参数。",
      "愿望和假设用途使用 would、would like to；当前产品事实使用现在时。",
    ],
  },
  {
    id: "wechat-app",
    tab: "素材 16｜常用应用",
    title: "独立素材 16：每天使用的微信",
    tagline: "经常使用的应用或程序",
    description: "使用最熟悉的日常应用，围绕联系家人朋友、工作群、付款和视频通话展开。",
    storyline: "微信 → 每天多次使用 → 联系家人朋友 → 查看工作群 → 付款和视频通话 → 方便但通知多 → 管理使用时间",
    modules: [
      {
        label: "01 · 应用名称",
        title: "微信",
        detail: "手机上最常使用的通信应用之一，工作和生活都会用到。",
        sentence: "The app I use most often is WeChat, a communication app on my phone.",
      },
      {
        label: "02 · 使用频率",
        title: "每天使用很多次",
        detail: "早上查看消息，白天处理工作群，晚上联系家人朋友。",
        sentence: "I use it many times a day, both for work and for my personal life.",
      },
      {
        label: "03 · 联系功能",
        title: "消息和视频通话",
        detail: "与家人、女朋友和朋友聊天，也能在不能见面时视频通话。",
        sentence: "I mainly use it to send messages, share photos and make video calls with family and friends.",
      },
      {
        label: "04 · 工作功能",
        title: "查看团队消息",
        detail: "工作群用于发送通知和简单更新，但重要技术问题仍在正式工具处理。",
        sentence: "I also check work groups for short updates and important notices from my team.",
      },
      {
        label: "05 · 其他用途",
        title: "付款和日常服务",
        detail: "在商店付款、转账或使用一些简单的小程序。",
        sentence: "It is also useful for making payments and using simple everyday services.",
      },
      {
        label: "06 · 总体感受",
        title: "方便但需要控制通知",
        detail: "节省时间，但消息太多会分散注意力，因此会关闭部分提醒。",
        sentence: "I find it extremely convenient, although I turn off some notifications so that it does not distract me from work.",
      },
    ],
    baseAnswer:
      "The app I use most often is WeChat, a communication app on my phone. I use it many times a day for both work and my personal life. I mainly use it to send messages, share photos and make video calls with family and friends. It is especially useful because some of my relatives live in another city, so we cannot meet very often. I also check work groups for short updates and important notices from my team. Besides communication, I sometimes use it to make payments in shops or use simple everyday services. I find WeChat extremely convenient because it puts many useful functions in one place. However, too many messages can be distracting, so I turn off some notifications when I need to focus on work or relax after a busy day.",
    topics: [
      {
        id: "app-often-use",
        code: "W1",
        name: "经常使用的应用或程序",
        question: "Describe an app or programme you often use.",
        answer: [
          special("I'd like to talk about an app that is an important part of my daily life."),
          common("The app I use most often is WeChat, a communication app on my phone."),
          common("I use it many times a day, both for work and for my personal life."),
          special("I normally check it in the morning, use it occasionally during the working day and reply to personal messages in the evening."),
          common("I mainly use it to send messages, share photos and make video calls with family and friends."),
          special("This is helpful because some of my relatives live in another city and we cannot meet regularly."),
          common("I also check work groups for short updates and important notices from my team."),
          common("It is also useful for making payments and using simple everyday services."),
          common("I find it extremely convenient, although I turn off some notifications so that it does not distract me from work."),
          special("Overall, it saves me time and makes it easier to stay connected with the people around me."),
        ],
      },
    ],
    rules: [
      "依次覆盖应用是什么、使用频率、主要用途和感受，不要只罗列功能。",
      "加入通知分散注意力的小缺点，可以让评价更自然、更平衡。",
      "描述日常习惯使用一般现在时，并注意第三人称和复数形式。",
    ],
  },
];
