export type TopicMaterial = {
  id: string;
  sourceOrder: number;
  title: string;
  titleEn: string;
  ideas: string[];
  logic: string[];
  paragraph: string;
  translation: string;
  phrases: string[];
  priority?: boolean;
};

export type MaterialCategory = {
  id: string;
  name: string;
  nameEn: string;
  summary: string;
  materials: TopicMaterial[];
};

export const categories: MaterialCategory[] = [
  {
    id: "society",
    name: "社会",
    nameEn: "Society",
    summary: "对应 PDF 第一部分：人口、教育、福利、法律、家庭和文化身份。",
    materials: [
      {
        id: "society-population",
        sourceOrder: 1,
        title: "人口变化",
        titleEn: "Population changes",
        ideas: [
          "人口老龄化：劳动力减少，养老金和医疗负担上升",
          "城市化：住房和基础设施需求增加，居住成本上升",
          "城市人口过密：可能带来污染、拥堵和社会隔离",
        ],
        logic: ["人口结构发生变化", "公共资源需求增加", "政府和家庭负担上升", "生活质量可能受到影响"],
        paragraph: "Population changes can create pressure on society. An ageing population increases the cost of pensions and health care, while rapid urbanisation raises the demand for housing, transport and other public services.",
        translation: "人口变化会给社会带来压力。人口老龄化会增加养老金和医疗成本，而快速城市化会提高住房、交通和其他公共服务的需求。",
        phrases: ["create pressure on society", "an ageing population", "the cost of pensions and health care", "rapid urbanisation", "the demand for housing, transport and other public services"],
        priority: true,
      },
      {
        id: "society-education-training",
        sourceOrder: 2,
        title: "教育和培训",
        titleEn: "Education and training",
        ideas: [
          "教育投资：提高就业能力、收入和社会流动机会",
          "职业教育与终身学习：帮助劳动者适应就业市场变化",
          "教育不平等：限制低收入群体的发展并加剧社会差距",
        ],
        logic: ["获得教育和培训", "掌握实用知识与技能", "就业机会和收入提高", "个人与社会共同受益"],
        paragraph: "Investment in education gives people useful knowledge and job skills. Vocational training and lifelong learning also help workers adapt to a changing job market, while equal access to education can reduce social inequality.",
        translation: "教育投资能让人们获得有用的知识和工作技能。职业培训和终身学习也能帮助劳动者适应不断变化的就业市场，而平等的教育机会可以减少社会不平等。",
        phrases: ["investment in education", "useful knowledge and job skills", "vocational training and lifelong learning", "adapt to a changing job market", "equal access to education", "reduce social inequality"],
        priority: true,
      },
      {
        id: "society-welfare-policy",
        sourceOrder: 3,
        title: "社会福利和政策",
        titleEn: "Social welfare and policies",
        ideas: [
          "社会福利：为弱势群体提供基本保障，减少贫困",
          "政策设计：税收、医疗和教育政策会影响社会公平",
          "政策可持续性：老龄化使养老金和医疗支出持续增加",
        ],
        logic: ["政府提供基本支持", "弱势群体获得帮助", "贫困和不平等减少", "社会更加稳定"],
        paragraph: "Social welfare can protect vulnerable people and reduce poverty. However, governments need fair and sustainable policies because the rising cost of pensions, health care and education may place pressure on public budgets.",
        translation: "社会福利可以保护弱势群体并减少贫困。但是，政府需要制定公平且可持续的政策，因为不断上升的养老金、医疗和教育成本可能会给公共预算带来压力。",
        phrases: ["social welfare", "protect vulnerable people and reduce poverty", "fair and sustainable policies", "the rising cost of pensions, health care and education", "place pressure on public budgets"],
        priority: true,
      },
      {
        id: "society-crime-law",
        sourceOrder: 4,
        title: "犯罪和法律",
        titleEn: "Crime and law",
        ideas: [
          "法律制度：维持社会秩序、公平并保护公民权利",
          "预防犯罪：通过教育、就业和社会支持减少犯罪动机",
          "法律改革：应对网络安全、隐私和知识产权等新问题",
        ],
        logic: ["提供教育、工作和支持", "人们拥有稳定生活", "犯罪动机减少", "社区更加安全"],
        paragraph: "A fair legal system protects citizens and maintains social order. Crime can also be prevented through education, employment and social support, while laws should be updated to deal with online privacy and cybercrime.",
        translation: "公平的法律制度可以保护公民并维持社会秩序。教育、就业和社会支持也可以预防犯罪，同时法律应及时更新，以处理网络隐私和网络犯罪问题。",
        phrases: ["a fair legal system", "protects citizens", "maintains social order", "education, employment and social support", "online privacy and cybercrime"],
      },
      {
        id: "society-family-children",
        sourceOrder: 5,
        title: "家庭和儿童抚养",
        titleEn: "Family and child-rearing",
        ideas: [
          "家庭结构变化：单亲或双职工家庭会改变儿童照顾方式",
          "儿童投入：早期教育和健康支持影响长期发展",
          "家庭政策：育儿假和托儿服务帮助父母平衡工作与家庭",
        ],
        logic: ["家庭获得育儿支持", "父母更好地平衡工作与家庭", "儿童得到稳定照顾", "儿童长期发展改善"],
        paragraph: "Changes in family structure can affect the way children are raised. Parental leave, affordable childcare and early education can help working parents and give children a safer and more supportive environment.",
        translation: "家庭结构的变化会影响儿童的抚养方式。育儿假、可负担的托儿服务和早期教育可以帮助在职父母，并为儿童提供更安全、更有支持性的环境。",
        phrases: ["changes in family structure", "affect the way children are raised", "parental leave, affordable childcare and early education", "help working parents", "a safer and more supportive environment"],
      },
      {
        id: "society-cultural-identity",
        sourceOrder: 6,
        title: "文化遗产和身份认同",
        titleEn: "Cultural heritage and identity",
        ideas: [
          "文化多样性：可以促进创新和包容，也可能带来文化冲突",
          "遗产保护：保存历史遗迹和传统，加强社区认同",
          "文化政策：支持艺术活动，并为社会和经济带来好处",
        ],
        logic: ["保护遗产并支持文化活动", "人们了解共同历史", "社区认同和凝聚力增强", "传统得以传承"],
        paragraph: "Protecting cultural heritage helps people understand their shared history and strengthens community identity. Support for diverse cultures and the arts can also make society more inclusive and create benefits for tourism and local jobs.",
        translation: "保护文化遗产有助于人们了解共同历史，并加强社区认同。支持多元文化和艺术也可以让社会更加包容，并为旅游业和本地就业带来好处。",
        phrases: ["protecting cultural heritage", "shared history", "community identity", "diverse cultures and the arts", "more inclusive", "tourism and local jobs"],
      },
    ],
  },
  {
    id: "economy",
    name: "经济",
    nameEn: "Economy",
    summary: "对应 PDF 第二部分：增长、就业、贫困、投资、贸易和公共支出。",
    materials: [
      {
        id: "economy-growth-development",
        sourceOrder: 1,
        title: "经济增长和发展",
        titleEn: "Economic growth and development",
        ideas: [
          "经济增长：商品和服务总量增加",
          "经济发展：还包括生活水平、教育和健康的改善",
          "增长的好处与风险：创造就业，但也可能消耗资源、污染环境",
        ],
        logic: ["企业生产和投资增加", "更多工作机会出现", "居民收入提高", "生活水平得到改善"],
        paragraph: "Economic growth can create jobs, raise national income and improve living standards. However, real development should also improve education and health, and growth must be managed carefully to avoid pollution and resource depletion.",
        translation: "经济增长可以创造就业、提高国民收入并改善生活水平。但是，真正的发展还应改善教育和健康，而且必须谨慎管理增长，以避免污染和资源枯竭。",
        phrases: ["economic growth", "create jobs", "raise national income", "improve living standards", "improve education and health", "pollution and resource depletion"],
        priority: true,
      },
      {
        id: "economy-employment",
        sourceOrder: 2,
        title: "就业和失业",
        titleEn: "Employment and unemployment",
        ideas: [
          "高就业率：增加家庭收入，促进经济和社会稳定",
          "失业：可能导致贫困、压力、犯罪和社会不安",
          "政府措施：通过投资、职业培训和再教育创造机会",
        ],
        logic: ["提供投资和技能培训", "失业者重新进入劳动力市场", "家庭获得稳定收入", "贫困和社会问题减少"],
        paragraph: "Stable employment gives families a regular income and improves their quality of life. During periods of high unemployment, governments can invest in new jobs and provide vocational training to help people return to work.",
        translation: "稳定就业能为家庭提供固定收入并改善生活质量。在高失业时期，政府可以投资创造新岗位，并提供职业培训来帮助人们重返工作。",
        phrases: ["stable employment", "a regular income", "quality of life", "high unemployment", "invest in new jobs", "vocational training"],
        priority: true,
      },
      {
        id: "economy-income-poverty",
        sourceOrder: 3,
        title: "收入分配和贫困",
        titleEn: "Income distribution and poverty",
        ideas: [
          "收入不平等：可能引发社会分裂和不满",
          "贫困循环：贫困限制教育和就业机会，贫困因此延续",
          "解决方式：税收、福利与较公平地分享经济增长成果",
        ],
        logic: ["低收入者缺少教育和工作机会", "收入难以提高", "贫困持续到下一代", "社会不平等加剧"],
        paragraph: "A wide income gap can cause dissatisfaction and social division. Poverty may also limit access to education and employment, so fair taxation and welfare support are needed to help people break this cycle.",
        translation: "过大的收入差距会引发不满和社会分裂。贫困也可能限制人们获得教育和工作的机会，因此需要公平的税收和福利支持来帮助人们打破这一循环。",
        phrases: ["a wide income gap", "dissatisfaction and social division", "limit access to education and employment", "fair taxation and welfare support", "break this cycle"],
      },
      {
        id: "economy-investment-saving",
        sourceOrder: 4,
        title: "投资和储蓄",
        titleEn: "Investment and savings",
        ideas: [
          "投资：推动技术进步、生产率和经济增长",
          "储蓄：为个人、企业和国家投资提供资金",
          "政府和个人：可用税收或利率鼓励储蓄，同时管理投资风险",
        ],
        logic: ["个人和企业增加储蓄", "更多资金可用于投资", "技术与生产率提高", "经济获得长期发展"],
        paragraph: "Savings provide money for business investment, which can improve technology and productivity. Governments may encourage saving through suitable tax and interest-rate policies, although people should still consider the possible risks of investment.",
        translation: "储蓄可以为企业投资提供资金，从而改善技术并提高生产率。政府可以通过合适的税收和利率政策鼓励储蓄，不过人们仍应考虑投资可能带来的风险。",
        phrases: ["savings provide money for business investment", "improve technology and productivity", "encourage saving", "tax and interest-rate policies", "risks of investment"],
      },
      {
        id: "economy-trade-globalisation",
        sourceOrder: 5,
        title: "贸易和全球化",
        titleEn: "Trade and globalisation",
        ideas: [
          "国际贸易：提高资源利用效率，增加商品选择",
          "全球化：加强国家间的经济、技术和文化交流",
          "保护与公平：过度保护会降低竞争力，公平贸易可帮助发展中国家",
        ],
        logic: ["国家开展国际贸易", "企业进入更大的市场", "商品选择增加、价格下降", "经济联系和效率提高"],
        paragraph: "International trade gives consumers more choices and allows businesses to enter larger markets. Globalisation can also spread technology and ideas, but trade rules should be fair so that poorer countries can share the benefits.",
        translation: "国际贸易给消费者更多选择，也让企业进入更大的市场。全球化还可以传播技术和思想，但贸易规则应当公平，让较贫穷的国家也能分享好处。",
        phrases: ["international trade", "more choices", "enter larger markets", "spread technology and ideas", "trade rules should be fair", "poorer countries can share the benefits"],
      },
      {
        id: "economy-tax-public-spending",
        sourceOrder: 6,
        title: "税收和公共支出",
        titleEn: "Taxation and public expenditure",
        ideas: [
          "税收功能：为公共服务和基础设施提供主要资金",
          "公共支出：合理投入可以促进发展并提高社会福利",
          "政策风险：税收会影响个人和企业，过度借贷可能造成财政赤字",
        ],
        logic: ["政府征收税款", "资金投入教育、医疗和交通", "更多人获得基本服务", "整体生活质量提高"],
        paragraph: "Tax revenue pays for schools, hospitals and public infrastructure. Well-planned public spending can improve social welfare and support economic development, but excessive government borrowing may create serious financial problems.",
        translation: "税收收入用于学校、医院和公共基础设施。规划合理的公共支出可以改善社会福利并支持经济发展，但政府过度借贷可能造成严重的财政问题。",
        phrases: ["tax revenue", "schools, hospitals and public infrastructure", "well-planned public spending", "improve social welfare", "support economic development", "excessive government borrowing"],
      },
    ],
  },
  {
    id: "culture",
    name: "文化",
    nameEn: "Culture",
    summary: "对应 PDF 第三部分：语言、艺术、宗教、传统和媒体。",
    materials: [
      {
        id: "culture-language-communication",
        sourceOrder: 1,
        title: "语言和交流",
        titleEn: "Language and communication",
        ideas: [
          "全球语言：方便国际贸易、旅行和外交",
          "文化身份：本地语言承载历史和文化",
          "交流障碍：语言差异可能影响社会融合和工作机会",
        ],
        logic: ["更多人使用共同语言", "国际交流变得容易", "学习和工作机会增加", "本地语言也可能受到威胁"],
        paragraph: "A common language makes international communication, study and business easier. However, governments and schools should also protect local languages because they are an important part of cultural identity.",
        translation: "共同语言让国际交流、学习和商业活动更加容易。但是，政府和学校也应该保护本地语言，因为它们是文化身份的重要组成部分。",
        phrases: ["a common language", "international communication, study and business", "protect local languages", "an important part of cultural identity"],
      },
      {
        id: "culture-arts-literature",
        sourceOrder: 2,
        title: "艺术和文学",
        titleEn: "Arts and literature",
        ideas: [
          "文化表达：艺术和文学记录价值观、信仰和历史",
          "经济价值：艺术可促进旅游、就业和文化出口",
          "社会凝聚：共同参与艺术活动能加强社区联系",
        ],
        logic: ["社会支持艺术和文学", "人们表达并了解文化", "社区联系得到加强", "旅游和就业也可能增长"],
        paragraph: "Arts and literature allow people to express their values and record their history. They can also strengthen community ties and support the economy by attracting tourists, creating jobs and sharing culture internationally.",
        translation: "艺术和文学让人们表达自己的价值观并记录历史。它们还可以加强社区联系，并通过吸引游客、创造就业和对外传播文化来支持经济。",
        phrases: ["arts and literature", "express their values and record their history", "strengthen community ties", "attracting tourists", "creating jobs", "sharing culture internationally"],
      },
      {
        id: "culture-religion-belief",
        sourceOrder: 3,
        title: "宗教和信仰",
        titleEn: "Religion and belief",
        ideas: [
          "道德框架：宗教可能影响个人行为和决定",
          "社会支持：宗教机构可以提供社区和慈善服务",
          "冲突与包容：信仰差异可能引发冲突，也能培养理解和宽容",
        ],
        logic: ["人们尊重不同信仰", "群体之间增加交流", "误解和冲突减少", "社会更加包容"],
        paragraph: "Religion can give people moral guidance and provide community support. Although different beliefs may sometimes cause conflict, open discussion and mutual respect can encourage tolerance and peaceful relationships.",
        translation: "宗教可以为人们提供道德指导和社区支持。虽然不同信仰有时会造成冲突，但开放交流和相互尊重可以促进包容与和平关系。",
        phrases: ["moral guidance", "community support", "different beliefs may sometimes cause conflict", "open discussion and mutual respect", "encourage tolerance", "peaceful relationships"],
      },
      {
        id: "culture-traditions-customs",
        sourceOrder: 4,
        title: "传统和习俗",
        titleEn: "Traditions and customs",
        ideas: [
          "文化延续：传统帮助人们与过去保持联系",
          "适应变化：传统可以随社会价值变化而调整",
          "包容问题：传统能加强内部联系，也可能排斥不同群体",
        ],
        logic: ["保护并适当更新传统", "年轻人理解文化历史", "不同群体都能参与", "文化得以延续且更加包容"],
        paragraph: "Traditions connect people with the past and strengthen group identity. However, they should be allowed to change with society so that they remain meaningful and do not exclude people from different backgrounds.",
        translation: "传统把人们与过去联系起来，并增强群体认同。但是，传统也应当随着社会变化而调整，使其保持意义，并且不会排斥不同背景的人。",
        phrases: ["connect people with the past", "strengthen group identity", "change with society", "remain meaningful", "exclude people from different backgrounds"],
      },
      {
        id: "culture-media-information",
        sourceOrder: 5,
        title: "媒体和信息传播",
        titleEn: "Media and information",
        ideas: [
          "信息获取：媒体提供信息、影响舆论并促进透明",
          "文化同质化：全球内容可能掩盖本地文化",
          "文化传播民主化：互联网让更多普通人的声音被听见",
        ],
        logic: ["网络和媒体传播大量内容", "公众更容易获取信息和表达观点", "社会交流扩大", "本地文化也可能被忽视"],
        paragraph: "The media gives people access to information and allows more voices to be heard. However, global content can become so popular that local programmes, traditions and cultural identities receive less attention.",
        translation: "媒体让人们获得信息，也让更多声音被听见。但是，全球内容可能过于流行，导致本地节目、传统和文化身份受到较少关注。",
        phrases: ["access to information", "allows more voices to be heard", "global content", "local programmes, traditions and cultural identities", "receive less attention"],
      },
    ],
  },
  {
    id: "environment",
    name: "环境",
    nameEn: "Environment",
    summary: "对应 PDF 第四部分：气候、资源、污染、野生动物和环境政策。",
    materials: [
      {
        id: "environment-climate-sustainability",
        sourceOrder: 1,
        title: "气候变化和可持续发展",
        titleEn: "Climate change and sustainable development",
        ideas: [
          "气候影响：极端天气增加，农业和生态系统受到威胁",
          "可持续发展：保护长期资源供应和生态平衡",
          "国际合作：各国共同减少温室气体排放",
        ],
        logic: ["温室气体持续增加", "全球气温上升", "极端天气更加频繁", "人类和自然环境受到损害"],
        paragraph: "Climate change increases extreme weather and threatens farming and natural ecosystems. Countries should follow sustainable development policies and work together to reduce greenhouse gas emissions because this problem crosses national borders.",
        translation: "气候变化会增加极端天气，并威胁农业和自然生态系统。各国应采取可持续发展政策，并共同减少温室气体排放，因为这个问题跨越国界。",
        phrases: ["climate change", "extreme weather", "threatens farming and natural ecosystems", "sustainable development policies", "reduce greenhouse gas emissions", "crosses national borders"],
      },
      {
        id: "environment-resource-conservation",
        sourceOrder: 2,
        title: "自然资源管理和保护",
        titleEn: "Natural resource management",
        ideas: [
          "资源有限：矿产、森林和水需要合理使用",
          "生态保护：资源保护有助于维持生物多样性和生态平衡",
          "政策管理：法规可以减少非法开采和资源浪费",
        ],
        logic: ["自然资源数量有限", "过度使用造成短缺和环境破坏", "政府进行管理和保护", "未来仍有稳定资源供应"],
        paragraph: "Natural resources such as water, forests and minerals are limited. Careful management and effective laws can prevent overuse and illegal extraction, protect biodiversity and keep enough resources for future generations.",
        translation: "水、森林和矿产等自然资源是有限的。谨慎管理和有效法律可以防止过度使用及非法开采，保护生物多样性，并为后代保留足够的资源。",
        phrases: ["natural resources", "careful management and effective laws", "prevent overuse and illegal extraction", "protect biodiversity", "future generations"],
      },
      {
        id: "environment-pollution-control",
        sourceOrder: 3,
        title: "污染控制和环境保护",
        titleEn: "Pollution control and environmental protection",
        ideas: [
          "污染来源：工业排放、农业污染和生活垃圾",
          "控制措施：严格排放标准和废物处理规定",
          "技术方案：采用清洁技术和可再生能源",
        ],
        logic: ["工业、农业和生活产生污染", "空气、水和健康受到影响", "政府执行排放与废物规定", "污染水平逐渐下降"],
        paragraph: "Industrial emissions, farm waste and household rubbish can damage the environment and public health. Governments should set strict pollution standards, improve waste management and encourage clean technology and renewable energy.",
        translation: "工业排放、农业废物和生活垃圾会损害环境与公众健康。政府应制定严格的污染标准、改善废物管理，并鼓励清洁技术和可再生能源。",
        phrases: ["industrial emissions, farm waste and household rubbish", "damage the environment and public health", "strict pollution standards", "improve waste management", "clean technology and renewable energy"],
        priority: true,
      },
      {
        id: "environment-wildlife",
        sourceOrder: 4,
        title: "野生动植物保护",
        titleEn: "Wildlife protection",
        ideas: [
          "生物多样性：对生态平衡和人类福祉非常重要",
          "濒危原因：栖息地破坏和非法贸易威胁物种生存",
          "保护措施：保护区、物种恢复计划和打击非法交易",
        ],
        logic: ["人类活动破坏栖息地", "野生物种数量下降", "生态平衡受到影响", "保护区和法律帮助恢复物种"],
        paragraph: "Wildlife is important for healthy ecosystems, but many species are threatened by habitat loss and illegal trade. Nature reserves, recovery programmes and stronger laws can protect endangered animals and plants.",
        translation: "野生动植物对健康的生态系统十分重要，但许多物种受到栖息地丧失和非法贸易的威胁。自然保护区、恢复计划和更严格的法律可以保护濒危动植物。",
        phrases: ["healthy ecosystems", "habitat loss and illegal trade", "nature reserves", "recovery programmes", "stronger laws", "protect endangered animals and plants"],
      },
      {
        id: "environment-policy-regulation",
        sourceOrder: 5,
        title: "环境政策和法规",
        titleEn: "Environmental policies and regulations",
        ideas: [
          "政策制定：引导企业和个人采取环保行动",
          "法规执行：监管和处罚确保环境标准被遵守",
          "公众参与：环保意识和参与能提高政策效果",
        ],
        logic: ["政府制定清楚的环境标准", "企业和个人改变行为", "公众参与监督", "环境政策得到有效执行"],
        paragraph: "Environmental policies are effective only when rules are clear and properly enforced. Governments should monitor businesses, punish serious pollution and involve the public so that more people support environmentally friendly action.",
        translation: "只有规定清楚并得到正确执行时，环境政策才会有效。政府应监管企业、处罚严重污染，并让公众参与，从而使更多人支持环保行动。",
        phrases: ["environmental policies", "clear and properly enforced", "monitor businesses", "punish serious pollution", "involve the public", "environmentally friendly action"],
      },
    ],
  },
  {
    id: "technology",
    name: "科技",
    nameEn: "Technology",
    summary: "对应 PDF 第五部分：技术创新、互联网、医疗、交通通信和能源。",
    materials: [
      {
        id: "technology-innovation",
        sourceOrder: 1,
        title: "技术创新和应用",
        titleEn: "Technological innovation",
        ideas: [
          "创新发展：提高生产效率和产品质量",
          "新兴产业：人工智能、生物技术和新能源创造新行业",
          "就业变化：旧岗位消失、新岗位出现，劳动者需要持续培训",
        ],
        logic: ["企业采用新技术", "重复工作更快、更准确", "成本下降、生产率提高", "同时出现新的工作和技能需求"],
        paragraph: "New technology can improve productivity, product quality and economic growth. Although automation may replace some jobs, it also creates new industries, so workers need regular training to learn the skills required by the changing market.",
        translation: "新技术可以提高生产率、产品质量并促进经济增长。尽管自动化可能取代一些工作，它也会创造新产业，因此劳动者需要定期培训，以掌握变化中的市场所需技能。",
        phrases: ["improve productivity", "product quality and economic growth", "automation may replace some jobs", "creates new industries", "regular training", "skills required by the changing market"],
        priority: true,
      },
      {
        id: "technology-internet",
        sourceOrder: 2,
        title: "信息技术和互联网",
        titleEn: "Information technology and the Internet",
        ideas: [
          "信息获取与全球交流：知识、沟通和合作更加方便",
          "隐私安全：个人资料在线存储带来数据风险",
          "数字鸿沟：缺少网络或设备的人可能被排除",
        ],
        logic: ["互联网提供大量信息与沟通工具", "学习和合作不再受地点限制", "更多人获得机会", "隐私风险和数字差距也随之增加"],
        paragraph: "The Internet gives people quick access to information and makes global communication easier. However, personal data must be protected, and governments should help people who lack devices or reliable Internet access.",
        translation: "互联网让人们快速获取信息，也使全球交流更加容易。但是，个人数据必须受到保护，政府也应帮助缺少设备或稳定网络的人。",
        phrases: ["quick access to information", "global communication", "personal data must be protected", "help people who lack devices or reliable Internet access"],
        priority: true,
      },
      {
        id: "technology-medical",
        sourceOrder: 3,
        title: "医学进步和健康",
        titleEn: "Medical advances and health",
        ideas: [
          "疾病治疗：新技术帮助预防、诊断和治疗疾病",
          "健康监测与资源：穿戴设备、远程医疗提高服务效率",
          "伦理问题：基因编辑和人体增强需要谨慎管理",
        ],
        logic: ["医疗技术不断进步", "疾病更早被发现和治疗", "医疗资源使用更有效", "人们活得更健康、更长久"],
        paragraph: "Medical technology can help doctors diagnose diseases earlier and provide more effective treatment. Wearable devices and online services may also improve access to care, although new methods such as gene editing require careful ethical rules.",
        translation: "医疗技术可以帮助医生更早诊断疾病，并提供更有效的治疗。穿戴设备和在线服务也可以改善医疗可及性，不过基因编辑等新方法需要谨慎的伦理规则。",
        phrases: ["medical technology", "diagnose diseases earlier", "effective treatment", "wearable devices and online services", "improve access to care", "gene editing require careful ethical rules"],
      },
      {
        id: "technology-transport-communication",
        sourceOrder: 4,
        title: "交通和通信",
        titleEn: "Transport and communication",
        ideas: [
          "交通效率：智能系统和自动驾驶提高安全与效率",
          "通信便利：现代通信加强个人和社会联系",
          "城乡与环境：连接地区、分配资源，但也可能增加污染和拥堵",
        ],
        logic: ["交通通信技术改善", "人员、信息和资源流动加快", "城乡联系和机会增加", "同时需要控制污染和拥堵"],
        paragraph: "Modern transport and communication can connect people, businesses and rural areas more efficiently. Smart systems may improve safety and access to services, but greener solutions are needed to control traffic congestion and pollution.",
        translation: "现代交通和通信可以更高效地连接个人、企业和农村地区。智能系统可以改善安全和服务可及性，但仍需要更环保的方案来控制交通拥堵和污染。",
        phrases: ["modern transport and communication", "rural areas more efficiently", "smart systems", "improve safety and access to services", "greener solutions", "traffic congestion and pollution"],
      },
      {
        id: "technology-energy",
        sourceOrder: 5,
        title: "能源开发和利用",
        titleEn: "Energy development and use",
        ideas: [
          "能源转型：从化石燃料转向可再生能源",
          "效率和安全：减少浪费，提高能源供应稳定性",
          "发展平衡：同时考虑经济需求和环境保护",
        ],
        logic: ["投资清洁和节能技术", "化石燃料使用减少", "排放和能源浪费下降", "能源供应更加稳定、可持续"],
        paragraph: "Investment in renewable energy and energy-saving technology can reduce emissions and waste. A wider range of energy sources can also improve energy security, but governments must balance environmental protection with economic needs.",
        translation: "投资可再生能源和节能技术可以减少排放与浪费。更多样的能源来源还能提高能源安全，但政府必须平衡环境保护与经济需求。",
        phrases: ["renewable energy and energy-saving technology", "reduce emissions and waste", "a wider range of energy sources", "improve energy security", "balance environmental protection with economic needs"],
        priority: true,
      },
    ],
  },
  {
    id: "education",
    name: "教育",
    nameEn: "Education",
    summary: "对应 PDF 第六部分：教育制度、学习方式、机会、教师和课程。",
    materials: [
      {
        id: "education-systems-policy",
        sourceOrder: 1,
        title: "教育系统和政策",
        titleEn: "Education systems and policies",
        ideas: [
          "教育体系：影响国家经济发展和社会进步",
          "政策与资源：提高质量并公平分配地区和群体间的资源",
          "教育改革：教育制度需要适应新的社会需求",
        ],
        logic: ["政府制定有效教育政策", "资源得到公平分配", "教学质量和机会提高", "社会与经济长期受益"],
        paragraph: "A strong education system supports both economic and social progress. Governments should distribute resources fairly, improve teaching quality and update education policies as the needs of students and society change.",
        translation: "健全的教育体系可以支持经济与社会进步。政府应公平分配资源、提高教学质量，并随着学生和社会需求的变化更新教育政策。",
        phrases: ["a strong education system", "economic and social progress", "distribute resources fairly", "improve teaching quality", "update education policies", "needs of students and society"],
      },
      {
        id: "education-learning-methods",
        sourceOrder: 2,
        title: "学习方式和效果",
        titleEn: "Learning methods and outcomes",
        ideas: [
          "传统与现代方式：课堂、在线学习和自主学习各有作用",
          "影响因素：环境、教学方法和个人习惯决定学习效果",
          "评估反馈：帮助学生发现问题并提高学习表现",
        ],
        logic: ["采用合适的教学和学习方式", "学生获得及时评估与反馈", "学习问题得到纠正", "学习效率和结果提高"],
        paragraph: "Both classroom teaching and online learning can be useful when they suit students' needs. A supportive environment, good study habits and regular feedback help learners understand their progress and improve their results.",
        translation: "只要适合学生的需要，课堂教学和在线学习都可以发挥作用。良好的学习环境、学习习惯和定期反馈能帮助学习者了解自己的进度并提高成绩。",
        phrases: ["classroom teaching and online learning", "suit students' needs", "a supportive environment", "good study habits", "regular feedback", "understand their progress and improve their results"],
      },
      {
        id: "education-equality",
        sourceOrder: 3,
        title: "教育机会和平等",
        titleEn: "Educational opportunity and equality",
        ideas: [
          "教育公平：是社会公平和进步的重要基础",
          "背景差距：收入、地区、性别和种族会影响教育机会",
          "政策干预：资助和资源投入可以缩小差距",
        ],
        logic: ["为不同背景的学生提供平等机会", "更多人获得知识和技能", "就业机会提高", "贫困和社会差距减少"],
        paragraph: "Equal access to education allows students from poor or disadvantaged backgrounds to develop useful skills. Financial support and fair resource distribution can improve their future job opportunities and reduce long-term inequality.",
        translation: "平等的教育机会让贫困或处于不利背景的学生获得实用技能。经济支持和公平的资源分配可以改善他们未来的就业机会，并减少长期不平等。",
        phrases: ["equal access to education", "poor or disadvantaged backgrounds", "develop useful skills", "financial support and fair resource distribution", "future job opportunities", "reduce long-term inequality"],
        priority: true,
      },
      {
        id: "education-teachers",
        sourceOrder: 4,
        title: "教师角色和培训",
        titleEn: "The role and training of teachers",
        ideas: [
          "教师作用：直接影响学生理解和学习效果",
          "专业发展：持续培训可以更新知识和教学方法",
          "教师支持：足够资源有利于教师发展和学生学习",
        ],
        logic: ["教师接受持续培训和支持", "教学知识与方法得到更新", "学生更容易理解课程", "整体教学质量提高"],
        paragraph: "Teachers play a central role in students' learning. Regular professional training and enough classroom resources help teachers improve their methods, explain lessons more clearly and provide better support for different learners.",
        translation: "教师在学生学习中发挥核心作用。定期的专业培训和充足的课堂资源能帮助教师改进方法、更清楚地讲解课程，并为不同学习者提供更好的支持。",
        phrases: ["a central role in students' learning", "professional training", "classroom resources", "improve their methods", "explain lessons more clearly", "provide better support for different learners"],
      },
      {
        id: "education-curriculum",
        sourceOrder: 5,
        title: "教育内容和课程设计",
        titleEn: "Educational content and curriculum design",
        ideas: [
          "课程相关性：与未来职业和社会需要相联系",
          "技能与创新：教授实用技能并培养创造力",
          "多元与终身学习：拓宽国际视野并形成持续学习习惯",
        ],
        logic: ["学校教授相关且实用的课程", "学生练习真实生活和工作技能", "独立性与就业能力提高", "更好地适应未来变化"],
        paragraph: "School subjects should be relevant to students' future lives and careers. A balanced curriculum can teach practical skills, encourage creativity, include different cultures and help students develop the habit of lifelong learning.",
        translation: "学校课程应与学生未来的生活和职业相关。均衡的课程可以教授实用技能、鼓励创造力、包含不同文化，并帮助学生养成终身学习的习惯。",
        phrases: ["relevant to students' future lives and careers", "a balanced curriculum", "teach practical skills", "encourage creativity", "include different cultures", "lifelong learning"],
        priority: true,
      },
    ],
  },
  {
    id: "government",
    name: "政府",
    nameEn: "Government",
    summary: "对应 PDF 第七部分“政治角度”：政府责任、民主、国际关系、政策与法律。",
    materials: [
      {
        id: "government-role-responsibility",
        sourceOrder: 1,
        title: "政府角色和责任",
        titleEn: "Government roles and responsibilities",
        ideas: [
          "公共服务：提供教育、医疗和安全等基本服务",
          "经济与环境：监管经济并执行环境法规",
          "社会福利：支持弱势群体，减少贫困和不平等",
        ],
        logic: ["政府提供基本服务并进行监管", "公众的基本需要得到满足", "危险和机会差距减少", "社会更加安全稳定"],
        paragraph: "Governments are responsible for basic services such as education, health care and public safety. They should also regulate the economy, protect the environment and support vulnerable groups to reduce poverty and inequality.",
        translation: "政府负责教育、医疗和公共安全等基本服务。政府还应监管经济、保护环境并支持弱势群体，以减少贫困和不平等。",
        phrases: ["basic services", "education, health care and public safety", "regulate the economy", "protect the environment", "support vulnerable groups", "reduce poverty and inequality"],
        priority: true,
      },
      {
        id: "government-democracy-participation",
        sourceOrder: 2,
        title: "政治参与和民主",
        titleEn: "Political participation and democracy",
        ideas: [
          "选举代表：公民通过投票选择代表自己利益的人",
          "自由与平等：所有群体都应有表达和参与的机会",
          "透明度：公开决策过程可以增强公众信任",
        ],
        logic: ["公民自由、平等地表达意见", "政府了解不同群体的需要", "决策更加公开且有代表性", "公众信任提高"],
        paragraph: "Democracy works better when citizens can vote, express their opinions and take part equally in public life. Clear and open decision-making also helps people understand government actions and increases public trust.",
        translation: "当公民能够投票、表达意见并平等参与公共生活时，民主会运作得更好。清楚公开的决策过程也有助于人们理解政府行为并提高公众信任。",
        phrases: ["citizens can vote", "express their opinions", "take part equally in public life", "open decision-making", "increases public trust"],
      },
      {
        id: "government-international-relations",
        sourceOrder: 3,
        title: "国际关系和冲突",
        titleEn: "International relations and conflict",
        ideas: [
          "外交与和平：国家政策会影响国际关系和国家利益",
          "国际合作：共同解决恐怖主义、疾病和环境问题",
          "冲突与贸易：军事行动需谨慎，贸易既能促进发展也会引发紧张",
        ],
        logic: ["全球问题跨越国界", "单个国家无法独立解决", "各国分享信息和资源", "解决方案更加有效"],
        paragraph: "Many problems, including disease, terrorism and climate change, cross national borders. International cooperation allows countries to share information and resources, while peaceful diplomacy and trade can reduce conflict and support development.",
        translation: "疾病、恐怖主义和气候变化等许多问题都跨越国界。国际合作让各国共享信息和资源，而和平外交与贸易可以减少冲突并促进发展。",
        phrases: ["cross national borders", "international cooperation", "share information and resources", "peaceful diplomacy", "reduce conflict", "support development"],
      },
      {
        id: "government-policy",
        sourceOrder: 4,
        title: "政策制定和实施",
        titleEn: "Policy design and implementation",
        ideas: [
          "政策制定：平衡不同利益群体的需求和目标",
          "实施挑战：资源不足、公众反对或行政阻力",
          "评估影响：检查社会、经济和环境结果并及时调整",
        ],
        logic: ["政府制定并实施政策", "收集执行后的实际结果", "发现问题与资源浪费", "调整政策并提高效果"],
        paragraph: "Good policy-making considers the needs of different groups and the resources available. After a policy is introduced, governments should measure its social, economic and environmental effects and make changes when problems appear.",
        translation: "良好的政策制定会考虑不同群体的需求和可用资源。政策推出后，政府应衡量其社会、经济和环境影响，并在问题出现时作出调整。",
        phrases: ["good policy-making", "the needs of different groups", "the resources available", "measure its social, economic and environmental effects", "make changes when problems appear"],
      },
      {
        id: "government-law-rights",
        sourceOrder: 5,
        title: "法律和人权",
        titleEn: "Law and human rights",
        ideas: [
          "法治：政府和公民都应遵守法律",
          "人权保护：保障生命、自由和财产权等基本权利",
          "司法与国际标准：公平司法建立信任，各国也应遵守国际承诺",
        ],
        logic: ["法律平等适用于政府和公民", "基本权利得到保护", "司法决定更加公平", "社会秩序与公众信任增强"],
        paragraph: "The rule of law means that both citizens and governments must follow the law. A fair justice system should protect basic human rights, treat people equally and follow widely accepted international standards.",
        translation: "法治意味着公民和政府都必须遵守法律。公平的司法制度应保护基本人权、平等对待每个人，并遵守广泛接受的国际标准。",
        phrases: ["the rule of law", "citizens and governments must follow the law", "a fair justice system", "protect basic human rights", "treat people equally", "international standards"],
      },
    ],
  },
  {
    id: "health",
    name: "健康",
    nameEn: "Health",
    summary: "对应 PDF 第八部分：医疗服务、疾病预防、生活方式、心理健康和公共卫生。",
    materials: [
      {
        id: "health-care-systems",
        sourceOrder: 1,
        title: "医疗保健系统和服务",
        titleEn: "Health-care systems and services",
        ideas: [
          "可及性与质量：所有人都应获得必要且高质量的医疗",
          "资源和技术：公平分配资源，并用技术提高诊疗效率",
          "成本控制：寻找效果好且费用合理的方案",
        ],
        logic: ["提供可负担且容易获得的医疗", "人们能够及时检查和治疗", "疾病不会继续恶化", "健康差距和长期成本下降"],
        paragraph: "A good health-care system should provide affordable and high-quality services to everyone. Fair resource distribution and medical technology can improve treatment, while cost control helps governments keep these services available in the long term.",
        translation: "良好的医疗体系应为所有人提供可负担且高质量的服务。公平的资源分配和医疗技术可以改善治疗，而成本控制能帮助政府长期维持这些服务。",
        phrases: ["a good health-care system", "affordable and high-quality services", "fair resource distribution", "medical technology", "improve treatment", "cost control helps governments keep these services available in the long term"],
      },
      {
        id: "health-disease-prevention",
        sourceOrder: 2,
        title: "疾病预防和控制",
        titleEn: "Disease prevention and control",
        ideas: [
          "疫苗与健康教育：预防传染病和慢性疾病",
          "监测系统：及早发现并应对疾病暴发",
          "国际合作：共同研发药物和疫苗，应对全球疫情",
        ],
        logic: ["开展疫苗接种和健康教育", "更多人避免患病", "疫情和慢性病减少", "医院与家庭的医疗负担下降"],
        paragraph: "Vaccination and health education can prevent many diseases before treatment is needed. Effective monitoring systems and international cooperation also help countries detect outbreaks early and develop medicines more quickly.",
        translation: "疫苗接种和健康教育可以在需要治疗之前预防许多疾病。有效的监测系统和国际合作也能帮助各国及早发现疫情并更快研发药物。",
        phrases: ["vaccination and health education", "prevent many diseases", "effective monitoring systems", "international cooperation", "detect outbreaks early", "develop medicines more quickly"],
      },
      {
        id: "health-lifestyle",
        sourceOrder: 3,
        title: "健康生活方式和习惯",
        titleEn: "Healthy lifestyles and habits",
        ideas: [
          "饮食与运动：保持健康体重并预防疾病",
          "不良习惯：减少吸烟和过量饮酒",
          "工作与环境：保持工作生活平衡，并提供安全运动环境",
        ],
        logic: ["保持均衡饮食、运动和充分休息", "健康体重和压力得到控制", "慢性疾病风险下降", "生活质量和工作表现提高"],
        paragraph: "A balanced diet, regular exercise and enough rest can reduce the risk of disease. People should also avoid smoking and excessive drinking, while safe public spaces and a good work-life balance make healthy choices easier.",
        translation: "均衡饮食、规律运动和充足休息可以降低患病风险。人们还应避免吸烟和过量饮酒，而安全的公共空间和良好的工作生活平衡能让健康选择更容易。",
        phrases: ["a balanced diet, regular exercise and enough rest", "reduce the risk of disease", "avoid smoking and excessive drinking", "safe public spaces", "a good work-life balance", "make healthy choices easier"],
      },
      {
        id: "health-mental-support",
        sourceOrder: 4,
        title: "心理健康和社会支持",
        titleEn: "Mental health and social support",
        ideas: [
          "心理健康意识：减少污名，让人更愿意寻求帮助",
          "社会支持和治疗：帮助人们应对压力并防止问题恶化",
          "职场支持：提高员工心理健康和工作满意度",
        ],
        logic: ["提高心理健康意识并提供支持", "人们更早寻求专业帮助", "问题得到及时处理", "严重后果和工作压力减少"],
        paragraph: "Greater mental-health awareness can reduce stigma and encourage people to seek help early. Support from families, health services and workplaces can help individuals manage stress and prevent minor problems from becoming more serious.",
        translation: "更强的心理健康意识可以减少污名，并鼓励人们及早寻求帮助。来自家庭、医疗服务和工作场所的支持可以帮助个人管理压力，防止较小的问题变得更加严重。",
        phrases: ["mental-health awareness", "reduce stigma", "seek help early", "support from families, health services and workplaces", "manage stress", "prevent minor problems from becoming more serious"],
      },
      {
        id: "health-policy-public-health",
        sourceOrder: 5,
        title: "健康政策和公共卫生",
        titleEn: "Health policy and public health",
        ideas: [
          "循证政策：根据可靠证据改善健康并减少不平等",
          "公共卫生投入：清洁水、卫生设施和疾病预防项目",
          "健康促进与评估：鼓励健康行为并定期检查政策效果",
        ],
        logic: ["政府投资公共卫生设施和预防项目", "环境和健康行为改善", "患病人数减少", "医疗支出和健康差距下降"],
        paragraph: "Public-health investment in clean water, sanitation and prevention programmes can protect whole communities. Governments should use reliable evidence, promote healthy behaviour and regularly evaluate policies to make sure they achieve their goals.",
        translation: "对清洁水、卫生设施和疾病预防项目的公共卫生投资可以保护整个社区。政府应使用可靠证据、促进健康行为，并定期评估政策，以确保实现目标。",
        phrases: ["public-health investment", "clean water, sanitation and prevention programmes", "protect whole communities", "reliable evidence", "promote healthy behaviour", "regularly evaluate policies"],
      },
    ],
  },
];

export const totalTopicCount = categories.reduce(
  (total, category) => total + category.materials.length,
  0,
);
