export type PartThreeItem = { question: string; answer: string };
export type PartThreeGroup = {
  id: string;
  category: string;
  title: string;
  partTwo: string;
  items: PartThreeItem[];
};

export const partThreeGroups: PartThreeGroup[] = [
  {
    id: "helping-others",
    category: "人物类",
    title: "帮助与互助",
    partTwo: "乐于助人的人",
    items: [
      { question: "Should children help their parents with household chores?", answer: "Yes, I think they should. Simple chores such as cleaning their room or washing dishes can teach children responsibility." },
      { question: "What kind of help do people need when looking for a new job?", answer: "People often need help with finding good job information, improving their CV and preparing for interviews. Friends or experienced colleagues can also explain what a company is really like." },
      { question: "Who should people ask for help, colleagues or family members?", answer: "I think it depends on the problem. For work-related issues, colleagues are usually more helpful because they have related experience." },
      { question: "Why do you think some people are more willing to help others than some?", answer: "Some people are naturally kind and feel happy when they are useful to others. Their family or education may also have taught them to share and work together." },
      { question: "Do you think it is important for neighbors to help each other? Why?", answer: "Yes, especially when someone is old, ill or facing an emergency. Neighbours live close by, so they can often provide help faster than relatives who live far away." },
      { question: "How can helping others benefit the person who offers the help?", answer: "Helping others can give people a sense of achievement and make them feel connected to their community. They may also learn new skills or build stronger relationships." },
    ],
  },
  {
    id: "protecting-nature",
    category: "人物类",
    title: "自然与环保",
    partTwo: "鼓励你保护自然的人",
    items: [
      { question: "How can parents teach their children to protect nature?", answer: "Parents should explain environmental ideas through daily actions. For example, they can teach children to sort rubbish, save water and avoid wasting food." },
      { question: "Should schools teach children to get close to nature?", answer: "Yes, because children may not care about something they have never experienced. Schools can organise visits to parks, farms or nature centres." },
      { question: "Do you think there should be laws to protect nature?", answer: "Yes, laws are necessary because education alone cannot stop every person or company from damaging the environment. Governments can limit pollution and punish illegal activities." },
      { question: "Besides laws, what else can the government do to protect the environment?", answer: "The government can improve public transport, provide recycling facilities and support clean energy. It can also run public campaigns and teach environmental topics in schools." },
      { question: "Why do some people not care about environmental protection?", answer: "Some people think environmental problems are too distant and do not affect their daily lives. Others care more about convenience or money." },
      { question: "Do you think individuals can make a real difference in protecting nature? Why?", answer: "Yes, but individual action works best when many people take part. One person using less plastic has a small effect, but millions of people can change demand and influence companies." },
    ],
  },
  {
    id: "smart-problem-solving",
    category: "人物类",
    title: "聪明与解决问题",
    partTwo: "机智解决问题的人",
    items: [
      { question: "Do you think children are born smart or they learn to become smart?", answer: "I think both natural ability and learning are important. Some children understand ideas quickly, but practice, education and curiosity can greatly improve their ability." },
      { question: "How do children become smart at school?", answer: "They become smarter by learning basic knowledge, practising skills and discussing ideas with teachers and classmates. Schools should encourage children to ask why instead of only memorising answers." },
      { question: "Why are some people well-rounded and others only good at one thing?", answer: "People have different interests, opportunities and ways of learning. Some enjoy trying many activities, while others spend most of their time developing one talent." },
      { question: "Why does modern society need talents of all kinds?", answer: "Modern society has many different problems, so one type of talent is not enough. Engineers build technology, doctors protect health and artists support culture." },
      { question: "In your opinion, what is more important in solving problems, intelligence or experience?", answer: "I think experience is usually more important for practical problems because experienced people notice common causes and avoid old mistakes. Intelligence helps when the situation is completely new." },
      { question: "Can you give an example of how technology helps people solve problems in a smart way today?", answer: "Navigation apps are a simple example. They collect traffic information and suggest a faster route, saving drivers time. At work, software can also find unusual system activity before a serious failure happens." },
    ],
  },
  {
    id: "planning",
    category: "人物类",
    title: "计划与职业选择",
    partTwo: "常做计划的人",
    items: [
      { question: "Do you think it's important to plan ahead?", answer: "Yes, planning helps people organise their time and prepare for possible problems. For example, a work plan can make duties and deadlines clear." },
      { question: "Do you think children should plan their future careers?", answer: "Older children can start thinking about careers, but they do not need to make a final decision too early. Their interests and abilities may change as they grow." },
      { question: "Should children ask their teachers or parents for advice when making plans?", answer: "They should ask both. Teachers understand education and may know which subjects match a child's strengths, while parents know the child's personality and family situation." },
      { question: "What activities do we need to plan ahead?", answer: "Important activities involving time, money or other people usually need planning. Examples include travel, major work projects, exams and family events." },
      { question: "Is making study plans popular among young people?", answer: "It is quite common, especially before important exams. Many students use calendars or study apps to divide subjects into smaller tasks." },
      { question: "Do you think choosing a college major is closely related to a person's future career?", answer: "Yes, in fields such as medicine or engineering, a related major is often necessary. However, many graduates later work in a different area because skills like communication and problem-solving can be transferred." },
    ],
  },
  {
    id: "drawing-and-art",
    category: "人物类",
    title: "儿童画画与艺术",
    partTwo: "喜欢画画的孩子",
    items: [
      { question: "What is the right age for a child to learn drawing?", answer: "Children can start drawing as soon as they can safely hold a pencil, perhaps at three or four years old. At that age, the goal should be enjoyment rather than technical skill." },
      { question: "Why do most children draw more often than adults do?", answer: "Children have more free time and are less worried about whether their drawings look professional. Drawing is also an easy way for them to express ideas before their language skills are fully developed." },
      { question: "Why do some people visit galleries or museums instead of viewing artworks online?", answer: "Seeing the original artwork gives people a clearer idea of its real size, colour and texture. Museums also provide a quiet atmosphere and useful background information." },
      { question: "Do you think galleries and museums should be free of charge?", answer: "Basic public museums should be free or inexpensive so families and students can visit regularly. However, special exhibitions may need a reasonable ticket price because displaying and protecting valuable objects costs money." },
      { question: "How do artworks inspire people?", answer: "Art can introduce people to a different way of seeing ordinary life. A painting may encourage someone to notice colours, emotions or social problems they usually ignore." },
      { question: "In your opinion, should drawing be a compulsory subject in primary school? Why or why not?", answer: "Yes, at primary level it can develop creativity, observation and hand control. The subject should remain enjoyable and should not create too much exam pressure." },
    ],
  },
  {
    id: "fame",
    category: "人物类",
    title: "名人与社交媒体",
    partTwo: "想见的名人",
    items: [
      { question: "What are the advantages and disadvantages of being a famous child?", answer: "A famous child may receive special opportunities, good training and money. However, public attention can create pressure and reduce privacy." },
      { question: "What can today's children do to become famous?", answer: "Some children become known through sport, music, acting or online videos. Social media makes it easier to reach a large audience, but becoming famous should not be the only goal." },
      { question: "What can children do with their fame?", answer: "They can use it to support charities, encourage positive behaviour or introduce useful ideas to other young people. They may also build a future career." },
      { question: "Do people become famous because of their talent?", answer: "Talent is one important reason, especially in music, sport and acting. However, timing, marketing, personal connections and luck also matter." },
      { question: "Why are some people more interested in the private lives of celebrities?", answer: "People are curious about lives that seem richer or more exciting than their own. Celebrity news also provides easy conversation and entertainment." },
      { question: "Do you think the definition of “fame” has changed in the age of social media? How?", answer: "Yes. In the past, famous people were usually actors, singers or athletes known through television. Now an ordinary person can gain millions of followers online very quickly." },
    ],
  },
  {
    id: "pride",
    category: "人物类",
    title: "家庭、奖励与自豪",
    partTwo: "让你骄傲的家人",
    items: [
      { question: "What would children do to make their parents proud?", answer: "Children can make parents proud by working hard, behaving responsibly and treating other people kindly. Good exam results may be one example, but character is also important." },
      { question: "What did you do to make your parents proud when you were young?", answer: "I think my parents were proud when I studied hard and entered university. I also learned to manage my own life and did not cause them many serious problems." },
      { question: "What advantages of yours make you proud?", answer: "I am proud that I can stay patient when I face a difficult problem. This is useful in my work as a software engineer because solutions sometimes take a long time." },
      { question: "When was the last time that you felt proud of yourself?", answer: "I recently felt proud after finishing a difficult project at work. The task had several problems, but I communicated with my teammates and completed it successfully." },
      { question: "Should parents reward children? Why and how?", answer: "Reasonable rewards can encourage effort and good habits. They do not always need to be money or expensive gifts; praise, extra playtime or a family activity can work well." },
      { question: "On what occasions would adults be proud of themselves?", answer: "Adults may feel proud after reaching a career goal, supporting their family or overcoming a personal difficulty. Some are also proud when they help another person." },
    ],
  },
  {
    id: "lifelong-learning",
    category: "人物类",
    title: "自学与终身学习",
    partTwo: "自学的朋友",
    items: [
      { question: "Is it necessary to keep learning after graduating from school?", answer: "Yes, because technology and workplaces continue to change. Adults may need new skills to remain useful or find better jobs." },
      { question: "Should teachers make learning in their classes fun?", answer: "Yes, an interesting class helps students pay attention and remember information. Teachers can use examples, discussions and simple activities." },
      { question: "Do you think there are too many subjects for students to learn?", answer: "In some schools, students may have too many subjects and too much homework. A broad education is useful, but there should be enough time to understand important ideas properly." },
      { question: "Is it better to focus on a few subjects or to learn many subjects?", answer: "Younger students should learn many basic subjects so they can discover their interests and understand the world. Older students can gradually focus on fewer areas related to their future." },
      { question: "Do you think enterprises should provide training for their employees?", answer: "Yes, because training helps employees use new tools and work more safely and quickly. It also shows that the company values their development." },
      { question: "Do you think it is good for older adults to continue learning?", answer: "Yes. Learning can keep their minds active, give them confidence and help them use modern services. They might learn a language, a musical instrument or basic smartphone skills." },
    ],
  },
  {
    id: "encouragement",
    category: "事件类",
    title: "鼓励与说服",
    partTwo: "鼓励别人做不愿做的事",
    items: [
      { question: "How can leaders encourage their employees?", answer: "Leaders should set clear goals, notice good work and give employees useful feedback. They can also provide training and allow people some freedom in how they complete a task." },
      { question: "When should parents encourage their children?", answer: "Parents should encourage children when they are learning something difficult, facing failure or trying a healthy new activity. Support is especially important when children make an effort but do not succeed quickly." },
      { question: "What kind of encouragement should parents give?", answer: "They should praise specific effort, such as practising regularly or helping a classmate, instead of only saying a child is smart. Practical support and patient listening are also useful." },
      { question: "Do you think some people are better than others at persuading?", answer: "Yes. Good persuaders usually listen carefully, understand the other person's concerns and explain benefits clearly. They also choose the right time and tone." },
      { question: "What is the difference between encouraging someone and pressuring someone?", answer: "Encouragement gives support and respects the person's final choice, while pressure makes them feel that they cannot refuse. Encouragement focuses on confidence and possible benefits." },
      { question: "In your opinion, is it always good to encourage people to try new things? Why?", answer: "Not always. Trying new things can build confidence and skills, but the activity must be safe and suitable. People should not be pushed into serious financial risks or situations that make them extremely uncomfortable." },
    ],
  },
  {
    id: "imagination",
    category: "事件类",
    title: "想象力与创造力",
    partTwo: "发挥想象力",
    items: [
      { question: "Do you think adults can have lots of imagination?", answer: "Yes. Adults use imagination when they design products, solve unusual problems or plan for the future." },
      { question: "Do you think imagination is essential for scientists?", answer: "Yes, because scientists need to think of explanations and experiments that nobody has tried before. Knowledge and evidence are still necessary, but imagination helps them ask new questions." },
      { question: "What kinds of jobs need imagination?", answer: "Artists, writers, designers and advertising workers clearly need imagination. Engineers, teachers and business owners also use it to solve problems and explain ideas in new ways." },
      { question: "What subjects are helpful for children's imagination?", answer: "Art, music and literature are especially helpful because they allow children to create and interpret ideas. Science can also develop imagination through experiments and questions about how the world works." },
      { question: "Why do you think some children seem to have more imagination than others?", answer: "Children have different personalities and interests, but their environment also matters. Those who read stories, play freely and receive encouragement may express more ideas." },
      { question: "Do you think modern technology (like TV and smartphones) helps or hurts people‘s imagination?", answer: "It can do both. Technology gives people access to stories, images and creative tools, which can inspire new ideas. However, endless passive entertainment may reduce time for thinking and creating." },
    ],
  },
  {
    id: "transport",
    category: "事件类",
    title: "交通、骑行与污染",
    partTwo: "自行车／摩托车／汽车旅行",
    items: [
      { question: "Which form of vehicle is more popular in your country, bikes, cars or motorcycles?", answer: "Cars are probably the most popular for families because they are comfortable and useful for longer trips. Shared bicycles are also common in large cities for short journeys." },
      { question: "Do you think air pollution comes mostly from mobile vehicles?", answer: "Vehicles are an important source, especially in crowded cities, but they are not the only one. Factories, construction and energy production also create pollution." },
      { question: "Do you think people need to change the way of transportation drastically to protect the environment?", answer: "A sudden complete change would be difficult, but people can gradually drive less and use public transport for suitable journeys. Governments should make buses, underground systems and cycling safer first." },
      { question: "How are the transportation systems in urban areas and rural areas different?", answer: "Cities usually have more buses, underground lines and shared bicycles because many people travel short distances. Rural areas have fewer services and longer distances, so residents depend more on private cars." },
      { question: "What are the benefits of travelling by bicycle compared to by car?", answer: "Cycling produces no direct pollution, costs less and gives people exercise. It can also be faster than driving for short trips in crowded areas." },
      { question: "Do you think the government should encourage people to use bicycles? How?", answer: "Yes. The government can build protected cycling paths, provide safe parking and connect bike routes to bus or underground stations." },
    ],
  },
  {
    id: "advice",
    category: "事件类",
    title: "建议与判断",
    partTwo: "给别人建议",
    items: [
      { question: "Should people prepare before giving advice?", answer: "Yes, especially when the decision involves health, money or a career. People should understand the situation and check good information before speaking confidently." },
      { question: "Is it good to ask advice from strangers online?", answer: "Online advice can provide different experiences and useful starting points, but strangers may not understand the full situation. Some information may also be wrong." },
      { question: "What are the personalities of people whose job is to give advice to others?", answer: "They should be patient, responsible and good at listening. They also need to explain complex information clearly without judging the client." },
      { question: "What are the problems if you ask too many people for advice?", answer: "Different people may give opposite suggestions, which can make the decision more confusing. Some advice may reflect their own interests rather than yours." },
      { question: "When is it not appropriate to give advice to others?", answer: "It may be not suitable when nobody has asked and the issue is very personal. People should also avoid giving professional advice without knowledge." },
      { question: "Which do you think is more helpful: advice from older people or advice from friends of the same age? Why?", answer: "Older people often have more life experience, while friends of the same age may understand current pressures better. For a major career or financial decision, experience can be valuable." },
    ],
  },
  {
    id: "music-events",
    category: "事件类",
    title: "音乐与公共活动",
    partTwo: "不喜欢的音乐活动",
    items: [
      { question: "Do you think everyone has the same taste in music? Why/Why not?", answer: "No. Musical taste is influenced by age, culture, personality and personal memories. Young people may enjoy new pop music, while older people may prefer songs from their youth." },
      { question: "What kind of music is suitable for big public events, like sports games or celebrations?", answer: "Upbeat, familiar music usually works well because it creates energy and many people can enjoy it. The volume should not be painfully loud, and organisers should consider the audience." },
      { question: "How important is music in creating the atmosphere at a social event?", answer: "Music is quite important because it affects people's mood and fills uncomfortable silence. Fast music can make a celebration lively, while soft music suits a meal or conversation." },
      { question: "Do you think older people and younger people enjoy the same kind of music at events? What are the differences?", answer: "There is some overlap, but younger people often prefer current pop or electronic music, while older people may enjoy familiar older songs. At mixed-age events, organisers can play several styles." },
      { question: "How has technology (like streaming apps) changed the way people listen to music at parties or events?", answer: "Streaming apps give organisers access to huge music libraries and ready-made playlists. Guests can also request a song instantly." },
      { question: "Do you think live music at events will be replaced by recorded music in the future? Why or why not?", answer: "Recorded music will remain more common because it is cheaper and easier to organise. However, live music will not disappear because performers create interaction and a special atmosphere." },
    ],
  },
  {
    id: "buildings",
    category: "地点类",
    title: "建筑设计与保护",
    partTwo: "有趣的建筑",
    items: [
      { question: "What types of buildings are popular in your country?", answer: "Modern apartment buildings are common in cities because they can house many people on limited land. Shopping centres and office towers are also popular." },
      { question: "Is it worth spending a lot of money on the exterior appearance of a building?", answer: "For important public or cultural buildings, an attractive exterior can improve the city and create a landmark. However, safety, function and energy use should come first." },
      { question: "Is it more important for a building to look good on the outside or on the inside?", answer: "The inside is usually more important because people use it every day and need a safe, comfortable space. The exterior still matters because it affects the surrounding area." },
      { question: "Why do people like to visit historical sites?", answer: "Historical sites allow people to see real places connected with the past. They can understand architecture, culture and important events more clearly than by only reading a book." },
      { question: "What are the challenges in preserving old or historical buildings?", answer: "Repairs can be expensive, and old materials may be difficult to replace. Cities also need space for modern housing and transport, so development creates pressure." },
      { question: "Do you think modern buildings will become as culturally valuable as ancient ones in the future?", answer: "Some will, especially buildings that represent an important period or new design idea. However, not every modern office tower will become valuable." },
    ],
  },
  {
    id: "shopping-malls",
    category: "地点类",
    title: "商场与购物方式",
    partTwo: "商场",
    items: [
      { question: "Why do people buy things they don't need?", answer: "Advertising, discounts and social pressure can make unnecessary products feel attractive. Shopping also gives some people short-term excitement when they are bored or stressed." },
      { question: "Do you think shopping malls are popular in your country? Why?", answer: "Yes, especially in cities. Malls combine shops, restaurants, cinemas and children's activities in one comfortable place. They are useful in very hot, cold or rainy weather." },
      { question: "What are the advantages of shopping in a mall compared to shopping online?", answer: "Customers can see, touch and try products before paying, which is especially useful for clothes or expensive items. They can also receive the product quickly." },
      { question: "Do young people and old people like to go to the same kind of malls? Why?", answer: "Not always. Young people may prefer modern malls with fashionable shops, cinemas and cafés, while older people may care more about supermarkets, seating and easy transport." },
      { question: "How can a shopping mall attract more customers?", answer: "It needs a good location, useful shops, clean facilities and convenient parking or public transport. Events, restaurants and entertainment can encourage people to stay longer." },
      { question: "Do you think having many malls in a city is a good thing?", answer: "Some competition gives customers more choice and can improve service. Malls also create jobs and indoor public spaces. However, too many similar malls may waste land, increase traffic and harm small local shops." },
    ],
  },
  {
    id: "foreign-stay",
    category: "地点类",
    title: "国外短期生活",
    partTwo: "外国的短期停留",
    items: [
      { question: "Why do people sometimes go to other cities or other countries to travel?", answer: "People travel to relax, experience different cultures and escape their usual routine. Some also visit friends, study or look for business opportunities." },
      { question: "What are the benefits of living in a foreign country for a short time?", answer: "People can practise a language, understand another culture and become more independent. A short stay also gives them international work or study experience without requiring a permanent move." },
      { question: "What problems might people have when they stay in a foreign country?", answer: "Language difficulties, unfamiliar food and different rules can create stress. People may also feel lonely or have trouble finding housing and healthcare." },
      { question: "Is it better to travel alone or with friends when visiting another country? Why?", answer: "Travelling with friends can feel safer, reduce costs and provide someone to share memories with. Travelling alone gives more freedom and encourages independence." },
      { question: "How can people prepare before going to stay in a foreign country?", answer: "They should check visa rules, insurance, accommodation, transport and local costs. Learning a few basic phrases and understanding important cultural rules is also helpful." },
      { question: "Do you think short-term visits can help people understand a different culture?", answer: "Yes, visitors can observe daily behaviour, food, transport and communication directly. However, a short stay only provides a limited view, especially if someone remains in tourist areas." },
    ],
  },
  {
    id: "smiling",
    category: "地点类",
    title: "微笑与情绪",
    partTwo: "微笑的场合",
    items: [
      { question: "Do you think people who like to smile are more friendly?", answer: "They often appear more friendly because a smile makes other people feel welcome. However, personality cannot be judged from one expression." },
      { question: "Why do most people smile in photographs?", answer: "People want photographs to record a happy or attractive moment. Smiling also makes a group photo look more positive and helps everyone appear relaxed." },
      { question: "Do women smile more than men? Why?", answer: "In some cultures, women may be encouraged to appear warm and friendly, so they might smile more in public. Men may be taught to look serious." },
      { question: "Do people smile more when they are younger or older?", answer: "Children may smile more openly because they worry less about how they look and react quickly to simple fun. Adults face more duties, but older people may also smile often when spending time with family." },
      { question: "In what situations is it inappropriate to smile?", answer: "Smiling can be not suitable during a serious accident, funeral or conversation about someone else's pain. It may make people think the situation is not being respected." },
      { question: "Do you think smiling can actually make people feel happier? Why?", answer: "Yes, smiling may slightly improve a person's mood and can encourage a positive response from others. If someone smiles, people may speak to them more warmly." },
    ],
  },
  {
    id: "mobile-phones",
    category: "地点类",
    title: "手机使用与限制",
    partTwo: "禁用手机的场合",
    items: [
      { question: "How do young and old people use mobile phones differently?", answer: "Young people often use phones for social media, games, videos and online study. Older people may focus more on calls, messages, news and practical services." },
      { question: "What positive and negative impact do mobile phones have on friendship?", answer: "Phones make it easy to stay in contact with friends who live far away and organise activities quickly. However, constant messages can reduce face-to-face attention, and online misunderstandings are common." },
      { question: "Is it a waste of time to take pictures with mobile phones?", answer: "Not necessarily. Photos help people record important moments and share useful information. It becomes a waste of time when someone takes hundreds of similar pictures or focuses on posting instead of enjoying the experience." },
      { question: "Do you think it is necessary to have laws on the use of mobile phones?", answer: "Some rules are necessary for safety and privacy, such as banning phone use while driving or taking secret photographs. However, governments should not control ordinary personal use too much." },
      { question: "Why do you think some people feel anxious when they cannot use their phones?", answer: "Phones provide messages, entertainment, work information and payment, so people may feel disconnected without them. Checking can also become a strong habit." },
      { question: "Can you suggest some effective ways to help people reduce their screen time?", answer: "People can set daily limits, remove unnecessary notifications and keep phones away from the bed. Replacing screen time with a specific activity, such as walking or reading, is also helpful." },
    ],
  },
  {
    id: "relaxation",
    category: "地点类",
    title: "放松、运动与家庭空间",
    partTwo: "家里放松的地方",
    items: [
      { question: "Why is it difficult for some people to relax?", answer: "Some people have heavy workloads, family duties or financial worries. Even after work, messages and phones keep their minds active." },
      { question: "What are the benefits of doing exercise?", answer: "Exercise improves physical health, strengthens the body and can reduce stress. It may also help people sleep better and meet others through group activities." },
      { question: "Do people in your country exercise after work?", answer: "Many do, especially younger office workers who go to gyms, run or walk in parks. However, overtime and long travel times make regular exercise difficult for others." },
      { question: "What is the place where people spend most of their time at home?", answer: "Many people spend most of their free time in the living room because they can watch television, talk and relax there. Younger people may spend more time in their bedrooms using computers." },
      { question: "Do you think there should be classes for training young people and children how to relax?", answer: "Schools could teach simple stress-management skills, such as breathing, exercise and healthy time planning. These lessons may help students during exams." },
      { question: "Which is more important, mental relaxation or physical relaxation?", answer: "Both are connected. Physical rest is necessary after hard work or exercise, while mental relaxation helps people handle stress and sleep." },
    ],
  },
  {
    id: "overspending",
    category: "事物类",
    title: "消费、广告与储蓄",
    partTwo: "花费超过预期的物品",
    items: [
      { question: "Do you often buy more than you expected?", answer: "Not very often, because I usually make a list and compare prices. However, discounts sometimes encourage me to add small things to an order." },
      { question: "What do you think young people spend most of their money on?", answer: "Many spend money on housing, food, transport, phones, entertainment and travel. In large cities, rent can take the biggest share." },
      { question: "Do you think it is important to save money? Why?", answer: "Yes. Savings help people handle emergencies, unemployment or major future plans without quickly borrowing money. Even a small regular amount can create security." },
      { question: "Do people buy things they don't need?", answer: "Yes, because advertisements, trends and low prices can make products seem necessary. Some people also shop when they are bored or stressed." },
      { question: "How do advertisements influence people’s spending habits?", answer: "Advertisements connect products with happiness, success or attractiveness, which can create emotional demand. Online platforms also show personalised adverts repeatedly." },
      { question: "What can people do to avoid overspending?", answer: "They can set a monthly budget, use a shopping list and compare prices before paying. Waiting one or two days before a non-important buy reduces impulse buying." },
    ],
  },
  {
    id: "successful-movies",
    category: "事物类",
    title: "电影成功因素",
    partTwo: "近期观影",
    items: [
      { question: "What kinds of movies do you think are successful in your country?", answer: "Comedies, action films and stories about family life often attract large audiences. Recently, good animated and science-fiction films have also become popular." },
      { question: "What are the factors that make a successful movie?", answer: "A clear story, believable characters and good acting are basic factors. Music, visual quality and marketing also matter." },
      { question: "Do Chinese people prefer to watch domestic movies or foreign movies?", answer: "Many people watch both. Domestic films are easier to connect with because of language, humour and familiar social issues. Foreign films offer different styles and larger productions." },
      { question: "Do you think only well-known directors can create the best movies?", answer: "No. Experienced directors may have more resources and professional teams, but new directors can bring fresh ideas. Some excellent films are made with small budgets." },
      { question: "Do you think successful movies should have well-known actors or actresses in leading roles?", answer: "Famous actors can attract attention and may have strong skills, but they are not important. A less famous actor who suits the character can be more believable." },
      { question: "Why do people prefer to watch movies in the cinema?", answer: "Cinemas offer a large screen, powerful sound and fewer daily interruptions. Watching with an audience can also make comedy or action more exciting." },
    ],
  },
  {
    id: "family-objects",
    category: "事物类",
    title: "家庭物品与博物馆",
    partTwo: "对家庭重要的东西",
    items: [
      { question: "What things do families keep for a long time?", answer: "Families often keep photographs, letters, jewellery, books and objects connected with important events. These items may not be expensive, but they carry personal memories." },
      { question: "What's the difference between things valued by people in the past and today?", answer: "In the past, durable household objects and handwritten letters were often valuable because products were harder to replace. Today, people may value phones, digital photographs and branded items." },
      { question: "What kinds of things are kept in museums?", answer: "Museums keep historical objects, artworks, documents, clothing, tools and scientific examples. The collection depends on the museum's purpose." },
      { question: "What's the influence of technology on museums?", answer: "Technology allows museums to create interactive displays, digital guides and virtual visits. It also helps experts record and protect collections." },
      { question: "Why is it important for people (especially children) to learn about family history?", answer: "Family history helps children understand where they come from and how older generations lived. It can create respect and a sense of identity." },
      { question: "Do you think people will keep fewer physical objects in the future as memories? Why?", answer: "Probably, because photographs, messages and documents are increasingly stored digitally. Small homes also reduce storage space." },
    ],
  },
  {
    id: "stories",
    category: "事物类",
    title: "故事、电影与价值观",
    partTwo: "最近读过的故事",
    items: [
      { question: "Why do most children like listening to stories before bedtime?", answer: "Stories help children relax, use their imagination and spend close time with their parents. A regular story can also become part of a healthy bedtime routine." },
      { question: "Is a good storyline important for a movie?", answer: "Yes, because the storyline gives meaning to the acting, images and music. Without a clear or interesting story, viewers may lose attention even if the film looks beautiful." },
      { question: "Do you think films with many celebrities are more likely to be popular?", answer: "They are more likely to receive attention at first because fans notice the actors. However, too many famous people cannot guarantee quality." },
      { question: "What films are popular in China right now?", answer: "Comedies, action movies, animation and stories about ordinary family life are generally popular. Large holiday periods often bring successful domestic films." },
      { question: "Do you think traditional stories (like fairy tales) are still relevant for children today?", answer: "Yes. Traditional stories discuss courage, kindness, greed and responsibility, which are still related. Adults may need to explain old-fashioned ideas or frightening parts." },
      { question: "How can stories influence a person‘s character or values?", answer: "Stories allow people to experience choices and consequences through characters. A child may learn empathy by seeing a situation from another person's view." },
    ],
  },
  {
    id: "apps",
    category: "事物类",
    title: "App与数字生活",
    partTwo: "App／程序",
    items: [
      { question: "What are the differences between old and young people when using apps?", answer: "Young people often explore new social, shopping and entertainment apps quickly. Older users may prefer a smaller number of practical apps and need clearer instructions." },
      { question: "Why do some people not like using apps?", answer: "They may worry about privacy, complicated menus, advertisements or spending too much time online. Some apps require frequent updates and permissions." },
      { question: "What kinds of apps are most popular among young people in your country?", answer: "Social media, short-video, messaging, shopping, music and game apps are very popular. Young people also use study, food-delivery and transport apps." },
      { question: "Do you think mobile apps have made our lives easier or more complicated?", answer: "Overall, they have made many tasks easier, such as payment, navigation and booking tickets. However, too many apps, passwords, notifications and privacy settings can create new problems." },
      { question: "What should people pay attention to when downloading a new app?", answer: "They should check the developer, reviews, permissions and privacy policy. An app should not request access that is unrelated to its purpose." },
      { question: "Do you think we will use more or fewer apps in the future? Why?", answer: "We may use more digital services but fewer separate apps. Large platforms and smart helpants could combine payment, travel and communication functions." },
    ],
  },
  {
    id: "important-things",
    category: "事物类",
    title: "物品、儿童与购买行为",
    partTwo: "生活中离不开的东西",
    items: [
      { question: "Why are children attracted to new things (such as electronics)?", answer: "New things provide surprise, bright colours and new ways to play. Children are naturally curious and may also copy friends or online influencers." },
      { question: "Why do some grown-ups hate to throw out old things (such as clothes)?", answer: "Old things may carry memories or still seem useful, so throwing them away feels wasteful. Some adults grew up when products were less available." },
      { question: "Is the way people buy things affected? How?", answer: "Yes, technology, advertising, income and social trends strongly affect shopping. Online stores allow people to compare and buy at any time, while personalised adverts create demand." },
      { question: "What do you think influences people to buy new things?", answer: "Need, price, quality and advertising are major influences. Friends, famous people and online reviews can also affect a decision." },
      { question: "Why do all children like toys?", answer: "Most children like toys because they provide fun, imagination and a way to practise real-life roles. Toys can also help them play with others and develop physical skills." },
      { question: "Do you think it is good for a child to always take his or her favourite toy with them all the time?", answer: "A familiar toy can make a young child feel safe in a new place. However, always depending on it may create problems at school or during travel." },
    ],
  },
  {
    id: "ideal-work",
    category: "事物类",
    title: "理想工作与职业满意度",
    partTwo: "完美工作",
    items: [
      { question: "What jobs do children want to do when they grow up?", answer: "Many children choose familiar or exciting jobs, such as doctors, teachers, athletes, pilots or online creators. Their choices are influenced by family, media and school." },
      { question: "What should people consider when choosing jobs?", answer: "They should consider their interests, skills, salary, working hours, location and opportunities to grow. Job security and team culture also matter." },
      { question: "Is salary the main reason people choose a certain job?", answer: "Salary is important because people need to support themselves and their families. However, working hours, interest, stability and relationships also affect future." },
      { question: "How have people’s opinions about the “perfect job” changed compared to the past?", answer: "In the past, many people valued stability and staying with one company. Today, younger workers may care more about flexibility, personal growth and work-life balance." },
      { question: "Do you think it’s easy for people to find their ideal job? Why or why not?", answer: "No, because competition, location and economic conditions limit choices. People may also have unrealistic expectations before gaining work experience." },
      { question: "What is more important for job satisfaction: a high salary or good relationships with colleagues?", answer: "Both matter, but good relationships may be more important after basic financial needs are met. People spend many hours with colleagues, so conflict creates daily stress." },
    ],
  },
  {
    id: "disappointing-films",
    category: "事物类",
    title: "电影评价与演员",
    partTwo: "让你失望的电影",
    items: [
      { question: "Do you believe movie reviews?", answer: "I use reviews as a reference but do not believe every opinion. Professional critics may notice technical quality, while ordinary viewers may focus on entertainment." },
      { question: "What are the different types of films in your country?", answer: "There are comedies, action films, historical dramas, romance, animation, science fiction and documentaries. Domestic films increasingly cover both large national stories and ordinary family life." },
      { question: "Are historical films popular in your country? Why?", answer: "Yes, some are popular because Chinese history offers many famous events and characters. These films can be educational and visually impressive." },
      { question: "Do you think films with famous actors or actresses are more likely to become successful films?", answer: "They are more likely to receive attention and strong promotion, but success is not certain. Famous actors cannot repair a confusing story." },
      { question: "Why are Japanese animated films so popular?", answer: "Many have detailed artwork, emotional stories and themes that both children and adults can understand. They cover more than simple comedy and often create memorable characters." },
      { question: "Should the director pay a lot of money to famous actors?", answer: "It may be worthwhile if the actor fits the role and helps attract enough viewers. However, spending too much on one star can reduce money for writing, visual effects and other actors." },
    ],
  },
];
