export type PartThreeItem = { question: string; answer: string };
export type PartThreeGroup = {
  id: string;
  category: string;
  title: string;
  partTwo: string;
  items: PartThreeItem[];
};

export const partThreeGroups: PartThreeGroup[] = [
  {
    id: "helping-others",
    category: "人物类",
    title: "帮助与互助",
    partTwo: "乐于助人的人",
    items: [
      { question: "Should children help their parents with household chores?", answer: "Yes, I think they should. Simple chores such as cleaning their room or washing dishes can teach children responsibility. However, parents should choose tasks that are suitable for the child's age and should not give them so much housework that it affects their studies." },
      { question: "What kind of help do people need when looking for a new job?", answer: "People often need help with finding reliable job information, improving their CV and preparing for interviews. Friends or experienced colleagues can also explain what a company is really like. This kind of practical advice can save time and help applicants avoid unsuitable jobs." },
      { question: "Who should people ask for help, colleagues or family members?", answer: "I think it depends on the problem. For work-related issues, colleagues are usually more helpful because they have relevant experience. For personal or emotional problems, family members may be better because they understand us well and normally care about our long-term happiness." },
      { question: "Why do you think some people are more willing to help others than some?", answer: "Some people are naturally kind and feel happy when they are useful to others. Their family or education may also have taught them to share and cooperate. In contrast, people who are very busy or have had bad experiences may be more careful about offering help." },
      { question: "Do you think it is important for neighbors to help each other? Why?", answer: "Yes, especially when someone is old, ill or facing an emergency. Neighbours live close by, so they can often provide help faster than relatives who live far away. Small actions, such as collecting a parcel, can also create trust and make the community friendlier." },
      { question: "How can helping others benefit the person who offers the help?", answer: "Helping others can give people a sense of achievement and make them feel connected to their community. They may also learn new skills or build stronger relationships. In the future, the person they helped may be willing to support them when they face a problem." },
    ],
  },
  {
    id: "protecting-nature",
    category: "人物类",
    title: "自然与环保",
    partTwo: "鼓励你保护自然的人",
    items: [
      { question: "How can parents teach their children to protect nature?", answer: "Parents should explain environmental ideas through daily actions. For example, they can teach children to sort rubbish, save water and avoid wasting food. Taking children to parks and cleaning up after a picnic can be more effective than only telling them that pollution is bad." },
      { question: "Should schools teach children to get close to nature?", answer: "Yes, because children may not care about something they have never experienced. Schools can organise visits to parks, farms or nature centres. These activities help children understand plants and animals, although schools must also consider safety and the cost of outdoor trips." },
      { question: "Do you think there should be laws to protect nature?", answer: "Yes, laws are necessary because education alone cannot stop every person or company from damaging the environment. Governments can limit pollution and punish illegal activities. However, the rules need to be clear and properly enforced, or they will not make a real difference." },
      { question: "Besides laws, what else can the government do to protect the environment?", answer: "The government can improve public transport, provide recycling facilities and support clean energy. It can also run public campaigns and teach environmental topics in schools. Making environmentally friendly choices convenient is important because many people will not change if the alternative is too difficult or expensive." },
      { question: "Why do some people not care about environmental protection?", answer: "Some people think environmental problems are too distant and do not affect their daily lives. Others care more about convenience or money. For example, they may continue using a car because public transport is poor. Better information and practical alternatives can help change these attitudes." },
      { question: "Do you think individuals can make a real difference in protecting nature? Why?", answer: "Yes, but individual action works best when many people take part. One person using less plastic has a small effect, but millions of people can change demand and influence companies. Individuals can also vote, support environmental policies and encourage their families to develop better habits." },
    ],
  },
  {
    id: "smart-problem-solving",
    category: "人物类",
    title: "聪明与解决问题",
    partTwo: "机智解决问题的人",
    items: [
      { question: "Do you think children are born smart or they learn to become smart?", answer: "I think both natural ability and learning are important. Some children understand ideas quickly, but practice, education and curiosity can greatly improve their ability. A child who works steadily and asks questions may eventually perform better than someone talented who makes little effort." },
      { question: "How do children become smart at school?", answer: "They become smarter by learning basic knowledge, practising skills and discussing ideas with teachers and classmates. Schools should encourage children to ask why instead of only memorising answers. Solving different kinds of problems also teaches them how to use knowledge in real situations." },
      { question: "Why are some people well-rounded and others only good at one thing?", answer: "People have different interests, opportunities and ways of learning. Some enjoy trying many activities, while others spend most of their time developing one talent. Being well-rounded is useful in daily life, but specialising can also be valuable in fields that require deep knowledge." },
      { question: "Why does modern society need talents of all kinds?", answer: "Modern society has many different problems, so one type of talent is not enough. Engineers build technology, doctors protect health and artists support culture. These people also need to cooperate. A successful project often depends on technical, creative and communication skills working together." },
      { question: "In your opinion, what is more important in solving problems, intelligence or experience?", answer: "I think experience is usually more important for practical problems because experienced people recognise common causes and avoid old mistakes. Intelligence helps when the situation is completely new. Ideally, people should combine clear thinking with lessons learned from previous work." },
      { question: "Can you give an example of how technology helps people solve problems in a smart way today?", answer: "Navigation apps are a simple example. They collect traffic information and suggest a faster route, saving drivers time. At work, software can also find unusual system activity before a serious failure happens. Technology is useful because it processes information faster than people can." },
    ],
  },
  {
    id: "planning",
    category: "人物类",
    title: "计划与职业选择",
    partTwo: "常做计划的人",
    items: [
      { question: "Do you think it's important to plan ahead?", answer: "Yes, planning helps people organise their time and prepare for possible problems. For example, a work plan can make responsibilities and deadlines clear. However, plans should not be too strict because unexpected changes happen, and people sometimes need to adjust their priorities." },
      { question: "Do you think children should plan their future careers?", answer: "Older children can start thinking about careers, but they do not need to make a final decision too early. Their interests and abilities may change as they grow. It is better to explore several subjects and understand different jobs before choosing one direction." },
      { question: "Should children ask their teachers or parents for advice when making plans?", answer: "They should ask both. Teachers understand education and may know which subjects match a child's strengths, while parents know the child's personality and family situation. However, adults should provide information rather than make every decision, because the child will live with the result." },
      { question: "What activities do we need to plan ahead?", answer: "Important activities involving time, money or other people usually need planning. Examples include travel, major work projects, exams and family events. A simple plan helps people book resources, share responsibilities and avoid last-minute stress, although small daily activities can remain flexible." },
      { question: "Is making study plans popular among young people?", answer: "It is quite common, especially before important exams. Many students use calendars or study apps to divide subjects into smaller tasks. However, making a plan is easier than following it. Young people need realistic goals and enough rest, otherwise they may give up quickly." },
      { question: "Do you think choosing a college major is closely related to a person's future career?", answer: "Yes, in fields such as medicine or engineering, a relevant major is often necessary. However, many graduates later work in a different area because skills like communication and problem-solving can be transferred. A major influences a career, but it does not decide a person's whole future." },
    ],
  },
  {
    id: "drawing-and-art",
    category: "人物类",
    title: "儿童画画与艺术",
    partTwo: "喜欢画画的孩子",
    items: [
      { question: "What is the right age for a child to learn drawing?", answer: "Children can start drawing as soon as they can safely hold a pencil, perhaps at three or four years old. At that age, the goal should be enjoyment rather than technical skill. Formal lessons can come later if the child remains interested." },
      { question: "Why do most children draw more often than adults do?", answer: "Children have more free time and are less worried about whether their drawings look professional. Drawing is also an easy way for them to express ideas before their language skills are fully developed. Adults often become busy and may feel embarrassed about making imperfect pictures." },
      { question: "Why do some people visit galleries or museums instead of viewing artworks online?", answer: "Seeing the original artwork gives people a clearer idea of its real size, colour and texture. Museums also provide a quiet atmosphere and useful background information. Online images are convenient, but a phone screen cannot fully reproduce the experience of standing in front of an artwork." },
      { question: "Do you think galleries and museums should be free of charge?", answer: "Basic public museums should be free or inexpensive so families and students can visit regularly. However, special exhibitions may need a reasonable ticket price because displaying and protecting valuable objects costs money. Governments could also offer free days each month." },
      { question: "How do artworks inspire people?", answer: "Art can introduce people to a different way of seeing ordinary life. A painting may encourage someone to notice colours, emotions or social problems they usually ignore. It can also give creative workers new ideas, although different viewers may understand the same artwork differently." },
      { question: "In your opinion, should drawing be a compulsory subject in primary school? Why or why not?", answer: "Yes, at primary level it can develop creativity, observation and hand control. The subject should remain enjoyable and should not create too much exam pressure. Children who are not talented at drawing can still learn to express an idea through pictures." },
    ],
  },
  {
    id: "fame",
    category: "人物类",
    title: "名人与社交媒体",
    partTwo: "想见的名人",
    items: [
      { question: "What are the advantages and disadvantages of being a famous child?", answer: "A famous child may receive special opportunities, professional training and financial rewards. However, public attention can create pressure and reduce privacy. Children may also find it difficult to know whether people like them personally or only because they are famous." },
      { question: "What can today's children do to become famous?", answer: "Some children become known through sport, music, acting or online videos. Social media makes it easier to reach a large audience, but becoming famous should not be the only goal. Children still need education, safety and adults who protect them from unhealthy attention." },
      { question: "What can children do with their fame?", answer: "They can use it to support charities, encourage positive behaviour or introduce useful ideas to other young people. They may also build a future career. However, adults should manage commercial activities carefully so fame does not damage the child's education or mental health." },
      { question: "Do people become famous because of their talent?", answer: "Talent is one important reason, especially in music, sport and acting. However, timing, marketing, personal connections and luck also matter. Today, some people become famous because a short video becomes popular, even if they do not have a traditional professional skill." },
      { question: "Why are some people more interested in the private lives of celebrities?", answer: "People are curious about lives that seem richer or more exciting than their own. Celebrity news also provides easy conversation and entertainment. However, this interest can become unhealthy when the public forgets that famous people still deserve personal space and respect." },
      { question: "Do you think the definition of “fame” has changed in the age of social media? How?", answer: "Yes. In the past, famous people were usually actors, singers or athletes known through television. Now an ordinary person can gain millions of followers online very quickly. Modern fame can be more direct but also less stable because attention moves to new people fast." },
    ],
  },
  {
    id: "pride",
    category: "人物类",
    title: "家庭、奖励与自豪",
    partTwo: "让你骄傲的家人",
    items: [
      { question: "What would children do to make their parents proud?", answer: "Children can make parents proud by working hard, behaving responsibly and treating other people kindly. Good exam results may be one example, but character is also important. Many parents are proud when their children become independent and continue trying after a failure." },
      { question: "What did you do to make your parents proud when you were young?", answer: "I think my parents were proud when I studied hard and entered university. I also learned to manage my own life and did not cause them many serious problems. For my parents, steady progress and responsible behaviour were probably more important than winning prizes." },
      { question: "What advantages of yours make you proud?", answer: "I am proud that I can stay patient when I face a difficult problem. This is useful in my work as a software engineer because solutions sometimes take a long time. I am also willing to learn from mistakes instead of hiding them." },
      { question: "When was the last time that you felt proud of yourself?", answer: "I recently felt proud after finishing a difficult project at work. The task had several problems, but I communicated with my teammates and completed it successfully. I was not perfect, but I handled the pressure better than I would have a few years ago." },
      { question: "Should parents reward children? Why and how?", answer: "Reasonable rewards can encourage effort and good habits. They do not always need to be money or expensive gifts; praise, extra playtime or a family activity can work well. Parents should reward the process, not only high scores, or children may become afraid of failure." },
      { question: "On what occasions would adults be proud of themselves?", answer: "Adults may feel proud after reaching a career goal, supporting their family or overcoming a personal difficulty. Some are also proud when they help another person. The feeling is usually strongest when success requires steady effort rather than good luck." },
    ],
  },
  {
    id: "lifelong-learning",
    category: "人物类",
    title: "自学与终身学习",
    partTwo: "自学的朋友",
    items: [
      { question: "Is it necessary to keep learning after graduating from school?", answer: "Yes, because technology and workplaces continue to change. Adults may need new skills to remain effective or find better jobs. Learning is also useful outside work, because activities such as languages or music can keep life interesting and help people meet others." },
      { question: "Should teachers make learning in their classes fun?", answer: "Yes, an interesting class helps students pay attention and remember information. Teachers can use examples, discussions and simple activities. However, fun should support the learning goal rather than replace it, because students still need to practise difficult skills and develop discipline." },
      { question: "Do you think there are too many subjects for students to learn?", answer: "In some schools, students may have too many subjects and too much homework. A broad education is useful, but there should be enough time to understand important ideas properly. Schools could reduce repeated content and give students more choice as they get older." },
      { question: "Is it better to focus on a few subjects or to learn many subjects?", answer: "Younger students should learn many basic subjects so they can discover their interests and understand the world. Older students can gradually focus on fewer areas related to their future. The best approach is broad learning first and more specialisation later." },
      { question: "Do you think enterprises should provide training for their employees?", answer: "Yes, because training helps employees use new tools and work more safely and efficiently. It also shows that the company values their development. However, the training should be practical and connected to real tasks, not just a formal meeting that wastes time." },
      { question: "Do you think it is good for older adults to continue learning?", answer: "Yes. Learning can keep their minds active, give them confidence and help them use modern services. They might learn a language, a musical instrument or basic smartphone skills. Courses should move at a comfortable speed and avoid making older learners feel embarrassed." },
    ],
  },
  {
    id: "encouragement",
    category: "事件类",
    title: "鼓励与说服",
    partTwo: "鼓励别人做不愿做的事",
    items: [
      { question: "How can leaders encourage their employees?", answer: "Leaders should set clear goals, recognise good work and give employees useful feedback. They can also provide training and allow people some freedom in how they complete a task. Encouragement is more effective when rewards are fair and employees understand why their work matters." },
      { question: "When should parents encourage their children?", answer: "Parents should encourage children when they are learning something difficult, facing failure or trying a healthy new activity. Support is especially important when children make an effort but do not succeed immediately. However, parents should also allow them to rest or change an unsuitable goal." },
      { question: "What kind of encouragement should parents give?", answer: "They should praise specific effort, such as practising regularly or helping a classmate, instead of only saying a child is smart. Practical support and patient listening are also useful. Small rewards can help, but children should not expect money for every positive action." },
      { question: "Do you think some people are better than others at persuading?", answer: "Yes. Good persuaders usually listen carefully, understand the other person's concerns and explain benefits clearly. They also choose the right time and tone. People who only talk about themselves or use pressure may get short-term agreement but damage trust." },
      { question: "What is the difference between encouraging someone and pressuring someone?", answer: "Encouragement gives support and respects the person's final choice, while pressure makes them feel that they cannot refuse. Encouragement focuses on confidence and possible benefits. Pressure often uses fear, guilt or punishment, so it can create stress and damage relationships." },
      { question: "In your opinion, is it always good to encourage people to try new things? Why?", answer: "Not always. Trying new things can build confidence and skills, but the activity must be safe and suitable. People should not be pushed into serious financial risks or situations that make them extremely uncomfortable. Good encouragement includes honest information and respect for their decision." },
    ],
  },
  {
    id: "imagination",
    category: "事件类",
    title: "想象力与创造力",
    partTwo: "发挥想象力",
    items: [
      { question: "Do you think adults can have lots of imagination?", answer: "Yes. Adults use imagination when they design products, solve unusual problems or plan for the future. They may show it less openly than children because work and responsibilities make them more practical, but imagination can grow through reading, travel and creative hobbies." },
      { question: "Do you think imagination is essential for scientists?", answer: "Yes, because scientists need to think of explanations and experiments that nobody has tried before. Knowledge and evidence are still necessary, but imagination helps them ask new questions. Many useful inventions began with someone imagining a different way to solve an old problem." },
      { question: "What kinds of jobs need imagination?", answer: "Artists, writers, designers and advertising workers clearly need imagination. Engineers, teachers and business owners also use it to solve problems and explain ideas in new ways. Even ordinary office jobs sometimes require creative thinking when the usual method does not work." },
      { question: "What subjects are helpful for children's imagination?", answer: "Art, music and literature are especially helpful because they allow children to create and interpret ideas. Science can also develop imagination through experiments and questions about how the world works. The teaching method matters because memorising facts alone does not encourage much creativity." },
      { question: "Why do you think some children seem to have more imagination than others?", answer: "Children have different personalities and interests, but their environment also matters. Those who read stories, play freely and receive encouragement may express more ideas. Children who are often corrected or given fixed answers may become afraid of saying something unusual." },
      { question: "Do you think modern technology (like TV and smartphones) helps or hurts people‘s imagination?", answer: "It can do both. Technology gives people access to stories, images and creative tools, which can inspire new ideas. However, endless passive entertainment may reduce time for thinking and creating. The effect depends on whether people use technology actively or only consume content." },
    ],
  },
  {
    id: "transport",
    category: "事件类",
    title: "交通、骑行与污染",
    partTwo: "自行车／摩托车／汽车旅行",
    items: [
      { question: "Which form of vehicle is more popular in your country, bikes, cars or motorcycles?", answer: "Cars are probably the most popular for families because they are comfortable and useful for longer trips. Shared bicycles are also common in large cities for short journeys. Motorcycles are less popular in some urban areas because local rules may limit their use." },
      { question: "Do you think air pollution comes mostly from mobile vehicles?", answer: "Vehicles are an important source, especially in crowded cities, but they are not the only one. Factories, construction and energy production also create pollution. Governments need to improve transport while also controlling industrial emissions and supporting cleaner energy." },
      { question: "Do you think people need to change the way of transportation drastically to protect the environment?", answer: "A sudden complete change would be difficult, but people can gradually drive less and use public transport for suitable journeys. Governments should make buses, underground systems and cycling safer first. People are more likely to change when green transport is convenient and affordable." },
      { question: "How are the transportation systems in urban areas and rural areas different?", answer: "Cities usually have more buses, underground lines and shared bicycles because many people travel short distances. Rural areas have fewer services and longer distances, so residents depend more on private cars. Improving regular bus connections would help people without cars." },
      { question: "What are the benefits of travelling by bicycle compared to by car?", answer: "Cycling produces no direct pollution, costs less and gives people exercise. It can also be faster than driving for short trips in crowded areas. However, bicycles are less practical in bad weather, for long distances or when people need to carry heavy things." },
      { question: "Do you think the government should encourage people to use bicycles? How?", answer: "Yes. The government can build protected cycling paths, provide safe parking and connect bike routes to bus or underground stations. Public campaigns may help, but safe infrastructure is more important. People will not cycle regularly if they feel at risk in traffic." },
    ],
  },
  {
    id: "advice",
    category: "事件类",
    title: "建议与判断",
    partTwo: "给别人建议",
    items: [
      { question: "Should people prepare before giving advice?", answer: "Yes, especially when the decision involves health, money or a career. People should understand the situation and check reliable information before speaking confidently. If they are unsure, it is better to say so or recommend a professional instead of guessing." },
      { question: "Is it good to ask advice from strangers online?", answer: "Online advice can provide different experiences and useful starting points, but strangers may not understand the full situation. Some information may also be wrong. People should compare several reliable sources and avoid sharing private details, especially for medical or financial problems." },
      { question: "What are the personalities of people whose job is to give advice to others?", answer: "They should be patient, responsible and good at listening. They also need to explain complex information clearly without judging the client. Confidence is useful, but they must be honest about uncertainty and understand that different people may need different solutions." },
      { question: "What are the problems if you ask too many people for advice?", answer: "Different people may give opposite suggestions, which can make the decision more confusing. Some advice may reflect their own interests rather than yours. It is better to choose a few trustworthy people, understand their reasons and then make your own decision." },
      { question: "When is it not appropriate to give advice to others?", answer: "It may be inappropriate when nobody has asked and the issue is very personal. People should also avoid giving professional advice without knowledge. If someone only needs emotional support, listening may be more helpful than immediately telling them what to do." },
      { question: "Which do you think is more helpful: advice from older people or advice from friends of the same age? Why?", answer: "Older people often have more life experience, while friends of the same age may understand current pressures better. For a major career or financial decision, experience can be valuable. For everyday social problems, a friend may offer more relevant advice. It depends on the topic." },
    ],
  },
  {
    id: "music-events",
    category: "事件类",
    title: "音乐与公共活动",
    partTwo: "不喜欢的音乐活动",
    items: [
      { question: "Do you think everyone has the same taste in music? Why/Why not?", answer: "No. Musical taste is influenced by age, culture, personality and personal memories. Young people may enjoy new pop music, while older people may prefer songs from their youth. Even close friends can like completely different styles, which is normal." },
      { question: "What kind of music is suitable for big public events, like sports games or celebrations?", answer: "Upbeat, familiar music usually works well because it creates energy and many people can enjoy it. The volume should not be painfully loud, and organisers should consider the audience. Traditional music may also be suitable for national or cultural celebrations." },
      { question: "How important is music in creating the atmosphere at a social event?", answer: "Music is quite important because it affects people's mood and fills uncomfortable silence. Fast music can make a celebration lively, while soft music suits a meal or conversation. However, good music cannot fix poor organisation, and it should not make communication difficult." },
      { question: "Do you think older people and younger people enjoy the same kind of music at events? What are the differences?", answer: "There is some overlap, but younger people often prefer current pop or electronic music, while older people may enjoy familiar older songs. At mixed-age events, organisers can play several styles. Volume is also important because older guests may prefer quieter music." },
      { question: "How has technology (like streaming apps) changed the way people listen to music at parties or events?", answer: "Streaming apps give organisers access to huge music libraries and ready-made playlists. Guests can also request a song instantly. This is convenient and inexpensive, although relying on automatic playlists may make events feel less personal than having a skilled DJ or live band." },
      { question: "Do you think live music at events will be replaced by recorded music in the future? Why or why not?", answer: "Recorded music will remain more common because it is cheaper and easier to organise. However, live music will not disappear because performers create interaction and a special atmosphere. Important weddings, festivals and concerts will still pay for live musicians when the experience matters." },
    ],
  },
  {
    id: "buildings",
    category: "地点类",
    title: "建筑设计与保护",
    partTwo: "有趣的建筑",
    items: [
      { question: "What types of buildings are popular in your country?", answer: "Modern apartment buildings are common in cities because they can house many people on limited land. Shopping centres and office towers are also popular. At the same time, many people still enjoy traditional buildings because they represent local history and culture." },
      { question: "Is it worth spending a lot of money on the exterior appearance of a building?", answer: "For important public or cultural buildings, an attractive exterior can improve the city and create a landmark. However, safety, function and energy use should come first. Spending too much on decoration while ignoring practical needs would not be responsible." },
      { question: "Is it more important for a building to look good on the outside or on the inside?", answer: "The inside is usually more important because people use it every day and need a safe, comfortable space. The exterior still matters because it affects the surrounding area. Ideally, a good building should be practical inside and suitable for its location outside." },
      { question: "Why do people like to visit historical sites?", answer: "Historical sites allow people to see real places connected with the past. They can understand architecture, culture and important events more clearly than by only reading a book. These sites also provide attractive places for photography and help local tourism." },
      { question: "What are the challenges in preserving old or historical buildings?", answer: "Repairs can be expensive, and old materials may be difficult to replace. Cities also need space for modern housing and transport, so development creates pressure. Governments must balance safety and new needs with protecting the building's original character." },
      { question: "Do you think modern buildings will become as culturally valuable as ancient ones in the future?", answer: "Some will, especially buildings that represent an important period or new design idea. However, not every modern office tower will become valuable. Time, historical events and public meaning will decide which buildings future generations choose to protect." },
    ],
  },
  {
    id: "shopping-malls",
    category: "地点类",
    title: "商场与购物方式",
    partTwo: "商场",
    items: [
      { question: "Why do people buy things they don't need?", answer: "Advertising, discounts and social pressure can make unnecessary products feel attractive. Shopping also gives some people short-term excitement when they are bored or stressed. Online payment makes spending easy, so people may buy before considering whether they will really use the item." },
      { question: "Do you think shopping malls are popular in your country? Why?", answer: "Yes, especially in cities. Malls combine shops, restaurants, cinemas and children's activities in one comfortable place. They are useful in very hot, cold or rainy weather. However, online shopping has reduced the need to visit malls only to buy ordinary products." },
      { question: "What are the advantages of shopping in a mall compared to shopping online?", answer: "Customers can see, touch and try products before paying, which is especially useful for clothes or expensive items. They can also receive the product immediately. Online shopping is more convenient, but photos and reviews do not always show the real quality." },
      { question: "Do young people and old people like to go to the same kind of malls? Why?", answer: "Not always. Young people may prefer modern malls with fashionable shops, cinemas and cafés, while older people may care more about supermarkets, seating and easy transport. A well-designed mall can serve both groups by offering different facilities and clear signs." },
      { question: "How can a shopping mall attract more customers?", answer: "It needs a good location, useful shops, clean facilities and convenient parking or public transport. Events, restaurants and entertainment can encourage people to stay longer. However, prices and service remain important because attractive decoration alone will not create loyal customers." },
      { question: "Do you think having many malls in a city is a good thing?", answer: "Some competition gives customers more choice and can improve service. Malls also create jobs and indoor public spaces. However, too many similar malls may waste land, increase traffic and harm small local shops. City planners should consider whether each area really needs another one." },
    ],
  },
  {
    id: "foreign-stay",
    category: "地点类",
    title: "国外短期生活",
    partTwo: "外国的短期停留",
    items: [
      { question: "Why do people sometimes go to other cities or other countries to travel?", answer: "People travel to relax, experience different cultures and escape their usual routine. Some also visit friends, study or look for business opportunities. Seeing a place in person can teach people more than photographs, although travel requires time and money." },
      { question: "What are the benefits of living in a foreign country for a short time?", answer: "People can practise a language, understand another culture and become more independent. A short stay also gives them international work or study experience without requiring a permanent move. It can make them more confident when dealing with unfamiliar situations." },
      { question: "What problems might people have when they stay in a foreign country?", answer: "Language difficulties, unfamiliar food and different rules can create stress. People may also feel lonely or have trouble finding housing and healthcare. Good preparation helps, but it normally takes time to understand how daily life works in a new country." },
      { question: "Is it better to travel alone or with friends when visiting another country? Why?", answer: "Travelling with friends can feel safer, reduce costs and provide someone to share memories with. Travelling alone gives more freedom and encourages independence. For a first visit to a very unfamiliar country, I would prefer going with one or two reliable friends." },
      { question: "How can people prepare before going to stay in a foreign country?", answer: "They should check visa rules, insurance, accommodation, transport and local costs. Learning a few basic phrases and understanding important cultural rules is also helpful. They should keep copies of documents and know how to contact emergency services or their embassy." },
      { question: "Do you think short-term visits can help people understand a different culture?", answer: "Yes, visitors can observe daily behaviour, food, transport and communication directly. However, a short stay only provides a limited view, especially if someone remains in tourist areas. Talking with local people and joining ordinary activities can create a deeper understanding." },
    ],
  },
  {
    id: "smiling",
    category: "地点类",
    title: "微笑与情绪",
    partTwo: "微笑的场合",
    items: [
      { question: "Do you think people who like to smile are more friendly?", answer: "They often appear more friendly because a smile makes other people feel welcome. However, personality cannot be judged from one expression. Some kind people are naturally quiet, while others may smile politely even when they do not want a close conversation." },
      { question: "Why do most people smile in photographs?", answer: "People want photographs to record a happy or attractive moment. Smiling also makes a group photo look more positive and helps everyone appear relaxed. It has become a social habit, although serious expressions may be more suitable for official documents or artistic photos." },
      { question: "Do women smile more than men? Why?", answer: "In some cultures, women may be encouraged to appear warm and friendly, so they might smile more in public. Men may be taught to look serious. However, this depends more on personality and situation than gender, and social expectations are gradually changing." },
      { question: "Do people smile more when they are younger or older?", answer: "Children may smile more openly because they worry less about how they look and react quickly to simple fun. Adults face more responsibilities, but older people may also smile often when spending time with family. Age is only one factor." },
      { question: "In what situations is it inappropriate to smile?", answer: "Smiling can be inappropriate during a serious accident, funeral or conversation about someone else's pain. It may make people think the situation is not being respected. However, a gentle supportive smile can sometimes comfort someone, so context and intention are important." },
      { question: "Do you think smiling can actually make people feel happier? Why?", answer: "Yes, smiling may slightly improve a person's mood and can encourage a positive response from others. If someone smiles, people may speak to them more warmly. However, it cannot solve serious sadness, and people should not be forced to hide real emotions." },
    ],
  },
  {
    id: "mobile-phones",
    category: "地点类",
    title: "手机使用与限制",
    partTwo: "禁用手机的场合",
    items: [
      { question: "How do young and old people use mobile phones differently?", answer: "Young people often use phones for social media, games, videos and online study. Older people may focus more on calls, messages, news and practical services. The difference is becoming smaller as more older adults learn mobile payment and video calling." },
      { question: "What positive and negative impact do mobile phones have on friendship?", answer: "Phones make it easy to stay in contact with friends who live far away and organise activities quickly. However, constant messages can reduce face-to-face attention, and online misunderstandings are common. Phones support friendship best when they do not replace real conversation." },
      { question: "Is it a waste of time to take pictures with mobile phones?", answer: "Not necessarily. Photos help people record important moments and share useful information. It becomes a waste of time when someone takes hundreds of similar pictures or focuses on posting instead of enjoying the experience. A few meaningful photos are usually enough." },
      { question: "Do you think it is necessary to have laws on the use of mobile phones?", answer: "Some rules are necessary for safety and privacy, such as banning phone use while driving or taking secret photographs. However, governments should not control ordinary personal use too much. Schools and workplaces can create their own reasonable rules for specific situations." },
      { question: "Why do you think some people feel anxious when they cannot use their phones?", answer: "Phones provide messages, entertainment, work information and payment, so people may feel disconnected without them. Checking can also become a strong habit. If someone always expects new information, even a short period without the phone may feel uncomfortable." },
      { question: "Can you suggest some effective ways to help people reduce their screen time?", answer: "People can set daily limits, remove unnecessary notifications and keep phones away from the bed. Replacing screen time with a specific activity, such as walking or reading, is also helpful. Small realistic changes are normally easier to maintain than suddenly deleting everything." },
    ],
  },
  {
    id: "relaxation",
    category: "地点类",
    title: "放松、运动与家庭空间",
    partTwo: "家里放松的地方",
    items: [
      { question: "Why is it difficult for some people to relax?", answer: "Some people have heavy workloads, family responsibilities or financial worries. Even after work, messages and phones keep their minds active. Others feel guilty when they are not being productive. Regular rest and clear boundaries between work and personal time can help." },
      { question: "What are the benefits of doing exercise?", answer: "Exercise improves physical health, strengthens the body and can reduce stress. It may also help people sleep better and meet others through group activities. People do not need intense training; regular walking, cycling or simple home exercise can still provide benefits." },
      { question: "Do people in your country exercise after work?", answer: "Many do, especially younger office workers who go to gyms, run or walk in parks. However, overtime and long travel times make regular exercise difficult for others. Convenient facilities near homes and workplaces can make after-work exercise more realistic." },
      { question: "What is the place where people spend most of their time at home?", answer: "Many people spend most of their free time in the living room because they can watch television, talk and relax there. Younger people may spend more time in their bedrooms using computers. The answer depends on the size and layout of the home." },
      { question: "Do you think there should be classes for training young people and children how to relax?", answer: "Schools could teach simple stress-management skills, such as breathing, exercise and healthy time planning. These lessons may help students during exams. However, relaxation should not become another difficult subject with tests; it should be practical, short and enjoyable." },
      { question: "Which is more important, mental relaxation or physical relaxation?", answer: "Both are connected. Physical rest is necessary after hard work or exercise, while mental relaxation helps people handle stress and sleep. For office workers who sit all day, light physical activity may actually relax the mind better than simply lying down." },
    ],
  },
  {
    id: "overspending",
    category: "事物类",
    title: "消费、广告与储蓄",
    partTwo: "花费超过预期的物品",
    items: [
      { question: "Do you often buy more than you expected?", answer: "Not very often, because I usually make a list and compare prices. However, discounts sometimes encourage me to add small things to an order. Online shopping makes this easy, so I try to wait before buying anything that was not planned." },
      { question: "What do you think young people spend most of their money on?", answer: "Many spend money on housing, food, transport, phones, entertainment and travel. In large cities, rent can take the biggest share. Some young people also pay for online services or hobbies, although spending habits differ according to income and family support." },
      { question: "Do you think it is important to save money? Why?", answer: "Yes. Savings help people handle emergencies, unemployment or major future plans without immediately borrowing money. Even a small regular amount can create security. However, people should still spend reasonably on health, education and experiences instead of saving every possible yuan." },
      { question: "Do people buy things they don't need?", answer: "Yes, because advertisements, trends and low prices can make products seem necessary. Some people also shop when they are bored or stressed. Before buying, it helps to ask how often the item will be used and whether something similar is already owned." },
      { question: "How do advertisements influence people’s spending habits?", answer: "Advertisements connect products with happiness, success or attractiveness, which can create emotional demand. Online platforms also show personalised adverts repeatedly. Advertising provides useful information, but consumers should compare products and remember that the company mainly wants to increase sales." },
      { question: "What can people do to avoid overspending?", answer: "They can set a monthly budget, use a shopping list and compare prices before paying. Waiting one or two days before a non-essential purchase reduces impulse buying. Turning off shopping notifications and avoiding saved payment details can also make spending more deliberate." },
    ],
  },
  {
    id: "successful-movies",
    category: "事物类",
    title: "电影成功因素",
    partTwo: "近期观影",
    items: [
      { question: "What kinds of movies do you think are successful in your country?", answer: "Comedies, action films and stories about family life often attract large audiences. Recently, good animated and science-fiction films have also become popular. Success depends on the story, promotion and timing, not only the type of movie." },
      { question: "What are the factors that make a successful movie?", answer: "A clear story, believable characters and good acting are basic factors. Music, visual quality and marketing also matter. Famous actors may attract the first audience, but positive comments and emotional connection are usually more important for long-term success." },
      { question: "Do Chinese people prefer to watch domestic movies or foreign movies?", answer: "Many people watch both. Domestic films are easier to connect with because of language, humour and familiar social issues. Foreign films offer different styles and larger productions. Preference often depends on the individual movie rather than where it was made." },
      { question: "Do you think only well-known directors can create the best movies?", answer: "No. Experienced directors may have more resources and professional teams, but new directors can bring fresh ideas. Some excellent films are made with small budgets. Audiences mainly care about the final story and experience, although a famous name helps promotion." },
      { question: "Do you think successful movies should have well-known actors or actresses in leading roles?", answer: "Famous actors can attract attention and may have strong skills, but they are not essential. A less famous actor who suits the character can be more believable. A weak story will not become good simply because an expensive star appears in it." },
      { question: "Why do people prefer to watch movies in the cinema?", answer: "Cinemas offer a large screen, powerful sound and fewer daily interruptions. Watching with an audience can also make comedy or action more exciting. However, home viewing is cheaper and more comfortable, so people may reserve cinemas for visually impressive films." },
    ],
  },
  {
    id: "family-objects",
    category: "事物类",
    title: "家庭物品与博物馆",
    partTwo: "对家庭重要的东西",
    items: [
      { question: "What things do families keep for a long time?", answer: "Families often keep photographs, letters, jewellery, books and objects connected with important events. These items may not be expensive, but they carry personal memories. Some families also preserve practical things, such as traditional recipes or tools passed down by older relatives." },
      { question: "What's the difference between things valued by people in the past and today?", answer: "In the past, durable household objects and handwritten letters were often valuable because products were harder to replace. Today, people may value phones, digital photographs and branded items. However, objects connected with family memories remain important in both periods." },
      { question: "What kinds of things are kept in museums?", answer: "Museums keep historical objects, artworks, documents, clothing, tools and scientific examples. The collection depends on the museum's purpose. Items are normally preserved because they help explain a culture, an important event or how people lived in another period." },
      { question: "What's the influence of technology on museums?", answer: "Technology allows museums to create interactive displays, digital guides and virtual visits. It also helps experts record and protect collections. However, screens should support real objects rather than replace everything, because many visitors value seeing an original item in person." },
      { question: "Why is it important for people (especially children) to learn about family history?", answer: "Family history helps children understand where they come from and how older generations lived. It can create respect and a sense of identity. However, families should present history honestly and avoid putting pressure on children to copy every traditional choice." },
      { question: "Do you think people will keep fewer physical objects in the future as memories? Why?", answer: "Probably, because photographs, messages and documents are increasingly stored digitally. Small homes also reduce storage space. However, people will still keep a few meaningful physical objects because touching an old book or piece of jewellery feels different from viewing a file." },
    ],
  },
  {
    id: "stories",
    category: "事物类",
    title: "故事、电影与价值观",
    partTwo: "最近读过的故事",
    items: [
      { question: "Why do most children like listening to stories before bedtime?", answer: "Stories help children relax, use their imagination and spend close time with their parents. A regular story can also become part of a healthy bedtime routine. Children enjoy following characters and hearing a familiar voice before they sleep." },
      { question: "Is a good storyline important for a movie?", answer: "Yes, because the storyline gives meaning to the acting, images and music. Without a clear or interesting story, viewers may lose attention even if the film looks beautiful. Some action films use simple plots, but the events still need to feel connected." },
      { question: "Do you think films with many celebrities are more likely to be popular?", answer: "They are more likely to receive attention at first because fans recognise the actors. However, too many celebrities cannot guarantee quality. If the story is weak or the characters are poorly written, audiences may still feel disappointed and give negative reviews." },
      { question: "What films are popular in China right now?", answer: "Comedies, action movies, animation and stories about ordinary family life are generally popular. Large holiday periods often bring successful domestic films. Popularity changes quickly, so good promotion and positive online discussion can strongly influence what people choose." },
      { question: "Do you think traditional stories (like fairy tales) are still relevant for children today?", answer: "Yes. Traditional stories discuss courage, kindness, greed and responsibility, which are still relevant. Adults may need to explain old-fashioned ideas or frightening parts. New versions can keep the main lesson while using language and situations modern children understand." },
      { question: "How can stories influence a person‘s character or values?", answer: "Stories allow people to experience choices and consequences through characters. A child may learn empathy by seeing a situation from another person's view. However, one story rarely changes someone completely; repeated messages from family, school and media have a stronger influence." },
    ],
  },
  {
    id: "apps",
    category: "事物类",
    title: "App与数字生活",
    partTwo: "App／程序",
    items: [
      { question: "What are the differences between old and young people when using apps?", answer: "Young people often explore new social, shopping and entertainment apps quickly. Older users may prefer a smaller number of practical apps and need clearer instructions. However, many older adults now use payment, transport and video-call apps confidently." },
      { question: "Why do some people not like using apps?", answer: "They may worry about privacy, complicated menus, advertisements or spending too much time online. Some apps require frequent updates and permissions. People may also prefer speaking to a real person when dealing with important services or difficult problems." },
      { question: "What kinds of apps are most popular among young people in your country?", answer: "Social media, short-video, messaging, shopping, music and game apps are very popular. Young people also use study, food-delivery and transport apps. Convenience is important, but entertainment apps probably take the largest amount of their screen time." },
      { question: "Do you think mobile apps have made our lives easier or more complicated?", answer: "Overall, they have made many tasks easier, such as payment, navigation and booking tickets. However, too many apps, passwords, notifications and privacy settings can create new problems. People need to choose useful apps instead of installing everything available." },
      { question: "What should people pay attention to when downloading a new app?", answer: "They should check the developer, reviews, permissions and privacy policy. An app should not request access that is unrelated to its purpose. People should also consider hidden payments, advertisements and whether the same function already exists on their phone." },
      { question: "Do you think we will use more or fewer apps in the future? Why?", answer: "We may use more digital services but fewer separate apps. Large platforms and smart assistants could combine payment, travel and communication functions. People are becoming tired of managing many accounts, so simpler services that work together may become more attractive." },
    ],
  },
  {
    id: "important-things",
    category: "事物类",
    title: "物品、儿童与购买行为",
    partTwo: "生活中离不开的东西",
    items: [
      { question: "Why are children attracted to new things (such as electronics)?", answer: "New things provide surprise, bright colours and new ways to play. Children are naturally curious and may also copy friends or online influencers. They do not always understand cost or long-term value, so parents need to set reasonable limits." },
      { question: "Why do some grown-ups hate to throw out old things (such as clothes)?", answer: "Old things may carry memories or still seem useful, so throwing them away feels wasteful. Some adults grew up when products were less available. However, keeping too many unused objects can create stress, so donating or recycling is a good compromise." },
      { question: "Is the way people buy things affected? How?", answer: "Yes, technology, advertising, income and social trends strongly affect shopping. Online stores allow people to compare and purchase at any time, while personalised adverts create demand. Reviews can help, but false information and easy payment may also encourage impulsive decisions." },
      { question: "What do you think influences people to buy new things?", answer: "Need, price, quality and advertising are major influences. Friends, celebrities and online reviews can also affect a decision. For expensive items, practical value and reliability should matter most, but emotions and the desire to follow trends often play a role." },
      { question: "Why do all children like toys?", answer: "Most children like toys because they provide fun, imagination and a way to practise real-life roles. Toys can also help them play with others and develop physical skills. Preferences vary, and some children may prefer drawing, books or outdoor activities." },
      { question: "Do you think it is good for a child to always take his or her favourite toy with them all the time?", answer: "A familiar toy can make a young child feel safe in a new place. However, always depending on it may create problems at school or during travel. Parents can allow it in stressful situations while gradually helping the child feel confident without it." },
    ],
  },
  {
    id: "ideal-work",
    category: "事物类",
    title: "理想工作与职业满意度",
    partTwo: "完美工作",
    items: [
      { question: "What jobs do children want to do when they grow up?", answer: "Many children choose familiar or exciting jobs, such as doctors, teachers, athletes, pilots or online creators. Their choices are influenced by family, media and school. These ideas often change when they learn more about their abilities and real working conditions." },
      { question: "What should people consider when choosing jobs?", answer: "They should consider their interests, skills, salary, working hours, location and opportunities to grow. Job security and team culture also matter. No job is perfect, so people need to decide which factors are most important at their current stage of life." },
      { question: "Is salary the main reason people choose a certain job?", answer: "Salary is important because people need to support themselves and their families. However, working hours, interest, stability and relationships also affect long-term happiness. A very high salary may not be worthwhile if the job seriously harms health or personal life." },
      { question: "How have people’s opinions about the “perfect job” changed compared to the past?", answer: "In the past, many people valued stability and staying with one company. Today, younger workers may care more about flexibility, personal growth and work-life balance. Stable income remains important, but people are more willing to change jobs when their needs are not met." },
      { question: "Do you think it’s easy for people to find their ideal job? Why or why not?", answer: "No, because competition, location and economic conditions limit choices. People may also have unrealistic expectations before gaining work experience. Most need to develop skills and try several roles before understanding what kind of job actually suits them." },
      { question: "What is more important for job satisfaction: a high salary or good relationships with colleagues?", answer: "Both matter, but good relationships may be more important after basic financial needs are met. People spend many hours with colleagues, so conflict creates daily stress. A fair salary attracts workers, while a supportive team often makes them want to stay." },
    ],
  },
  {
    id: "disappointing-films",
    category: "事物类",
    title: "电影评价与演员",
    partTwo: "让你失望的电影",
    items: [
      { question: "Do you believe movie reviews?", answer: "I use reviews as a reference but do not believe every opinion. Professional critics may notice technical quality, while ordinary viewers may focus on entertainment. I normally compare several comments and consider whether the reviewer likes the same kind of movies as I do." },
      { question: "What are the different types of films in your country?", answer: "There are comedies, action films, historical dramas, romance, animation, science fiction and documentaries. Domestic films increasingly cover both large national stories and ordinary family life. Different age groups and holiday periods often support different types." },
      { question: "Are historical films popular in your country? Why?", answer: "Yes, some are popular because Chinese history offers many famous events and characters. These films can be educational and visually impressive. However, audiences may criticise them if they change history too much or focus on special effects instead of a clear story." },
      { question: "Do you think films with famous actors or actresses are more likely to become successful films?", answer: "They are more likely to receive attention and strong promotion, but success is not guaranteed. Famous actors cannot repair a confusing story. Good casting means choosing someone suitable for the role, whether that person is already famous or not." },
      { question: "Why are Japanese animated films so popular?", answer: "Many have detailed artwork, emotional stories and themes that both children and adults can understand. They cover more than simple comedy and often create memorable characters. International streaming and long-established studios have also made these films easy to access worldwide." },
      { question: "Should the director pay a lot of money to famous actors?", answer: "It may be worthwhile if the actor fits the role and helps attract enough viewers. However, spending too much on one star can reduce money for writing, visual effects and other actors. The budget should support the whole film, not only its marketing name." },
    ],
  },
];
